// Grade 6 — ratio and rate, percent, negative numbers, the first letters that
// stand for numbers, area by cutting a rectangle in half, and the three
// different things people mean when they say "average".
export const GRADE_6 = [
  {
    id: 'g6_ratio', subject: 'math', standard: '6.RP.A.1', title: 'The Dye Vat',
    story: 'The dyer\'s green is two scoops of blue to three of yellow. Not two and three — '
      + 'two FOR EVERY three. Double the batch and it is four to six, and the colour is identical. '
      + 'A ratio is a recipe that works at any size.',
    steps: [
      { say: 'One batch: two scoops of blue, three of yellow.',
        prompt: 'Make a group of 2 and a group of 3, with a gap between them.',
        hint: 'Two together, a gap, then three together.',
        success: 'Two to three. That is the recipe for meadow green.',
        build: { kind: 'groups', block: 'green_wool', sizes: [2, 3] } },
      { say: 'Double batch. Double BOTH — that is the only way the colour stays the same.',
        prompt: 'Make a group of 4 and a group of 6, with a gap between them.',
        hint: 'Two doubled is four. Three doubled is six.',
        success: 'Four to six is the SAME ratio as two to three. Same green, twice as much.',
        build: { kind: 'groups', block: 'green_wool', sizes: [4, 6] } },
      { say: 'Triple batch.',
        prompt: 'Make a group of 6 and a group of 9, with a gap between them.',
        hint: 'Two times three is six. Three times three is nine.',
        success: 'Six to nine — still the same green!',
        build: { kind: 'groups', block: 'green_wool', sizes: [6, 9] } },
      { say: 'A different colour now. The dyer\'s purple is one to four.',
        prompt: 'Make a group of 1 and a group of 4, with a gap between them.',
        hint: 'One on its own, a gap, then four.',
        success: 'One to four. Much more of the second colour.',
        build: { kind: 'groups', block: 'purple_wool', sizes: [1, 4] } },
      { say: 'Scale the purple up three times.',
        prompt: 'Make a group of 3 and a group of 12, with a gap between them.',
        hint: 'One times three is three. Four times three is twelve — that will need its own row.',
        success: 'Three to twelve is one to four. A ratio scales as far as you like!',
        build: { kind: 'groups', block: 'purple_wool', sizes: [3, 12] } },
    ],
    reward: { coins: 130, items: [['green_wool', 40], ['purple_wool', 40]] },
  },
  {
    id: 'g6_rate', subject: 'math', standard: '6.RP.A.2', title: 'How Much for One?',
    story: 'The market is full of confusing prices: twelve eggs for a certain price, five for another. '
      + 'The only way to compare is to work out what ONE costs. '
      + 'That number is called the UNIT RATE, and it is the shopper\'s best weapon.',
    steps: [
      { say: 'Four baskets, three eggs in each. How many eggs?',
        prompt: 'Build 4 rows with 3 blocks in each row.',
        hint: 'Three in a row, four rows.',
        success: 'Twelve eggs in four baskets.',
        build: { kind: 'array', block: 'white_wool', rows: 4, cols: 3 } },
      { say: 'So how many in ONE basket? Build just that.',
        prompt: 'Build 1 row with 3 blocks in it.',
        hint: 'Twelve shared between four baskets.',
        success: 'Three per basket. That is the unit rate: three eggs PER basket.',
        build: { kind: 'array', block: 'white_wool', rows: 1, cols: 3 } },
      { say: 'The other stall: five baskets, twenty eggs.',
        prompt: 'Make 5 groups of 4, with gaps between them.',
        hint: 'Twenty eggs shared into five baskets.',
        success: 'Four per basket — a better deal than three!',
        build: { kind: 'groups', block: 'white_wool', sizes: [4, 4, 4, 4, 4] } },
      { say: 'Show the two rates side by side: three per basket against four per basket.',
        prompt: 'Build a tower 3 tall on the LEFT and a tower 4 tall on the RIGHT.',
        hint: 'Three on one side of the wooden line, four on the other.',
        success: 'Four beats three. Once everything is "per one", comparing is easy!',
        build: { kind: 'compare', block: 'white_wool', left: 3, right: 4 } },
      { say: 'Last stall. Two baskets, fourteen eggs. What is the rate?',
        prompt: 'Build 2 rows with 7 blocks in each row.',
        hint: 'Fourteen shared between two baskets is seven each.',
        success: 'Seven per basket — the best deal on the market. Buy from that one!',
        build: { kind: 'array', block: 'white_wool', rows: 2, cols: 7 } },
    ],
    reward: { coins: 130, items: [['white_wool', 40], ['yellow_wool', 30]] },
  },
  {
    id: 'g6_percent', subject: 'math', standard: '6.RP.A.3.C', title: 'The Toll Gate',
    story: 'The toll gate takes a PERCENT of everything that goes through. Percent means '
      + '"out of a hundred" — but you can see it much more easily out of ten, '
      + 'because fifty percent and five tenths are the same thing wearing different clothes.',
    steps: [
      { say: 'The gate takes fifty percent. Out of ten, that is…',
        prompt: 'Make a row of 10 blocks with exactly 5 of them red.',
        hint: 'Fifty percent is half. Half of ten is five.',
        success: 'Fifty percent is half — five out of ten.',
        build: { kind: 'fraction', whole: 'white_wool', part: 'red_wool', den: 10, num: 5 } },
      { say: 'A cheaper gate: twenty percent.',
        prompt: 'Make a row of 10 blocks with exactly 2 of them red.',
        hint: 'Twenty percent of ten is two.',
        success: 'Twenty percent — two out of ten, or one fifth.',
        build: { kind: 'fraction', whole: 'white_wool', part: 'red_wool', den: 10, num: 2 } },
      { say: 'A very greedy gate: ninety percent.',
        prompt: 'Make a row of 10 blocks with exactly 9 of them red.',
        hint: 'Nine out of ten.',
        success: 'Ninety percent. Only a tenth gets through — nobody uses that road.',
        build: { kind: 'fraction', whole: 'white_wool', part: 'red_wool', den: 10, num: 9 } },
      { say: 'What if it takes a hundred percent?',
        prompt: 'Make a row of 10 blocks with all 10 of them red.',
        hint: 'Every single one.',
        success: 'A hundred percent is ALL of it. That is not a toll, that is robbery!',
        build: { kind: 'fraction', whole: 'white_wool', part: 'red_wool', den: 10, num: 10 } },
      { say: 'Last gate: thirty percent of ten sacks. Work out the number, then build both piles.',
        prompt: 'Make a group of 3 and a group of 7, with a gap between them.',
        hint: 'Thirty percent of ten is three. The rest — seven — goes through.',
        success: 'Three taken, seven through. Percent works on any number, not just a hundred!',
        build: { kind: 'groups', block: 'red_wool', sizes: [3, 7] } },
    ],
    reward: { coins: 135, items: [['red_wool', 40], ['white_wool', 40]] },
  },
  {
    id: 'g6_neg', subject: 'math', standard: '6.NS.C.5', title: 'Below the Waterline',
    story: 'The harbour marks depth below the water as a MINUS number and height above it as a plus. '
      + 'Zero is the waterline itself. Minus five is not "small" — it is five deep, '
      + 'and it is further from zero than plus three is.',
    steps: [
      { say: 'The mast stands three above the water; the keel hangs two below. Build both from the line.',
        prompt: 'Build a tower 3 tall on the LEFT and a tower 2 tall on the RIGHT.',
        hint: 'Left is above the waterline, right is below. Three one side, two the other.',
        success: 'Plus three and minus two. The wooden line is ZERO.',
        build: { kind: 'compare', block: 'cyan_wool', left: 3, right: 2 } },
      { say: 'A bigger ship: five up, five down. Perfectly balanced.',
        prompt: 'Build a tower 5 tall on the LEFT and a tower 5 tall on the RIGHT.',
        hint: 'Five each side of the line.',
        success: 'Plus five and minus five are OPPOSITES — the same distance from zero, in opposite directions.',
        build: { kind: 'compare', block: 'cyan_wool', left: 5, right: 5 } },
      { say: 'Now a deep-draughted barge: two above, six below.',
        prompt: 'Build a tower 2 tall on the LEFT and a tower 6 tall on the RIGHT.',
        hint: 'Two above, six below.',
        success: 'Minus six is FURTHER from zero than plus two — even though six sounds bigger and it is the minus one.',
        build: { kind: 'compare', block: 'cyan_wool', left: 2, right: 6 } },
      { say: 'How far from the top of the mast to the bottom of the keel? Two up and six down.',
        prompt: 'Build ONE tower exactly 8 tall… the mat is only 7, so build 7 and remember the last one.',
        hint: 'Two and six is eight. The ceiling is seven, so build seven.',
        success: 'Eight blocks of ship, all told. To find a distance across zero you ADD the two depths.',
        build: { kind: 'tower', block: 'cyan_wool', h: 7 } },
      { say: 'Last one. Which is deeper: minus four or minus seven? Build them and look.',
        prompt: 'Build a tower 4 tall on the LEFT and a tower 7 tall on the RIGHT.',
        hint: 'Four one side, seven the other. Deeper means further from the line.',
        success: 'Minus seven is deeper. With minus numbers, the bigger the number the LOWER it is!',
        build: { kind: 'compare', block: 'cyan_wool', left: 4, right: 7 } },
    ],
    reward: { coins: 135, items: [['cyan_wool', 40], ['blue_wool', 30]] },
  },
  {
    id: 'g6_expr', subject: 'math', standard: '6.EE.A.2', title: 'The Unknown Sack',
    story: 'The miller ships flour in sacks, and nobody at the far end knows how many pounds '
      + 'are in one. So they call it "n". Three sacks is three n. '
      + 'You can do arithmetic with a letter perfectly well — right up until you find out what it is.',
    steps: [
      { say: 'One sack. We do not know its size, so call it n — and today n turns out to be four.',
        prompt: 'Build 1 row with 4 blocks in it.',
        hint: 'Four in a row: one sack, four pounds.',
        success: 'n is four.',
        build: { kind: 'array', block: 'brown_wool', rows: 1, cols: 4 } },
      { say: 'Three sacks. That is three n.',
        prompt: 'Build 3 rows with 4 blocks in each row.',
        hint: 'Three rows, four in each — three lots of n.',
        success: 'Three n is twelve, when n is four.',
        build: { kind: 'array', block: 'brown_wool', rows: 3, cols: 4 } },
      { say: 'Now three sacks plus two loose pounds: three n plus two.',
        prompt: 'Make a group of 12 and a group of 2, with a gap between them.',
        hint: 'The twelve from the sacks, and two on their own.',
        success: 'Fourteen. Three n plus two, when n is four, is fourteen.',
        build: { kind: 'groups', block: 'brown_wool', sizes: [12, 2] } },
      { say: 'The mill changes its sacks — now n is six. Three sacks again.',
        prompt: 'Build 3 rows with 6 blocks in each row.',
        hint: 'Three rows of six this time.',
        success: 'Three n is eighteen now. The expression did not change — only n did!',
        build: { kind: 'array', block: 'brown_wool', rows: 3, cols: 6 } },
      { say: 'Last one. Two n plus five, with n still six.',
        prompt: 'Make a group of 12 and a group of 5, with a gap between them.',
        hint: 'Two sixes is twelve, and then five more.',
        success: 'Seventeen. You are doing algebra — the letter is just a number you have not been told yet.',
        build: { kind: 'groups', block: 'brown_wool', sizes: [12, 5] } },
    ],
    reward: { coins: 135, items: [['brown_wool', 40], ['gray_wool', 30]] },
  },
  {
    id: 'g6_tri', subject: 'math', standard: '6.G.A.1', title: 'Half a Rectangle',
    story: 'The roofer needs the area of a triangle and swears there is no formula for it. '
      + 'There is, and it is the easiest one there is: build the triangle as a staircase, '
      + 'build a second one exactly the same, and the two of them make a rectangle.',
    steps: [
      { say: 'Build a staircase: four blocks, then three behind, then two, then one.',
        prompt: 'Build a staircase of 4, 3, 2 and 1 — each row starting at the left edge.',
        hint: 'Front row four, next row three, next two, then one — all lined up on the left.',
        success: 'Ten blocks in a staircase. That is our triangle.',
        build: { kind: 'cells', block: 'orange_wool',
          at: [[0, 0, 0], [1, 0, 0], [2, 0, 0], [3, 0, 0], [0, 0, 1], [1, 0, 1], [2, 0, 1], [0, 0, 2], [1, 0, 2], [0, 0, 3]] } },
      { say: 'Two of those staircases fit together perfectly. Build the rectangle they make: four across, five back.',
        prompt: 'Build 4 rows with 5 blocks in each row.',
        hint: 'Twenty blocks — exactly twice the ten in the staircase.',
        success: 'Twenty, and the staircase was ten. The triangle is HALF the rectangle!',
        build: { kind: 'array', block: 'orange_wool', rows: 4, cols: 5 } },
      { say: 'Try a smaller one. A staircase of three, two, one.',
        prompt: 'Build a staircase of 3, 2 and 1 — each row starting at the left edge.',
        hint: 'Three, then two behind, then one.',
        success: 'Six blocks.',
        build: { kind: 'cells', block: 'orange_wool',
          at: [[0, 0, 0], [1, 0, 0], [2, 0, 0], [0, 0, 1], [1, 0, 1], [0, 0, 2]] } },
      { say: 'And its rectangle: three across, four back.',
        prompt: 'Build 3 rows with 4 blocks in each row.',
        hint: 'Twelve blocks — twice the six.',
        success: 'Twelve, and the staircase was six. Half again!',
        build: { kind: 'array', block: 'orange_wool', rows: 3, cols: 4 } },
      { say: 'One more, bigger: five, four, three, two, one.',
        prompt: 'Build a staircase of 5, 4, 3, 2 and 1 — each row starting at the left edge.',
        hint: 'Five in the front row and one fewer each row going back.',
        success: 'Fifteen — and its rectangle would be five by six, which is thirty. Base times height, divided by two!',
        build: { kind: 'cells', block: 'orange_wool',
          at: [[0, 0, 0], [1, 0, 0], [2, 0, 0], [3, 0, 0], [4, 0, 0],
            [0, 0, 1], [1, 0, 1], [2, 0, 1], [3, 0, 1],
            [0, 0, 2], [1, 0, 2], [2, 0, 2], [0, 0, 3], [1, 0, 3], [0, 0, 4]] } },
    ],
    reward: { coins: 140, items: [['orange_wool', 40]] },
  },
  {
    id: 'g6_stats', subject: 'math', standard: '6.SP.B.5', title: 'Levelling the Bars',
    story: 'Five apprentices each cut a different number of planks and the master wants one number '
      + 'that describes the day. The MEAN is what they would each have cut if the work had been '
      + 'shared perfectly evenly — so knock the tall bars down and fill the short ones up.',
    steps: [
      { say: 'The day\'s work: two, six, three, five and four planks.',
        prompt: 'Build five towers side by side: 2, 6, 3, 5 and 4 tall.',
        hint: 'Five stacks: two, six, three, five, four.',
        success: 'Twenty planks between five apprentices — but very unevenly.',
        build: { kind: 'stack', block: 'brown_wool', heights: [2, 6, 3, 5, 4] } },
      { say: 'Now level them. Twenty planks, five apprentices.',
        prompt: 'Build five towers side by side, all exactly 4 tall.',
        hint: 'Twenty shared between five is four each.',
        success: 'All level at four. The MEAN is four — that is what "average" usually means.',
        build: { kind: 'stack', block: 'brown_wool', heights: [4, 4, 4, 4, 4] } },
      { say: 'A different day, in the order they finished: three, one, seven, one, two.',
        prompt: 'Build five towers side by side: 3, 1, 7, 1 and 2 tall.',
        hint: 'Three, one, seven, one, two — jumbled up, exactly as they came in.',
        success: 'One apprentice did more than the other four together!',
        build: { kind: 'stack', block: 'brown_wool', heights: [3, 1, 7, 1, 2] } },
      { say: 'The MEDIAN is the middle one when they are in ORDER. So put them in order first.',
        prompt: 'Build five towers side by side: 1, 1, 2, 3 and 7 tall.',
        hint: 'Same five numbers, smallest to biggest. The middle tower is the third one.',
        success: 'The median is two. The mean would be nearly three — one big number drags the mean up but not the median.',
        build: { kind: 'stack', block: 'brown_wool', heights: [1, 1, 2, 3, 7] } },
      { say: 'Which one describes that day better? Build the median on its own.',
        prompt: 'Build ONE tower exactly 2 tall.',
        hint: 'The middle value: two.',
        success: 'The median. When one number is wildly out of line, the median tells the truer story!',
        build: { kind: 'tower', block: 'brown_wool', h: 2 } },
    ],
    reward: { coins: 140, items: [['brown_wool', 40], ['light_gray_wool', 30]] },
  },
  {
    id: 'g6_dist', subject: 'math', standard: '6.SP.A.2', title: 'Spread Out or Bunched Up',
    story: 'Two villages both have an average of four children per house — and they look nothing alike. '
      + 'In one, every house has four. In the other, some have none and some have seven. '
      + 'The average is only half the story; the SPREAD is the other half.',
    steps: [
      { say: 'The bunched-up village: every house the same.',
        prompt: 'Build five towers side by side, all exactly 4 tall.',
        hint: 'Five towers, four blocks each.',
        success: 'Mean four, and no spread at all. Every house identical.',
        build: { kind: 'stack', block: 'pink_wool', heights: [4, 4, 4, 4, 4] } },
      { say: 'The spread-out village: one, two, four, six, seven.',
        prompt: 'Build five towers side by side: 1, 2, 4, 6 and 7 tall.',
        hint: 'One, two, four, six, seven — climbing steeply.',
        success: 'Same twenty children, same mean of four — a completely different village!',
        build: { kind: 'stack', block: 'pink_wool', heights: [1, 2, 4, 6, 7] } },
      { say: 'The RANGE measures the spread: biggest take away smallest.',
        prompt: 'Build ONE tower exactly 6 tall.',
        hint: 'Seven take away one is six.',
        success: 'A range of six for the spread village — and a range of ZERO for the bunched one.',
        build: { kind: 'tower', block: 'pink_wool', h: 6 } },
      { say: 'A third village, mostly bunched with one odd house: three, four, four, four, seven.',
        prompt: 'Build five towers side by side: 3, 4, 4, 4 and 7 tall.',
        hint: 'Three, then three fours, then a seven.',
        success: 'Mostly the same, with one OUTLIER standing out at seven.',
        build: { kind: 'stack', block: 'pink_wool', heights: [3, 4, 4, 4, 7] } },
      { say: 'The commonest value is called the MODE. Build it.',
        prompt: 'Build ONE tower exactly 4 tall.',
        hint: 'Four turns up three times — more than any other.',
        success: 'Mode four. Mean, median, mode and range — four ways of describing the same village!',
        build: { kind: 'tower', block: 'pink_wool', h: 4 } },
    ],
    reward: { coins: 140, items: [['pink_wool', 40], ['magenta_wool', 30]] },
  },
  {
    id: 'g6_greek', subject: 'reading', standard: 'L.6.4.B', title: 'Borrowed From the Greeks',
    story: 'Half the difficult words in science are Greek words wearing English clothes. '
      + 'TELE means far. PHONE means sound. SCOPE means to look. Learn eight of these '
      + 'and you can take apart words nobody ever taught you.',
    steps: [
      { say: 'First piece: TELE. It means "far away".',
        prompt: 'Spell TELE.',
        hint: 'T, E, L, E.',
        success: 'TELE — far. Now we need something to do at a distance.',
        build: { kind: 'word', text: 'TELE' } },
      { say: 'PHONE means "sound". Put them together: sound from far away.',
        prompt: 'Spell PHONE.',
        hint: 'P-H-O-N-E. The PH says "f".',
        success: 'PHONE — sound. Telephone: sound from far away. That is exactly what it is!',
        build: { kind: 'word', text: 'PHONE' } },
      { say: 'SCOPE means "to look at". What would a telescope be?',
        prompt: 'Spell SCOPE.',
        hint: 'S, C, O, P, E.',
        success: 'SCOPE — to look. A telescope looks far away, and a microscope looks at tiny things!',
        build: { kind: 'word', text: 'SCOPE' } },
      { say: 'GRAPH means "written down". PHOTO means "light".',
        prompt: 'Spell PHOTOGRAPH.',
        hint: 'P-H-O-T-O then G-R-A-P-H. Ten letters, two Greek words.',
        success: 'PHOTOGRAPH — light, written down. That is precisely what a photograph is!',
        build: { kind: 'word', text: 'PHOTOGRAPH' } },
      { say: 'Three more pieces to keep: BIO means life, GEO means earth, THERM means heat.',
        prompt: 'Spell BIO, GEO and THERM — one on each row.',
        hint: 'B-I-O. G-E-O. T-H-E-R-M.',
        success: 'Biology, geography, thermometer. You can read half a science book already!',
        build: { kind: 'words', list: ['BIO', 'GEO', 'THERM'] } },
    ],
    reward: { coins: 145, items: [['letter_o', 6], ['letter_e', 6], ['letter_h', 4]] },
  },
  {
    id: 'g6_context', subject: 'reading', standard: 'L.6.4.A', title: 'Working It Out From Around It',
    story: 'You will meet words you do not know for the rest of your life, and you will not always '
      + 'have anyone to ask. But sentences leak. The words AROUND a strange word usually give it away — '
      + 'if you know what kind of clue to look for.',
    steps: [
      { say: 'Some clues DEFINE the word outright: "the arid desert, meaning dry, stretched for miles".',
        prompt: 'Spell ARID.',
        hint: 'A, R, I, D. The sentence told you it means dry.',
        success: 'ARID means dry — the sentence handed it to you.',
        build: { kind: 'word', text: 'ARID' } },
      { say: 'Some clues work by OPPOSITE: "she was timid, unlike her bold brother".',
        prompt: 'Spell TIMID.',
        hint: 'T-I-M-I-D. If the brother is bold and she is UNLIKE him…',
        success: 'TIMID is the opposite of bold — shy. The word "unlike" was the clue.',
        build: { kind: 'word', text: 'TIMID' } },
      { say: 'Some clues give EXAMPLES: "vermin such as rats and mice".',
        prompt: 'Spell VERMIN.',
        hint: 'V-E-R-M-I-N. The examples tell you what kind of thing it is.',
        success: 'VERMIN — pests. The examples did the work.',
        build: { kind: 'word', text: 'VERMIN' } },
      { say: 'And sometimes the sentence explains the CAUSE: "the river was frigid, so nobody swam".',
        prompt: 'Spell FRIGID.',
        hint: 'F-R-I-G-I-D. Why did nobody swim?',
        success: 'FRIGID means freezing cold. The reason gave it away!',
        build: { kind: 'word', text: 'FRIGID' } },
      { say: 'Four kinds of clue, four new words. Write three of them out together.',
        prompt: 'Spell ARID, TIMID and VERMIN — one on each row.',
        hint: 'A-R-I-D. T-I-M-I-D. V-E-R-M-I-N.',
        success: 'Definition, opposite, example, cause. You never have to be stuck on a word again!',
        build: { kind: 'words', list: ['ARID', 'TIMID', 'VERMIN'] } },
    ],
    reward: { coins: 150, items: [['hearth_loaf', 5], ['travel_biscuit', 5]] },
  },
];
