// Grade 3 — multiplication and division as equal groups and arrays, area and
// perimeter as two different questions about the same rectangle, fractions as
// parts of one whole, rounding, scaled graphs, and word endings.
export const GRADE_3 = [
  {
    id: 'g3_mult', subject: 'math', standard: '3.OA.A.1', title: 'The Weaver\'s Loom',
    story: 'Maren weaves blankets on a loom, and every blanket is rows of squares. '
      + 'She never counts the squares — she says "four rows of six" and knows it is twenty-four. '
      + 'Multiplication is just a fast way of saying "this many groups of that many".',
    steps: [
      { say: 'The first blanket: three rows of four.',
        prompt: 'Build 3 rows with 4 blocks in each row.',
        hint: 'Four in a row, then four behind it, then four more.',
        success: 'Three fours is twelve. Three TIMES four.',
        build: { kind: 'array', block: 'cyan_wool', rows: 3, cols: 4 } },
      { say: 'Turn the blanket sideways: four rows of three.',
        prompt: 'Build 4 rows with 3 blocks in each row.',
        hint: 'Three in a row, four rows of them.',
        success: 'Still twelve! Four times three is the same as three times four — that is very useful.',
        build: { kind: 'array', block: 'cyan_wool', rows: 4, cols: 3 } },
      { say: 'A wider one: two rows of eight.',
        prompt: 'Build 2 rows with 8 blocks in each row.',
        hint: 'Eight in a row, twice over.',
        success: 'Two eights is sixteen. Doubling — the easiest times table there is.',
        build: { kind: 'array', block: 'cyan_wool', rows: 2, cols: 8 } },
      { say: 'The market blanket: five rows of seven.',
        prompt: 'Build 5 rows with 7 blocks in each row.',
        hint: 'Seven in a row. Five rows. Count in sevens: 7, 14, 21, 28, 35.',
        success: 'Five sevens is thirty-five!',
        build: { kind: 'array', block: 'cyan_wool', rows: 5, cols: 7 } },
      { say: 'And the one she is proudest of: four rows of nine.',
        prompt: 'Build 4 rows with 9 blocks in each row.',
        hint: 'Nine in a row, four times. Nine, eighteen, twenty-seven, thirty-six.',
        success: 'Four nines is thirty-six. You are multiplying properly now!',
        build: { kind: 'array', block: 'cyan_wool', rows: 4, cols: 9 } },
    ],
    reward: { coins: 75, items: [['cyan_wool', 40], ['light_blue_wool', 20]] },
  },
  {
    id: 'g3_div', subject: 'math', standard: '3.OA.A.2', title: 'Sharing the Catch',
    story: 'Four fishers come back to the camp with one big catch and it has to be shared out '
      + 'so nobody grumbles. Dividing means splitting into EQUAL groups. '
      + 'Sometimes it goes exactly — and sometimes there is a fish left over.',
    steps: [
      { say: 'Twelve fish, three fishers. Make three equal piles.',
        prompt: 'Make 3 groups of 4, with gaps between them.',
        hint: 'Deal them out one at a time into three piles until they are gone. Four each.',
        success: 'Twelve shared between three is FOUR each. Nobody is grumbling.',
        build: { kind: 'groups', block: 'light_blue_wool', sizes: [4, 4, 4] } },
      { say: 'The same twelve fish, but four fishers now.',
        prompt: 'Make 4 groups of 3, with gaps between them.',
        hint: 'Four piles this time. Twelve shared four ways.',
        success: 'Three each. More people, smaller share — dividing always works that way.',
        build: { kind: 'groups', block: 'light_blue_wool', sizes: [3, 3, 3, 3] } },
      { say: 'A bigger catch: twenty fish, four fishers.',
        prompt: 'Make 4 groups of 5, with gaps between them.',
        hint: 'Twenty shared into four piles. Five in each.',
        success: 'Five each. Twenty divided by four is five!',
        build: { kind: 'groups', block: 'light_blue_wool', sizes: [5, 5, 5, 5] } },
      { say: 'Now a catch that will not share evenly. Thirteen fish, three fishers.',
        prompt: 'Make 3 groups of 4 and 1 group of 1.',
        hint: 'Four each, and then one fish that will not fit anywhere.',
        success: 'Four each with one left over. That leftover has a name: the REMAINDER.',
        build: { kind: 'groups', block: 'light_blue_wool', sizes: [4, 4, 4, 1] } },
      { say: 'Last catch. Fifteen fish, five fishers — and this one is exact.',
        prompt: 'Make 5 groups of 3, with gaps between them.',
        hint: 'Five piles of three. Fifteen divided by five.',
        success: 'Three each, nothing left over. Everybody eats!',
        build: { kind: 'groups', block: 'light_blue_wool', sizes: [3, 3, 3, 3, 3] } },
    ],
    reward: { coins: 75, items: [['light_blue_wool', 30], ['hearth_loaf', 3]] },
  },
  {
    id: 'g3_area', subject: 'math', standard: '3.MD.C.7', title: 'Tiling the Workshop',
    story: 'The workshop floor needs tiling and the tiler charges by the tile. '
      + 'AREA is how many tiles it takes to COVER a floor — every square counted, '
      + 'not just the edges. Rows times columns, every time.',
    steps: [
      { say: 'The small storeroom: three across, three back.',
        prompt: 'Build 3 rows with 3 blocks in each row.',
        hint: 'Cover the whole square — every tile, not just the edge.',
        success: 'Nine tiles. Three times three is an area of nine.',
        build: { kind: 'array', block: 'gray_wool', rows: 3, cols: 3 } },
      { say: 'The workbench corner: two back, six across.',
        prompt: 'Build 2 rows with 6 blocks in each row.',
        hint: 'Six along, two deep. Cover it all.',
        success: 'Twelve tiles. A long thin room can have the same area as a fat one!',
        build: { kind: 'array', block: 'gray_wool', rows: 2, cols: 6 } },
      { say: 'Prove that. Three back, four across — different shape, same area.',
        prompt: 'Build 3 rows with 4 blocks in each row.',
        hint: 'Four along, three deep.',
        success: 'Twelve again! Two different rooms, both needing twelve tiles.',
        build: { kind: 'array', block: 'gray_wool', rows: 3, cols: 4 } },
      { say: 'The main floor: four back, eight across.',
        prompt: 'Build 4 rows with 8 blocks in each row.',
        hint: 'Eight along, four deep. Count in eights: 8, 16, 24, 32.',
        success: 'Thirty-two tiles for the main floor!',
        build: { kind: 'array', block: 'gray_wool', rows: 4, cols: 8 } },
      { say: 'And the hall, the biggest of the lot: five back, ten across.',
        prompt: 'Build 5 rows with 10 blocks in each row.',
        hint: 'Ten along, five deep. Ten, twenty, thirty, forty, fifty.',
        success: 'Fifty tiles. The workshop is floored and you did the whole quote in your head!',
        build: { kind: 'array', block: 'gray_wool', rows: 5, cols: 10 } },
    ],
    reward: { coins: 80, items: [['gray_wool', 50], ['light_gray_wool', 20]] },
  },
  {
    id: 'g3_perim', subject: 'math', standard: '3.MD.D.8', title: 'Fencing the Paddock',
    story: 'The goats keep escaping and the fence has to go all the way AROUND. '
      + 'That is perimeter: the distance round the edge. It is a completely different question '
      + 'from area — one is the fence, the other is the grass.',
    steps: [
      { say: 'The little pen: three across, three back, edges only.',
        prompt: 'Build the OUTLINE of a 3 by 3 square — nothing in the middle.',
        hint: 'Go round the edge. Leave the middle square empty — that is the grass.',
        success: 'Eight fence posts round a 3 by 3 pen. The middle stays empty!',
        build: { kind: 'frame', block: 'brown_wool', w: 3, d: 3 } },
      { say: 'A longer paddock: five across, three back.',
        prompt: 'Build the OUTLINE of a rectangle 5 across and 3 back.',
        hint: 'Five along the front, five along the back, and the two ends. The middle is empty.',
        success: 'Sixteen posts. Five and five and one and one — round the edge.',
        build: { kind: 'frame', block: 'brown_wool', w: 5, d: 3 } },
      { say: 'The big field: eight across, four back.',
        prompt: 'Build the OUTLINE of a rectangle 8 across and 4 back.',
        hint: 'Eight along the top, eight along the bottom, and two down each side.',
        success: 'Twenty posts round the big field!',
        build: { kind: 'frame', block: 'brown_wool', w: 8, d: 4 } },
      { say: 'Now the same rectangle, but FILLED — that is the grass the goats eat.',
        prompt: 'Build 4 rows with 8 blocks in each row.',
        hint: 'This time cover the whole thing, middle included.',
        success: 'Thirty-two squares of grass, but only twenty posts of fence. Different questions, different answers!',
        build: { kind: 'array', block: 'green_wool', rows: 4, cols: 8 } },
      { say: 'Last one. A long thin run: eleven across, two back.',
        prompt: 'Build the OUTLINE of a rectangle 11 across and 2 back.',
        hint: 'Eleven along the front and eleven along the back — with only two deep there is no middle.',
        success: 'Twenty-two posts. The goats are staying put!',
        build: { kind: 'frame', block: 'brown_wool', w: 11, d: 2 } },
    ],
    reward: { coins: 80, items: [['brown_wool', 40], ['green_wool', 32]] },
  },
  {
    id: 'g3_frac', subject: 'math', standard: '3.NF.A.1', title: 'The Miller\'s Measure',
    story: 'The miller sells flour by the sack, and a sack is always cut into the same number of '
      + 'scoops. The BOTTOM number tells you how many scoops the sack was cut into. '
      + 'The TOP number tells you how many you are taking home.',
    steps: [
      { say: 'A sack cut into four. Take one scoop.',
        prompt: 'Make a row of 4 blocks with exactly 1 of them magenta.',
        hint: 'Four in a row, one of them magenta.',
        success: 'One quarter — one out of four.',
        build: { kind: 'fraction', whole: 'white_wool', part: 'magenta_wool', den: 4, num: 1 } },
      { say: 'Take three of the four instead.',
        prompt: 'Make a row of 4 blocks with exactly 3 of them magenta.',
        hint: 'Four in a row, three magenta.',
        success: 'Three quarters. The bottom stayed the same — only your share changed.',
        build: { kind: 'fraction', whole: 'white_wool', part: 'magenta_wool', den: 4, num: 3 } },
      { say: 'A sack cut into six. Take five.',
        prompt: 'Make a row of 6 blocks with exactly 5 of them magenta.',
        hint: 'Six in a row, five magenta, one white.',
        success: 'Five sixths — nearly the whole sack.',
        build: { kind: 'fraction', whole: 'white_wool', part: 'magenta_wool', den: 6, num: 5 } },
      { say: 'A sack cut into eight, and you only want three.',
        prompt: 'Make a row of 8 blocks with exactly 3 of them magenta.',
        hint: 'Eight in a row, three of them magenta.',
        success: 'Three eighths. Cut into more pieces, so each one is smaller.',
        build: { kind: 'fraction', whole: 'white_wool', part: 'magenta_wool', den: 8, num: 3 } },
      { say: 'Last. What does the WHOLE sack look like as a fraction? Six out of six.',
        prompt: 'Make a row of 6 blocks with all 6 of them magenta.',
        hint: 'Six in a row, every one magenta.',
        success: 'Six sixths is ONE WHOLE. When the top and bottom match, you have all of it!',
        build: { kind: 'fraction', whole: 'white_wool', part: 'magenta_wool', den: 6, num: 6 } },
    ],
    reward: { coins: 80, items: [['magenta_wool', 30], ['white_wool', 30]] },
  },
  {
    id: 'g3_equiv', subject: 'math', standard: '3.NF.A.3', title: 'Same Cake, Different Knife',
    story: 'Two bakers argue all morning. One cuts her cake in two and sells you one piece. '
      + 'The other cuts hers in four and sells you two. You are getting exactly the same amount — '
      + 'fractions that look different can be worth the same.',
    steps: [
      { say: 'The first baker: cut in two, take one.',
        prompt: 'Make a row of 2 blocks with exactly 1 of them lime.',
        hint: 'Two blocks, one lime.',
        success: 'One half.',
        build: { kind: 'fraction', whole: 'white_wool', part: 'lime_wool', den: 2, num: 1 } },
      { say: 'The second baker: cut in four, take two.',
        prompt: 'Make a row of 4 blocks with exactly 2 of them lime.',
        hint: 'Four blocks, two lime.',
        success: 'Two quarters — and it covers exactly the same amount of cake as one half!',
        build: { kind: 'fraction', whole: 'white_wool', part: 'lime_wool', den: 4, num: 2 } },
      { say: 'A third baker cuts hers into six. How many pieces make a half?',
        prompt: 'Make a row of 6 blocks with exactly 3 of them lime.',
        hint: 'Half of six is three.',
        success: 'Three sixths is a half too. They are all the same size of cake!',
        build: { kind: 'fraction', whole: 'white_wool', part: 'lime_wool', den: 6, num: 3 } },
      { say: 'And the fussy baker who cuts into eight?',
        prompt: 'Make a row of 8 blocks with exactly 4 of them lime.',
        hint: 'Half of eight is four.',
        success: 'Four eighths. One half, two quarters, three sixths, four eighths — all the same!',
        build: { kind: 'fraction', whole: 'white_wool', part: 'lime_wool', den: 8, num: 4 } },
      { say: 'Now try a different one. A third — and then the same amount cut twice as fine.',
        prompt: 'Make a row of 6 blocks with exactly 2 of them lime.',
        hint: 'A third of six is two.',
        success: 'Two sixths is the same as one third. Cut every piece in two and BOTH numbers double!',
        build: { kind: 'fraction', whole: 'white_wool', part: 'lime_wool', den: 6, num: 2 } },
    ],
    reward: { coins: 85, items: [['lime_wool', 30], ['white_wool', 30]] },
  },
  {
    id: 'g3_round', subject: 'math', standard: '3.NBT.A.1', title: 'Near Enough for the Cart',
    story: 'The carter will not carry an exact number of anything — he wants it to the nearest ten, '
      + 'so he knows how many crates to bring. Rounding is picking the closest ten. '
      + 'If you are past halfway, you go up. If not, you stay down.',
    steps: [
      { say: 'Twenty-three sacks. Is that closer to twenty or to thirty?',
        prompt: 'Make two rows of 10 and one row of 3.',
        hint: 'Two whole tens and three left over. Three is a small leftover.',
        success: 'Only three past twenty — not even halfway. It rounds DOWN to twenty.',
        build: { kind: 'groups', block: 'yellow_wool', sizes: [10, 10, 3] } },
      { say: 'Now twenty-eight.',
        prompt: 'Make two rows of 10 and one row of 8.',
        hint: 'Two tens and eight. Eight is a big leftover — nearly another whole ten.',
        success: 'Eight past twenty is well past halfway. It rounds UP to thirty!',
        build: { kind: 'groups', block: 'yellow_wool', sizes: [10, 10, 8] } },
      { say: 'The awkward one. Twenty-five is exactly halfway. The rule is: halfway goes UP.',
        prompt: 'Make two rows of 10 and one row of 5.',
        hint: 'Two tens and five — right in the middle.',
        success: 'Five is the halfway mark, and halfway always rounds UP. Twenty-five becomes thirty.',
        build: { kind: 'groups', block: 'yellow_wool', sizes: [10, 10, 5] } },
      { say: 'Forty-one. Barely over.',
        prompt: 'Make four rows of 10 and one row of 1.',
        hint: 'Four tens and a single one.',
        success: 'One past forty. Rounds down to forty — the carter brings four crates.',
        build: { kind: 'groups', block: 'yellow_wool', sizes: [10, 10, 10, 10, 1] } },
      { say: 'Last load. Thirty-nine.',
        prompt: 'Make three rows of 10 and one row of 9.',
        hint: 'Three tens and nine — one short of another whole ten.',
        success: 'Nine past thirty rounds UP to forty. The cart is loaded and away!',
        build: { kind: 'groups', block: 'yellow_wool', sizes: [10, 10, 10, 9] } },
    ],
    reward: { coins: 85, items: [['yellow_wool', 50]] },
  },
  {
    id: 'g3_graph', subject: 'math', standard: '3.MD.B.3', title: 'When One Block Means Five',
    story: 'Pip counted every bird that came to the feeder this week and some days had thirty. '
      + 'The mat is only seven high. So each block is going to stand for FIVE birds — '
      + 'that is called a SCALE, and reading a scaled graph is a proper grown-up skill.',
    steps: [
      { say: 'Monday: fifteen birds. At five to a block, that is three blocks.',
        prompt: 'Build ONE tower exactly 3 tall.',
        hint: 'Fifteen shared into fives is three. Three blocks tall.',
        success: 'Three blocks means fifteen birds. The key at the bottom tells you the scale!',
        build: { kind: 'tower', block: 'cyan_wool', h: 3 } },
      { say: 'Tuesday twenty-five, Wednesday ten. Add them to the graph.',
        prompt: 'Build three towers side by side: 3, 5 and 2 tall.',
        hint: 'Fifteen is three blocks, twenty-five is five, ten is two.',
        success: 'Three days on one graph, and every block worth five birds.',
        build: { kind: 'stack', block: 'cyan_wool', heights: [3, 5, 2] } },
      { say: 'Thursday was the big day: thirty-five birds.',
        prompt: 'Build four towers side by side: 3, 5, 2 and 7 tall.',
        hint: 'Thirty-five divided by five is seven — right to the top of the mat.',
        success: 'Seven blocks, thirty-five birds. Thursday wins!',
        build: { kind: 'stack', block: 'cyan_wool', heights: [3, 5, 2, 7] } },
      { say: 'How many MORE came on Thursday than on Wednesday? Seven blocks take away two.',
        prompt: 'Build ONE tower exactly 5 tall.',
        hint: 'Five blocks of difference — and each block is five birds, so that is twenty-five more.',
        success: 'Five blocks: twenty-five more birds. You read the scale AND did the subtraction!',
        build: { kind: 'tower', block: 'cyan_wool', h: 5 } },
      { say: 'The whole week, in order, smallest to biggest.',
        prompt: 'Build five towers side by side: 1, 2, 3, 5 and 7 tall.',
        hint: 'One, two, three, five, seven — climbing up like steps.',
        success: 'A full week of birds, sorted. Pip is delighted with her graph!',
        build: { kind: 'stack', block: 'cyan_wool', heights: [1, 2, 3, 5, 7] } },
    ],
    reward: { coins: 85, items: [['cyan_wool', 30], ['blue_wool', 24]] },
  },
  {
    id: 'g3_suffix', subject: 'reading', standard: 'RF.3.3.A', title: 'The Ending Changes Everything',
    story: 'A little tail on the end of a word can move it through time. JUMP is what you do. '
      + 'JUMPED already happened. JUMPING is happening right now. '
      + 'Learn the endings and you get three words for the price of one.',
    steps: [
      { say: 'Start with the plain word: what the goat does over the fence.',
        prompt: 'Spell JUMP.',
        hint: 'J, U, M, P.',
        success: 'JUMP — happening any time.',
        build: { kind: 'word', text: 'JUMP' } },
      { say: 'Now put it in the past. Add E-D.',
        prompt: 'Spell JUMPED.',
        hint: 'J-U-M-P and then E-D on the end.',
        success: 'JUMPED. The E-D ending means it already happened!',
        build: { kind: 'word', text: 'JUMPED' } },
      { say: 'And happening right now: add I-N-G.',
        prompt: 'Spell JUMPING.',
        hint: 'J-U-M-P and then I-N-G.',
        success: 'JUMPING. Same word, three different times!',
        build: { kind: 'word', text: 'JUMPING' } },
      { say: 'Try it on a new word. PLANT, and then what Maren did yesterday.',
        prompt: 'Spell PLANTED.',
        hint: 'P-L-A-N-T and then E-D.',
        success: 'PLANTED. The rule works on words you have never seen before — that is why rules are worth learning.',
        build: { kind: 'word', text: 'PLANTED' } },
      { say: 'Last three. All happening right now: READING, WALKING and PAINTING.',
        prompt: 'Spell READING, WALKING and PAINTING — one on each row.',
        hint: 'READ plus ING. WALK plus ING. PAINT plus ING.',
        success: 'Three words, one ending. You can build hundreds of words with this!',
        build: { kind: 'words', list: ['READING', 'WALKING', 'PAINTING'] } },
    ],
    reward: { coins: 85, items: [['letter_i', 6], ['letter_n', 6], ['letter_g', 6]] },
  },
  {
    id: 'g3_syll', subject: 'reading', standard: 'RF.3.3.C', title: 'Clapping the Beats',
    story: 'Every word has beats in it, like a little drum. CAT has one. RAB-BIT has two. '
      + 'BUT-TER-FLY has three. Clap them out and even the longest word breaks into pieces '
      + 'small enough to read. Build a tower for each beat.',
    steps: [
      { say: 'Clap the word CAT. One beat.',
        prompt: 'Build ONE tower exactly 1 tall.',
        hint: 'One block — one clap.',
        success: 'One beat. One syllable!',
        build: { kind: 'tower', block: 'orange_wool', h: 1 } },
      { say: 'Now RAB-BIT. Clap it: two.',
        prompt: 'Build ONE tower exactly 2 tall.',
        hint: 'Two blocks — RAB, BIT.',
        success: 'Two beats. Two syllables!',
        build: { kind: 'tower', block: 'orange_wool', h: 2 } },
      { say: 'BUT-TER-FLY. Clap all three.',
        prompt: 'Build ONE tower exactly 3 tall.',
        hint: 'BUT, TER, FLY. Three claps, three blocks.',
        success: 'Three syllables. The word is long but the pieces are small!',
        build: { kind: 'tower', block: 'orange_wool', h: 3 } },
      { say: 'Four words, four towers: CAT, RABBIT, BUTTERFLY, and CA-TER-PIL-LAR.',
        prompt: 'Build four towers side by side: 1, 2, 3 and 4 tall.',
        hint: 'One, two, three, four — one block for each beat.',
        success: 'Even a four-beat word is easy once you clap it into pieces.',
        build: { kind: 'stack', block: 'orange_wool', heights: [1, 2, 3, 4] } },
      { say: 'Now spell one of the two-beat words: RAB-BIT.',
        prompt: 'Spell RABBIT.',
        hint: 'RAB, then BIT. Two double letters in the middle.',
        success: 'RABBIT — read in two easy pieces instead of one hard one!',
        build: { kind: 'word', text: 'RABBIT' } },
    ],
    reward: { coins: 90, items: [['hearth_loaf', 4], ['travel_biscuit', 4]] },
  },
];
