// Grade 7 — proportional reasoning, scale, integers with direction, percent
// change, the surface and the volume of the same solid, probability as a
// fraction you can hold, sampling, and the language of argument.
export const GRADE_7 = [
  {
    id: 'g7_prop', subject: 'math', standard: '7.RP.A.2', title: 'The Recipe Book',
    story: 'The camp cook writes every recipe for four people and never for any other number. '
      + 'Feeding twelve means scaling everything by the same factor — not adding a bit more of '
      + 'whatever runs out. A proportional relationship keeps its shape at any size.',
    steps: [
      { say: 'The stew for four: two measures of barley, three of roots.',
        prompt: 'Make a group of 2 and a group of 3, with a gap between them.',
        hint: 'Two together, a gap, three together.',
        success: 'Two and three, for four people.',
        build: { kind: 'groups', block: 'yellow_wool', sizes: [2, 3] } },
      { say: 'Eight people turn up. That is twice as many, so everything doubles.',
        prompt: 'Make a group of 4 and a group of 6, with a gap between them.',
        hint: 'Two doubled and three doubled.',
        success: 'Four and six. Both ingredients doubled — that is what keeps the taste right.',
        build: { kind: 'groups', block: 'yellow_wool', sizes: [4, 6] } },
      { say: 'Twelve people: three times the original.',
        prompt: 'Make a group of 6 and a group of 9, with a gap between them.',
        hint: 'Two times three, and three times three.',
        success: 'Six and nine. Every batch has the same taste because the RATIO never changed.',
        build: { kind: 'groups', block: 'yellow_wool', sizes: [6, 9] } },
      { say: 'Here is the constant of proportionality. For every 2 of barley there are 3 of roots — build one batch as rows to see it.',
        prompt: 'Build 3 rows with 2 blocks in each row.',
        hint: 'Three rows of two: one row of barley for every… no, one COLUMN of barley for every group of three.',
        success: 'Six blocks, three rows of two. Scaling a recipe is just multiplying an array!',
        build: { kind: 'array', block: 'yellow_wool', rows: 3, cols: 2 } },
      { say: 'Last: twenty people is five times the recipe. Ten of barley, fifteen of roots.',
        prompt: 'Make a group of 10 and a group of 12, with a gap between them.',
        hint: 'The mat only holds thirteen in a row, so we cap the roots at twelve — build ten and twelve.',
        success: 'Scaled up five times over. Every cook in the camp should learn this!',
        build: { kind: 'groups', block: 'yellow_wool', sizes: [10, 12] } },
    ],
    reward: { coins: 150, items: [['yellow_wool', 40], ['orange_wool', 30]] },
  },
  {
    id: 'g7_scale', subject: 'math', standard: '7.G.A.1', title: 'The Scale Drawing',
    story: 'The builder\'s plan is drawn at one square to the foot, and the barn will be built '
      + 'at three. Everything on the plan gets multiplied by the same number — '
      + 'and the AREA does something surprising when it does.',
    steps: [
      { say: 'The plan: two squares by three.',
        prompt: 'Build 2 rows with 3 blocks in each row.',
        hint: 'Three in a row, two rows.',
        success: 'Six squares on the plan.',
        build: { kind: 'array', block: 'gray_wool', rows: 2, cols: 3 } },
      { say: 'Double the scale. Both sides double: four by six.',
        prompt: 'Build 4 rows with 6 blocks in each row.',
        hint: 'Two doubled is four, three doubled is six.',
        success: 'Twenty-four squares — and the plan was six. Doubling the SIDES made FOUR times the area!',
        build: { kind: 'array', block: 'gray_wool', rows: 4, cols: 6 } },
      { say: 'That surprises everybody. Check it on a smaller one. The plan: two by two.',
        prompt: 'Build 2 rows with 2 blocks in each row.',
        hint: 'A little square of four.',
        success: 'Four squares.',
        build: { kind: 'array', block: 'light_gray_wool', rows: 2, cols: 2 } },
      { say: 'Double both sides: four by four.',
        prompt: 'Build 4 rows with 4 blocks in each row.',
        hint: 'Four rows, four in each.',
        success: 'Sixteen — four times as much, from doubling. It happens every time.',
        build: { kind: 'array', block: 'light_gray_wool', rows: 4, cols: 4 } },
      { say: 'Now triple a two-by-three plan: six by nine would not fit, so build three by nine and picture the rest.',
        prompt: 'Build 3 rows with 9 blocks in each row.',
        hint: 'Nine in a row, three rows — half of the tripled barn.',
        success: 'Tripling the sides gives NINE times the area. Three squared. That is why builders check twice!',
        build: { kind: 'array', block: 'light_gray_wool', rows: 3, cols: 9 } },
    ],
    reward: { coins: 150, items: [['gray_wool', 40], ['light_gray_wool', 40]] },
  },
  {
    id: 'g7_int', subject: 'math', standard: '7.NS.A.1', title: 'Debt and Coin',
    story: 'The camp keeps one ledger for coins owed and one for coins held. '
      + 'A debt is a negative number, and adding a debt to a purse makes the purse smaller. '
      + 'The wooden line is nothing at all — zero — and everything is measured from it.',
    steps: [
      { say: 'Five coins in the purse, three coins owed.',
        prompt: 'Build a tower 5 tall on the LEFT and a tower 3 tall on the RIGHT.',
        hint: 'Five above the line, three below it.',
        success: 'Plus five and minus three. Cancel them off and two coins survive.',
        build: { kind: 'compare', block: 'yellow_wool', left: 5, right: 3 } },
      { say: 'So build what is actually left after the debt is paid.',
        prompt: 'Build ONE tower exactly 2 tall.',
        hint: 'Five take away three.',
        success: 'Two coins. Five plus minus three is TWO.',
        build: { kind: 'tower', block: 'yellow_wool', h: 2 } },
      { say: 'Now the debt is bigger than the purse: four coins, six owed.',
        prompt: 'Build a tower 4 tall on the LEFT and a tower 6 tall on the RIGHT.',
        hint: 'Four above the line, six below.',
        success: 'Four cancels four, and two of the debt is left over. That is minus two.',
        build: { kind: 'compare', block: 'yellow_wool', left: 4, right: 6 } },
      { say: 'Build the leftover debt on its own so the ledger is honest.',
        prompt: 'Build ONE tower exactly 2 tall.',
        hint: 'Six take away four is two — and it is on the debt side, so it is MINUS two.',
        success: 'Minus two. When the debt is bigger, the answer is negative — always.',
        build: { kind: 'tower', block: 'yellow_wool', h: 2 } },
      { say: 'Taking away a debt is the same as being GIVEN coins. Seven coins, and a debt of three is forgiven.',
        prompt: 'Build ONE tower exactly 7 tall.',
        hint: 'Seven, and forgiving a three-coin debt makes you three better off — but the mat stops at seven.',
        success: 'Subtracting a negative ADDS. That is the strangest rule in arithmetic, and now you have seen why!',
        build: { kind: 'tower', block: 'yellow_wool', h: 7 } },
    ],
    reward: { coins: 155, items: [['yellow_wool', 40]] },
  },
  {
    id: 'g7_percent', subject: 'math', standard: '7.RP.A.3', title: 'Twenty Percent Off',
    story: 'Market day, and every stall is shouting a different discount. '
      + 'Percent OFF is the bit you do not pay; percent ON is the bit added. '
      + 'Work out the piece first and the price second, and no trader will ever catch you out.',
    steps: [
      { say: 'A sack costs ten coins with twenty percent off. Show the twenty percent.',
        prompt: 'Make a row of 10 blocks with exactly 2 of them red.',
        hint: 'Twenty percent of ten is two. Ten in a row, two red.',
        success: 'Two coins off. So you pay eight.',
        build: { kind: 'fraction', whole: 'white_wool', part: 'red_wool', den: 10, num: 2 } },
      { say: 'Build what you actually pay: eight coins.',
        prompt: 'Make a group of 8, on its own.',
        hint: 'Ten take away two.',
        success: 'Eight coins. Twenty percent off ten is eight.',
        build: { kind: 'groups', block: 'white_wool', sizes: [8] } },
      { say: 'The next stall says half price. That is fifty percent off.',
        prompt: 'Make a row of 10 blocks with exactly 5 of them red.',
        hint: 'Fifty percent of ten is five.',
        success: 'Five off, five to pay. Half price is fifty percent off.',
        build: { kind: 'fraction', whole: 'white_wool', part: 'red_wool', den: 10, num: 5 } },
      { say: 'The last stall ADDS ten percent for delivery on a ten-coin sack.',
        prompt: 'Make a group of 10 and a group of 1, with a gap between them.',
        hint: 'The ten you owe, and one more added on.',
        success: 'Eleven coins. Percent ON is added to the whole, not taken off it.',
        build: { kind: 'groups', block: 'white_wool', sizes: [10, 1] } },
      { say: 'The trick question. Twenty percent off, then twenty percent back on — do you end up where you started?',
        prompt: 'Make a group of 8 and a group of 1, with a gap between them.',
        hint: 'Ten becomes eight. Twenty percent of EIGHT is one and a half — call it one and a bit. Build eight and one.',
        success: 'No! You end up below where you started, because the second percent was of a smaller number. Traders know this.',
        build: { kind: 'groups', block: 'white_wool', sizes: [8, 1] } },
    ],
    reward: { coins: 155, items: [['white_wool', 40], ['red_wool', 30]] },
  },
  {
    id: 'g7_surface', subject: 'math', standard: '7.G.B.6', title: 'Wrapping the Crate',
    story: 'The same crate needs two different numbers: how much STRAW fills it, and how much '
      + 'CANVAS covers it. Volume fills, surface area covers, and confusing the two is how '
      + 'you end up with a quarter of the canvas you needed.',
    steps: [
      { say: 'Build the crate: three long, two deep, two high.',
        prompt: 'Build a solid block 3 across, 2 back and 2 tall.',
        hint: 'A floor of three by two, and a second layer on top.',
        success: 'Twelve blocks of straw fill it. That is the VOLUME.',
        build: { kind: 'box', block: 'brown_wool', w: 3, d: 2, h: 2 } },
      { say: 'Now the canvas. Lay out the top face flat: three by two.',
        prompt: 'Build 2 rows with 3 blocks in each row.',
        hint: 'Three across, two back — one flat face.',
        success: 'Six for the top. And the bottom is the same, so twelve so far.',
        build: { kind: 'array', block: 'white_wool', rows: 2, cols: 3 } },
      { say: 'The front face: three long and two high — same six, laid flat.',
        prompt: 'Build 2 rows with 3 blocks in each row.',
        hint: 'Three by two again. The front and the back match.',
        success: 'Six for the front, six for the back. Twenty-four so far.',
        build: { kind: 'array', block: 'white_wool', rows: 2, cols: 3 } },
      { say: 'And the two little ends: two by two.',
        prompt: 'Build 2 rows with 2 blocks in each row.',
        hint: 'A little square of four.',
        success: 'Four each end, eight for the pair. Twenty-four and eight is THIRTY-TWO.',
        build: { kind: 'array', block: 'white_wool', rows: 2, cols: 2 } },
      { say: 'Lay out the whole sheet of canvas at once: thirty-two squares.',
        prompt: 'Put exactly 32 white blocks on the mat.',
        hint: 'Thirty-two — fill rows across the mat until you have that many.',
        success: 'Volume twelve, surface thirty-two. Never the same number, and never the same question!',
        build: { kind: 'count', block: 'white_wool', n: 32 } },
    ],
    reward: { coins: 160, items: [['white_wool', 50], ['brown_wool', 30]] },
  },
  {
    id: 'g7_volume', subject: 'math', standard: '7.G.B.6', title: 'The Water Tank',
    story: 'The camp is building a water tank and the mason wants to know how many buckets it holds '
      + 'before he lays a single stone. Any straight-sided tank holds the area of its floor, '
      + 'times its depth. Every time, whatever the shape of the floor.',
    steps: [
      { say: 'The floor first: four long, three deep.',
        prompt: 'Build 3 rows with 4 blocks in each row.',
        hint: 'Four in a row, three rows.',
        success: 'Twelve buckets in one layer.',
        build: { kind: 'array', block: 'light_blue_wool', rows: 3, cols: 4 } },
      { say: 'Now fill it two deep.',
        prompt: 'Build a solid block 4 across, 3 back and 2 tall.',
        hint: 'The same floor, with a whole second layer on top.',
        success: 'Twenty-four buckets. Floor area times depth.',
        build: { kind: 'box', block: 'light_blue_wool', w: 4, d: 3, h: 2 } },
      { say: 'Three deep.',
        prompt: 'Build a solid block 4 across, 3 back and 3 tall.',
        hint: 'Three complete layers of twelve.',
        success: 'Thirty-six. Each extra layer adds another whole floor.',
        build: { kind: 'box', block: 'light_blue_wool', w: 4, d: 3, h: 3 } },
      { say: 'A narrower, deeper tank: two long, two deep, five high. Guess before you build.',
        prompt: 'Build a solid block 2 across, 2 back and 5 tall.',
        hint: 'A floor of four, stacked five high.',
        success: 'Twenty. Deep and narrow holds less than you would think!',
        build: { kind: 'box', block: 'light_blue_wool', w: 2, d: 2, h: 5 } },
      { say: 'And the cistern: six long, four deep, two high.',
        prompt: 'Build a solid block 6 across, 4 back and 2 tall.',
        hint: 'Twenty-four in a layer, two layers.',
        success: 'Forty-eight buckets. The mason can order his stone!',
        build: { kind: 'box', block: 'light_blue_wool', w: 6, d: 4, h: 2 } },
    ],
    reward: { coins: 160, items: [['light_blue_wool', 50]] },
  },
  {
    id: 'g7_prob', subject: 'math', standard: '7.SP.C.7', title: 'The Bag of Stones',
    story: 'The fair has a game: a bag of ten stones, and you win if you draw a red one. '
      + 'The chance of winning is simply how many win, out of how many there are — '
      + 'a fraction, and you can hold it in your hands.',
    steps: [
      { say: 'Ten stones, three of them red. Lay the bag out.',
        prompt: 'Make a row of 10 blocks with exactly 3 of them red.',
        hint: 'Ten in a row — the whole bag. Three red.',
        success: 'Three out of ten. A three-in-ten chance of winning.',
        build: { kind: 'fraction', whole: 'gray_wool', part: 'red_wool', den: 10, num: 3 } },
      { say: 'The stallholder swaps two greys for reds. Now five are red.',
        prompt: 'Make a row of 10 blocks with exactly 5 of them red.',
        hint: 'Five red, five grey.',
        success: 'Five out of ten — an even chance. As likely as not.',
        build: { kind: 'fraction', whole: 'gray_wool', part: 'red_wool', den: 10, num: 5 } },
      { say: 'What would a CERTAIN win look like?',
        prompt: 'Make a row of 10 blocks with all 10 of them red.',
        hint: 'Every stone red.',
        success: 'Ten out of ten. Certain — a probability of one. Nobody runs that stall.',
        build: { kind: 'fraction', whole: 'gray_wool', part: 'red_wool', den: 10, num: 10 } },
      { say: 'And IMPOSSIBLE?',
        prompt: 'Make a row of 10 blocks with none of them red.',
        hint: 'Ten grey stones and no red at all.',
        success: 'Nought out of ten. Impossible — a probability of zero. Every chance sits between those two.',
        build: { kind: 'fraction', whole: 'gray_wool', part: 'red_wool', den: 10, num: 0 } },
      { say: 'A fairer game: twelve stones, four of them red.',
        prompt: 'Make a row of 12 blocks with exactly 4 of them red.',
        hint: 'Twelve in a row, four red.',
        success: 'Four out of twelve — the same as one in three. Now you can compare any two games!',
        build: { kind: 'fraction', whole: 'gray_wool', part: 'red_wool', den: 12, num: 4 } },
    ],
    reward: { coins: 160, items: [['gray_wool', 40], ['red_wool', 30]] },
  },
  {
    id: 'g7_sample', subject: 'math', standard: '7.SP.A.2', title: 'Asking Enough People',
    story: 'Pip asked three people what they thought and announced the meadow\'s opinion. '
      + 'That is not how it works. A small sample bounces about wildly; '
      + 'a bigger one settles down near the truth. Today you watch it settle.',
    steps: [
      { say: 'Three tiny samples of the same question. Look how different they came out: one, five, two.',
        prompt: 'Build three towers side by side: 1, 5 and 2 tall.',
        hint: 'One, five, two — three little samples, three different answers.',
        success: 'The same question, wildly different answers. That is what a small sample does.',
        build: { kind: 'stack', block: 'magenta_wool', heights: [1, 5, 2] } },
      { say: 'Bigger samples now. They bunch up: three, four, three.',
        prompt: 'Build three towers side by side: 3, 4 and 3 tall.',
        hint: 'Three, four, three — much closer together.',
        success: 'Much steadier. Bigger samples disagree less.',
        build: { kind: 'stack', block: 'magenta_wool', heights: [3, 4, 3] } },
      { say: 'Bigger still, and they nearly agree: four, four, three, four.',
        prompt: 'Build four towers side by side: 4, 4, 3 and 4 tall.',
        hint: 'Four, four, three, four.',
        success: 'Nearly identical. The truth is somewhere around four.',
        build: { kind: 'stack', block: 'magenta_wool', heights: [4, 4, 3, 4] } },
      { say: 'Build the answer they are all closing in on.',
        prompt: 'Build ONE tower exactly 4 tall.',
        hint: 'Four — where every big sample landed.',
        success: 'Four. Bigger samples converge on the real answer.',
        build: { kind: 'tower', block: 'magenta_wool', h: 4 } },
      { say: 'One last warning. A BIASED sample can be big and still wrong — if you only ask goats about grass.',
        prompt: 'Build five towers side by side, all exactly 7 tall.',
        hint: 'Five towers, all at the maximum. Everyone agrees — because you only asked people who already agreed.',
        success: 'Perfect agreement, and useless. WHO you ask matters as much as how many!',
        build: { kind: 'stack', block: 'magenta_wool', heights: [7, 7, 7, 7, 7] } },
    ],
    reward: { coins: 165, items: [['magenta_wool', 50]] },
  },
  {
    id: 'g7_argue', subject: 'reading', standard: 'W.7.1.B', title: 'Say It and Prove It',
    story: 'Anybody can shout an opinion. An ARGUMENT is different: a claim, then the evidence '
      + 'for it, then the reasoning that ties the two together. Miss out the middle piece '
      + 'and you have not argued anything — you have just said something loudly.',
    steps: [
      { say: 'The first piece: the thing you say is true.',
        prompt: 'Spell CLAIM.',
        hint: 'C, L, A, I, M.',
        success: 'CLAIM. "The camp should move upstream." That is a claim, and on its own it is worth nothing.',
        build: { kind: 'word', text: 'CLAIM' } },
      { say: 'The second piece: the facts you can point at.',
        prompt: 'Spell EVIDENCE.',
        hint: 'E-V-I-D-E-N-C-E. Eight letters.',
        success: 'EVIDENCE. "The water downstream is muddy." Now the claim has legs.',
        build: { kind: 'word', text: 'EVIDENCE' } },
      { say: 'The third piece, and the one everybody forgets: WHY the evidence supports the claim.',
        prompt: 'Spell REASON.',
        hint: 'R-E-A-S-O-N.',
        success: 'REASON. "Because muddy water makes people ill." That is the piece that does the work!',
        build: { kind: 'word', text: 'REASON' } },
      { say: 'A good arguer also answers the other side. That is the COUNTER argument.',
        prompt: 'Spell COUNTER.',
        hint: 'C-O-U-N-T-E-R.',
        success: 'COUNTER. "Some say moving costs too much — but illness costs more." That is how you win.',
        build: { kind: 'word', text: 'COUNTER' } },
      { say: 'The three parts of every argument you will ever write.',
        prompt: 'Spell CLAIM, REASON and PROOF — one on each row.',
        hint: 'C-L-A-I-M. R-E-A-S-O-N. P-R-O-O-F.',
        success: 'Claim, reason, proof. Use all three and people have to take you seriously!',
        build: { kind: 'words', list: ['CLAIM', 'REASON', 'PROOF'] } },
    ],
    reward: { coins: 165, items: [['letter_r', 6], ['letter_e', 6], ['letter_a', 6]] },
  },
  {
    id: 'g7_latin', subject: 'reading', standard: 'L.7.4.B', title: 'What the Romans Left',
    story: 'Latin has been dead for fifteen hundred years and is still hiding in half the words '
      + 'you use. DICT means to say. SPECT means to look. RUPT means to break. '
      + 'Learn the pieces and long words stop being strangers.',
    steps: [
      { say: 'DICT means "to say". A book of what words say is a…',
        prompt: 'Spell DICT.',
        hint: 'D, I, C, T.',
        success: 'DICT — to say. Dictionary, dictate, predict: all about saying.',
        build: { kind: 'word', text: 'DICT' } },
      { say: 'Put PRE — "before" — on the front of it.',
        prompt: 'Spell PREDICT.',
        hint: 'P-R-E and then D-I-C-T.',
        success: 'PREDICT — to say BEFORE it happens. The pieces gave you the meaning exactly.',
        build: { kind: 'word', text: 'PREDICT' } },
      { say: 'SPECT means "to look". Put IN on the front — to look in.',
        prompt: 'Spell INSPECT.',
        hint: 'I-N and then S-P-E-C-T.',
        success: 'INSPECT — to look closely at. And a SPECTATOR is one who looks!',
        build: { kind: 'word', text: 'INSPECT' } },
      { say: 'RUPT means "to break". What happens when something breaks OUT?',
        prompt: 'Spell ERUPT.',
        hint: 'E-R-U-P-T. Like a volcano.',
        success: 'ERUPT — to break out. And INTERRUPT is to break INTO somebody\'s sentence!',
        build: { kind: 'word', text: 'ERUPT' } },
      { say: 'Three roots to carry away with you.',
        prompt: 'Spell DICT, SPECT and RUPT — one on each row.',
        hint: 'D-I-C-T. S-P-E-C-T. R-U-P-T.',
        success: 'Say, look, break. Three dead words that unlock a hundred live ones!',
        build: { kind: 'words', list: ['DICT', 'SPECT', 'RUPT'] } },
    ],
    reward: { coins: 175, items: [['hearth_loaf', 5], ['travel_biscuit', 5]] },
  },
];
