// Kindergarten — ten stories, half an hour each.
//
// At this age the child cannot read the screen, so every word here is written to
// be HEARD (js/game/speech.js reads it out). That shapes the prose: short
// sentences, one instruction at a time, the number said out loud rather than
// only shown, and no clause a five-year-old has to hold in their head while
// doing something else with their hands.
export const GRADE_K = [
  // The walked one. `walk: true` puts this lesson on a MEADOW PATH instead of in
  // a single room: six stops along a trail, a different job at each, and two of
  // them barring the way until the work is done. Every step names the kind of
  // place it happens in; js/world/lessonpath.js builds it.
  {
    id: 'k_count', subject: 'math', standard: 'K.CC.B.5', title: 'The Egg Hunt',
    walk: true,
    story: 'Pip\'s hen Nutmeg got out of her coop last night and has laid her eggs all the way '
      + 'along the meadow path. Walk the path with Pip and help at every stop — mend what is broken, '
      + 'cross what is in the way, and get every last egg home to the nest before the sun goes down.',
    steps: [
      { station: { kind: 'grass', plot: false, scatter: { block: 'nest_egg', n: 7 } },
        travel: 'Off we go! Follow the gravel path until you come to the long grass.',
        say: 'Somewhere in this long grass are three of Nutmeg\'s eggs. Have a good look around — '
          + 'they are speckled brown and white, and they are hiding.',
        prompt: 'Find and pick up 3 eggs.',
        hint: 'Walk about in the grass and break the eggs you find — each one goes straight into your bag. One, two, three.',
        success: 'Three eggs found! Well hunted.',
        build: { kind: 'gather', block: 'nest_egg', n: 3 } },
      { station: { kind: 'nest' },
        travel: 'Now follow the path along to the hen house.',
        say: 'Here is Nutmeg\'s nest — and look, she has laid two MORE while we were hunting. '
          + 'Three that you found, and two more.',
        prompt: 'Put 5 eggs on the straw nest.',
        hint: 'Place them one at a time and count out loud: one, two, three, four, five.',
        success: 'Five eggs, safe on the straw. Three and two more make five!',
        build: { kind: 'count', block: 'nest_egg', n: 5 } },
      { station: { kind: 'book' },
        travel: 'Pip has a writing desk a little further on. Come and see.',
        say: 'Pip keeps a book of everything that happens in the meadow, and she wants today\'s '
          + 'sum written down properly. Three eggs, and two more, makes five.',
        prompt: 'Write it with the number blocks: 3 + 2 = 5',
        hint: 'Five blocks in a row, all touching: the 3, then the plus sign, then the 2, then the equals sign, then the 5.',
        success: 'Three plus two equals five — written down in Pip\'s own book!',
        build: { kind: 'sentence', text: '3+2=5' } },
      { station: { kind: 'gate', barrier: 'gate' },
        travel: 'On we go — the path runs down to the old gate.',
        say: 'Oh no. The gate has lost its top rail and it is stuck fast. Nothing gets through until '
          + 'it is mended, and a rail takes eight planks in a row.',
        prompt: 'Lay a row of 8 planks on the mending patch — all touching, no gaps.',
        hint: 'Eight in one straight line, each plank against the last. Count them as you lay them.',
        success: 'Eight planks and the rail is mended — the gate swings open! Walk through.',
        build: { kind: 'groups', block: 'planks', sizes: [8] } },
      { station: { kind: 'stream', barrier: 'stream' },
        travel: 'Through the gate and along to the stream.',
        say: 'The stream is far too wide to jump. We shall have to lay stepping stones — '
          + 'and it takes five to reach the other bank.',
        prompt: 'Lay a row of 5 stones on the bank.',
        hint: 'Five stones in a line, all touching. One, two, three, four, five.',
        success: 'Five stones — and away they go, straight across the water. Walk over!',
        build: { kind: 'groups', block: 'cobble', sizes: [5] } },
      { station: { kind: 'orchard' },
        travel: 'Over the stream, and on into the apple trees.',
        say: 'The wind knocked the apples down and mixed them all up. There are two baskets: '
          + 'red apples in one, green apples in the other.',
        prompt: 'Put 4 red apples on one side of the plank line and 4 green ones on the other.',
        hint: 'All the reds together on one side. All the greens together on the other. None may cross the line!',
        success: 'Sorted — reds one side, greens the other, and not one in the wrong basket.',
        build: { kind: 'sort', a: 'apple_red', b: 'apple_green', n: 4 } },
      { station: { kind: 'cottage' },
        travel: 'Nearly home. Pip\'s cottage is right at the end of the path.',
        say: 'It is getting dark. Pip has hung six lanterns and lit them, but the path needs TEN '
          + 'before bedtime. Hang the dark ones and she will light them after.',
        prompt: 'Hang unlit lanterns until there are 10 lanterns altogether.',
        hint: 'Count the lit ones: six. Now count on — seven, eight, nine, ten. That is four more.',
        success: 'Ten lanterns, and the whole path is lit! Every egg home and every job done. Thank you.',
        build: { kind: 'bond', have: { block: 'lantern_lit', n: 6 }, add: { block: 'lantern_dark', n: 4 } } },
    ],
    reward: { coins: 30, items: [['red_wool', 8], ['blue_wool', 8]] },
  },
  {
    id: 'k_more', subject: 'math', standard: 'K.CC.C.6', title: 'Who Has More?',
    story: 'Bramble the goat and Thistle the hedgehog are arguing about who has more apples. '
      + 'Neither of them can count. You are going to build their piles side by side, '
      + 'so everybody can see the answer with their eyes.',
    steps: [
      { say: 'Bramble has three apples. Thistle has two. Build their piles on the mat, one each side of the wooden line.',
        prompt: 'Build a tower 3 tall on the LEFT, and a tower 2 tall on the RIGHT.',
        hint: 'Stack blocks on top of each other. Three on the left of the wooden line, two on the right.',
        success: 'Three is MORE than two. Bramble wins this round!',
        build: { kind: 'compare', block: 'red_wool', left: 3, right: 2 } },
      { say: 'Thistle says that was not fair. He goes and gets one more, and Bramble gets two more.',
        prompt: 'Now make the LEFT tower 5 and the RIGHT tower 3.',
        hint: 'Take the old towers down first. Then stack five on the left, three on the right.',
        success: 'Five beats three. Bramble is still ahead!',
        build: { kind: 'compare', block: 'red_wool', left: 5, right: 3 } },
      { say: 'Thistle rolls his whole apple store out of his burrow. Six of them!',
        prompt: 'Make the RIGHT tower 6 and the LEFT tower 2.',
        hint: 'Six on the right side, two on the left. Now the right one is the tall one.',
        success: 'Six is more than two — this time Thistle has more!',
        build: { kind: 'compare', block: 'red_wool', left: 2, right: 6 } },
      { say: 'They decide to share instead. Every apple goes into one big tower.',
        prompt: 'Build ONE tower exactly 7 tall.',
        hint: 'Put a block down, then one on top, then another. Count as you climb: up to seven.',
        success: 'Seven, all together. Sharing is easier than arguing!',
        build: { kind: 'tower', block: 'red_wool', h: 7 } },
      { say: 'Last one. Line up four piles so we can see them all: one, then three, then two, then four.',
        prompt: 'Build four towers side by side: 1, 3, 2 and 4 tall.',
        hint: 'Four separate stacks, next to each other. One block, then three, then two, then four.',
        success: 'Now you can see which is biggest just by looking. That is what a graph does!',
        build: { kind: 'stack', block: 'red_wool', heights: [1, 3, 2, 4] } },
    ],
    reward: { coins: 30, items: [['yellow_wool', 8], ['green_wool', 8]] },
  },
  {
    id: 'k_sort', subject: 'math', standard: 'K.MD.B.3', title: 'Tidy the Toadstools',
    story: 'A storm has blown through the meadow and mixed up all of Pip\'s toadstools. '
      + 'The red ones and the yellow ones have to live on different shelves, or they argue all night. '
      + 'The wooden line down the middle of the mat is the shelf edge.',
    steps: [
      { say: 'Start small. Three red toadstools on one side of the line, three yellow on the other.',
        prompt: 'Put 3 red blocks on one side of the wooden line, and 3 yellow on the other side.',
        hint: 'All the reds together on one side. All the yellows together on the other. None may cross the line!',
        success: 'Sorted! Reds on their side, yellows on theirs.',
        build: { kind: 'sort', a: 'red_wool', b: 'yellow_wool', n: 3 } },
      { say: 'More blow in off the hedge. Four of each now.',
        prompt: 'Sort 4 red and 4 yellow, one colour each side.',
        hint: 'Keep every red on one side and every yellow on the other. Four each.',
        success: 'Four and four, no stragglers. Pip is impressed.',
        build: { kind: 'sort', a: 'red_wool', b: 'yellow_wool', n: 4 } },
      { say: 'Now the blue ones and the green ones need doing. Same shelves, new colours.',
        prompt: 'Sort 4 blue and 4 green — one colour on each side.',
        hint: 'Clear the mat first. Then blues together on one side, greens together on the other.',
        success: 'Blues and greens, all in their places!',
        build: { kind: 'sort', a: 'blue_wool', b: 'green_wool', n: 4 } },
      { say: 'Pip wants to know how many blue ones there are altogether. Put them all in one place and count.',
        prompt: 'Put exactly 6 blue blocks on the mat.',
        hint: 'Count out loud as you place them: one, two, three, four, five, six.',
        success: 'Six blues. Counting after sorting — that is proper tidying!',
        build: { kind: 'count', block: 'blue_wool', n: 6 } },
      { say: 'Last job. The big shelf takes five of each colour.',
        prompt: 'Sort 5 red and 5 blue, one colour on each side of the line.',
        hint: 'Five reds all on one side. Five blues all on the other. Check nothing has crept across!',
        success: 'The meadow is tidy and nobody is arguing. Thank you!',
        build: { kind: 'sort', a: 'red_wool', b: 'blue_wool', n: 5 } },
    ],
    reward: { coins: 35, items: [['orange_wool', 8], ['purple_wool', 8]] },
  },
  {
    id: 'k_shapes', subject: 'math', standard: 'K.G.B.5', title: 'A Window for Pip',
    story: 'Pip is building a little house in the hollow of an oak, and she needs a window. '
      + 'Windows are shapes. Today you will build a square, a bigger square, '
      + 'a window frame with the glass missing, and a long thin rectangle for the letter box.',
    steps: [
      { say: 'A square first. Two blocks across, and two blocks back.',
        prompt: 'Build a square 2 across and 2 back.',
        hint: 'Two blocks in a row. Then two more right behind them.',
        success: 'A square! Every side the same. Four blocks altogether.',
        build: { kind: 'array', block: 'yellow_wool', rows: 2, cols: 2 } },
      { say: 'Too small for Pip to see out of. Make it bigger — three across, three back.',
        prompt: 'Build a square 3 across and 3 back.',
        hint: 'A row of three. Then another row of three behind it. Then one more.',
        success: 'Three by three — a bigger square, and nine blocks!',
        build: { kind: 'array', block: 'yellow_wool', rows: 3, cols: 3 } },
      { say: 'Now take the middle out, so she can actually see through it. Just the edges left.',
        prompt: 'Build the OUTLINE of a 3 by 3 square — edges only, nothing in the middle.',
        hint: 'Build the square, then break the one block in the very middle.',
        success: 'A window frame! The hole in the middle is where the light comes in.',
        build: { kind: 'frame', block: 'yellow_wool', w: 3, d: 3 } },
      { say: 'The letter box goes under the window. Long and thin: four across, two back.',
        prompt: 'Build a rectangle 4 across and 2 back.',
        hint: 'A row of four. Then another row of four behind it.',
        success: 'A rectangle. Longer than it is deep — perfect for letters.',
        build: { kind: 'array', block: 'brown_wool', rows: 2, cols: 4 } },
      { say: 'Last of all, shutters. One each side of the wooden line, exactly matching.',
        prompt: 'Put 4 blocks on one side of the line and 4 matching ones the same distance away on the other.',
        hint: 'However far a block is from the wooden line, put one just as far on the other side.',
        success: 'Both shutters match. Pip\'s house looks beautiful!',
        build: { kind: 'mirror', block: 'brown_wool', pairs: 4 } },
    ],
    reward: { coins: 35, items: [['brown_wool', 10], ['white_wool', 10]] },
  },
  {
    id: 'k_add', subject: 'math', standard: 'K.OA.A.2', title: 'Berries in the Basket',
    story: 'It is berry day. Pip picks some, you pick some, and every time you meet at the basket '
      + 'you have to work out how many there are ALTOGETHER. That is what adding means: putting together.',
    steps: [
      { say: 'You pick two berries. Pip picks two more. Put them all in the basket.',
        prompt: 'Put 4 red blocks on the mat.',
        hint: 'Two, and two more. Count them all: one, two, three, four.',
        success: 'Two and two make four!',
        build: { kind: 'count', block: 'red_wool', n: 4 } },
      { say: 'Round the next bush, you find three and Pip finds two.',
        prompt: 'Clear the mat, then put 5 red blocks on it.',
        hint: 'Three first. Then two more next to them. Count them all together.',
        success: 'Three and two make five!',
        build: { kind: 'count', block: 'red_wool', n: 5 } },
      { say: 'Let us see the two handfuls separately before we mix them. Three in one pile, two in the other.',
        prompt: 'Make a pile of 3 and a pile of 2, with a gap between them.',
        hint: 'Three in a row. Leave an empty square. Then two more.',
        success: 'Three here and two there — and still five altogether!',
        build: { kind: 'groups', block: 'red_wool', sizes: [3, 2] } },
      { say: 'Now a bigger haul. Four from the low branches, three from the high ones.',
        prompt: 'Put 7 red blocks on the mat.',
        hint: 'Four, then keep counting on: five, six, seven.',
        success: 'Four and three make seven. You did not start from one — you counted ON!',
        build: { kind: 'count', block: 'red_wool', n: 7 } },
      { say: 'The basket is nearly full. Six from you, three from Pip.',
        prompt: 'Put 9 red blocks on the mat.',
        hint: 'Six, then count on: seven, eight, nine.',
        success: 'Nine berries! That is enough for a pie.',
        build: { kind: 'count', block: 'red_wool', n: 9 } },
    ],
    reward: { coins: 40, items: [['hearth_loaf', 2], ['pink_wool', 8]] },
  },
  {
    id: 'k_take', subject: 'math', standard: 'K.OA.A.2', title: 'The Hungry Goat',
    story: 'Bramble the goat has got into the vegetable patch. Every time you plant something, '
      + 'he eats some of it. Taking away is the opposite of adding — and today you will do the taking, '
      + 'by breaking the blocks Bramble eats.',
    steps: [
      { say: 'Plant five cabbages. Bramble eats two of them. Build all five first — then break the two he ate.',
        prompt: 'Place 5 green blocks, then break 2 of them.',
        hint: 'All five first! Count them. Then break one, and another. Three should be left.',
        success: 'Five take away two leaves three. That is subtraction!',
        build: { kind: 'subtract', block: 'green_wool', from: 5, take: 2 } },
      { say: 'You plant six more. Bramble comes back and eats three.',
        prompt: 'Place 6 green blocks, then break 3 of them.',
        hint: 'Six first, all in a row. Then break three of them away.',
        success: 'Six take away three leaves three. Half of them, gone!',
        build: { kind: 'subtract', block: 'green_wool', from: 6, take: 3 } },
      { say: 'You put up a fence. Bramble jumps it. Eight cabbages, four eaten.',
        prompt: 'Place 8 green blocks, then break 4 of them.',
        hint: 'Build all eight before you break any. Then break four.',
        success: 'Eight take away four leaves four. Bramble is getting full!',
        build: { kind: 'subtract', block: 'green_wool', from: 8, take: 4 } },
      { say: 'Bramble is asleep in the sun. Quick — count what is left of the whole patch.',
        prompt: 'Put exactly 4 green blocks on the mat.',
        hint: 'Four. One, two, three, four — then stop.',
        success: 'Four cabbages saved!',
        build: { kind: 'count', block: 'green_wool', n: 4 } },
      { say: 'One last raid. Ten cabbages, and he eats five.',
        prompt: 'Place 10 green blocks, then break 5 of them.',
        hint: 'Ten first — a whole row. Then break five away.',
        success: 'Ten take away five leaves five. You worked it all out yourself!',
        build: { kind: 'subtract', block: 'green_wool', from: 10, take: 5 } },
    ],
    reward: { coins: 40, items: [['green_wool', 12], ['travel_biscuit', 2]] },
  },
  {
    id: 'k_ten', subject: 'math', standard: 'K.OA.A.4', title: 'Ten Little Lanterns',
    story: 'The meadow path needs TEN lanterns lit before dark, no more and no fewer. '
      + 'Pip has already lit some. Every time, your job is to work out how many are still missing '
      + 'and light exactly that many. Pairs that make ten are worth knowing by heart.',
    steps: [
      { say: 'Look — Pip has lit six already. They are on the mat. How many more to make ten?',
        prompt: 'Add BLUE blocks until there are 10 altogether.',
        hint: 'Count the ones already there: six. Now count on — seven, eight, nine, ten — one blue for each.',
        success: 'Six and four make ten! Four was the missing piece.',
        build: { kind: 'bond', have: { block: 'yellow_wool', n: 6 }, add: { block: 'blue_wool', n: 4 } } },
      { say: 'The wind blows some out. Now there are seven lit.',
        prompt: 'Add BLUE blocks until there are 10 altogether.',
        hint: 'Seven… eight, nine, ten. That is three more.',
        success: 'Seven and three make ten!',
        build: { kind: 'bond', have: { block: 'yellow_wool', n: 7 }, add: { block: 'blue_wool', n: 3 } } },
      { say: 'Pip has been busy. Eight are lit now.',
        prompt: 'Add BLUE blocks until there are 10 altogether.',
        hint: 'Eight… nine, ten. Only two more!',
        success: 'Eight and two make ten. That one was quick!',
        build: { kind: 'bond', have: { block: 'yellow_wool', n: 8 }, add: { block: 'blue_wool', n: 2 } } },
      { say: 'A big gust. Half of them are out — only five left lit.',
        prompt: 'Add BLUE blocks until there are 10 altogether.',
        hint: 'Five and how many more? Count on: six, seven, eight, nine, ten.',
        success: 'Five and five make ten. The easiest pair of all!',
        build: { kind: 'bond', have: { block: 'yellow_wool', n: 5 }, add: { block: 'blue_wool', n: 5 } } },
      { say: 'The path is lit. Build the whole row of ten yourself, so Pip can count them from her window.',
        prompt: 'Put 10 yellow blocks on the mat.',
        hint: 'Ten in a row. Count every one out loud.',
        success: 'Ten lanterns, all lit. The meadow is safe tonight!',
        build: { kind: 'count', block: 'yellow_wool', n: 10 } },
    ],
    reward: { coins: 45, items: [['yellow_wool', 12], ['blue_wool', 12]] },
  },
  {
    id: 'k_pattern', subject: 'math', standard: '1.OA.C.5', title: 'The Ribbon Path',
    story: 'Every summer the meadow lays a ribbon path to the fair. The ribbons go in an order '
      + 'and the order NEVER changes — that is what makes it a pattern. '
      + 'If you learn the order, you always know what comes next.',
    steps: [
      { say: 'The simplest ribbon: red, blue, red, blue. Lay six in a row.',
        prompt: 'Make a row: red, blue, red, blue, red, blue.',
        hint: 'Start with red. Then blue right next to it. The colours take turns!',
        success: 'Red, blue, red, blue. Now you know what comes next without looking!',
        build: { kind: 'pattern', seq: ['red_wool', 'blue_wool'], reps: 3 } },
      { say: 'Down by the stream they use a longer one: two reds, then a blue.',
        prompt: 'Make a row: red, red, blue — three times over.',
        hint: 'Red, red, blue. Then red, red, blue again. And once more.',
        success: 'Red red blue, red red blue, red red blue. A longer pattern — but still a pattern!',
        build: { kind: 'pattern', seq: ['red_wool', 'red_wool', 'blue_wool'], reps: 3 } },
      { say: 'The fair gate uses three colours. Yellow, green, yellow, green.',
        prompt: 'Make a row: yellow, green — four times over.',
        hint: 'Yellow then green, over and over, until you have eight blocks.',
        success: 'Eight blocks, and never two the same next to each other!',
        build: { kind: 'pattern', seq: ['yellow_wool', 'green_wool'], reps: 4 } },
      { say: 'Now a pattern that GROWS. One block, then two, then three, then four.',
        prompt: 'Build four towers next to each other: 1, 2, 3 and 4 tall.',
        hint: 'One block. Then a stack of two beside it. Then three. Then four.',
        success: 'Each one is one taller than the last. That is a growing pattern — like stairs!',
        build: { kind: 'stack', block: 'purple_wool', heights: [1, 2, 3, 4] } },
      { say: 'Last ribbon, the fanciest one: red, yellow, blue, again and again.',
        prompt: 'Make a row: red, yellow, blue — three times over.',
        hint: 'Red, yellow, blue. Then start again: red, yellow, blue. And once more.',
        success: 'Nine blocks in a perfect three-colour pattern. The path to the fair is finished!',
        build: { kind: 'pattern', seq: ['red_wool', 'yellow_wool', 'blue_wool'], reps: 3 } },
    ],
    reward: { coins: 45, items: [['purple_wool', 12], ['light_blue_wool', 12]] },
  },
  {
    id: 'k_letters', subject: 'reading', standard: 'RF.K.1.D', title: 'Pip\'s Alphabet Gate',
    story: 'The gate to the reading garden only opens for someone who knows their letters. '
      + 'It asks for them in order — and the alphabet is always, always in the same order, '
      + 'which is why the song helps so much. Sing it while you build.',
    steps: [
      { say: 'The first three letters. Sing them: A, B, C.',
        prompt: 'Put the letters A, B and C in a row.',
        hint: 'Find the letter A block and put it down. Then B right next to it. Then C. No gaps!',
        success: 'A, B, C — the very beginning of the alphabet!',
        build: { kind: 'word', text: 'ABC' } },
      { say: 'Keep singing. What comes after C? D, E, F.',
        prompt: 'Put the letters D, E and F in a row.',
        hint: 'Clear the mat. Then D, then E, then F, all touching.',
        success: 'D, E, F. The song is helping!',
        build: { kind: 'word', text: 'DEF' } },
      { say: 'Now all six together, in one long row.',
        prompt: 'Spell out A B C D E F in a row.',
        hint: 'Start with A on the left and work right: A, B, C, D, E, F.',
        success: 'Six letters, all in the right order. The gate is creaking open!',
        build: { kind: 'word', text: 'ABCDEF' } },
      { say: 'The gate wants two more: G and H. Put the whole run together.',
        prompt: 'Spell out A B C D E F G H in a row.',
        hint: 'Everything you did before, and then G and H on the end.',
        success: 'All the way to H. That is a third of the alphabet!',
        build: { kind: 'word', text: 'ABCDEFGH' } },
      { say: 'Last test. Five special letters live in nearly every word. They are called the VOWELS.',
        prompt: 'Put the vowels in a row: A E I O U.',
        hint: 'Sing them: A, E, I, O, U. Every word needs at least one of these.',
        success: 'A E I O U — the five vowels. The reading garden is open to you!',
        build: { kind: 'word', text: 'AEIOU' } },
    ],
    reward: { coins: 50, items: [['letter_c', 4], ['letter_a', 4], ['letter_t', 4]] },
  },
  {
    id: 'k_words', subject: 'reading', standard: 'RF.K.3.A', title: 'Three Little Words',
    story: 'Inside the reading garden, everything has a name written on a little wooden sign — '
      + 'but a jackdaw has stolen all the letters. Say each word slowly, listen for the sounds, '
      + 'and build the sign back. A word is just sounds, in order, written down.',
    steps: [
      { say: 'The first sign belongs to the garden cat. Say it slowly: c… a… t.',
        prompt: 'Spell CAT.',
        hint: 'Three sounds, three letters: C, then A, then T, all in a row.',
        success: 'C-A-T spells CAT. You have written a word!',
        build: { kind: 'word', text: 'CAT' } },
      { say: 'Next sign: the dog by the gate. Say it: d… o… g.',
        prompt: 'Spell DOG.',
        hint: 'D, then O, then G. Listen for the sound in the middle — that is the O.',
        success: 'D-O-G spells DOG. Two words now!',
        build: { kind: 'word', text: 'DOG' } },
      { say: 'This one is high above the garden and it is very bright. S… u… n.',
        prompt: 'Spell SUN.',
        hint: 'S, U, N. The U is the vowel in the middle.',
        success: 'S-U-N spells SUN!',
        build: { kind: 'word', text: 'SUN' } },
      { say: 'There is a pig asleep by the wall. P… i… g.',
        prompt: 'Spell PIG.',
        hint: 'P, I, G. Say it slowly and you can hear all three.',
        success: 'P-I-G spells PIG. Four signs mended!',
        build: { kind: 'word', text: 'PIG' } },
      { say: 'The last three signs all sound alike at the end. Listen: CAT, HAT, BAT. Those are RHYMES.',
        prompt: 'Spell CAT, HAT and BAT — one on each row.',
        hint: 'They all end A-T. Only the first letter changes: C, then H, then B.',
        success: 'CAT, HAT, BAT — they rhyme because they end the same way. The garden is yours!',
        build: { kind: 'words', list: ['CAT', 'HAT', 'BAT'] } },
    ],
    reward: { coins: 60, items: [['hearth_loaf', 3], ['travel_biscuit', 3]] },
  },
];
