// Grade 4 — factors and multiples, prime and composite, the area model that
// makes two-digit multiplication possible in your head, adding fractions with
// the same denominator, tenths, symmetry, line plots, and word roots.
export const GRADE_4 = [
  {
    id: 'g4_factors', subject: 'math', standard: '4.OA.B.4', title: 'The Tile Merchant',
    story: 'A merchant has exactly twelve tiles and wants to lay them in a perfect rectangle. '
      + 'There is more than one way — and the pairs of numbers that work are called the FACTORS '
      + 'of twelve. Find them all and you know the number properly.',
    steps: [
      { say: 'The laziest rectangle: one row of twelve.',
        prompt: 'Build 1 row with 12 blocks in it.',
        hint: 'All twelve in a single line.',
        success: 'One times twelve. That is the first factor pair: 1 and 12.',
        build: { kind: 'array', block: 'purple_wool', rows: 1, cols: 12 } },
      { say: 'Now two rows. How many in each?',
        prompt: 'Build 2 rows with 6 blocks in each row.',
        hint: 'Twelve shared between two rows is six each.',
        success: 'Two times six. The second pair: 2 and 6.',
        build: { kind: 'array', block: 'purple_wool', rows: 2, cols: 6 } },
      { say: 'Three rows next.',
        prompt: 'Build 3 rows with 4 blocks in each row.',
        hint: 'Twelve shared between three rows is four each.',
        success: 'Three times four. The third pair: 3 and 4.',
        build: { kind: 'array', block: 'purple_wool', rows: 3, cols: 4 } },
      { say: 'Four rows — and notice this is the last new one.',
        prompt: 'Build 4 rows with 3 blocks in each row.',
        hint: 'Four rows of three. It is the three-by-four turned on its side.',
        success: 'Four times three — the same pair the other way round. Once they start repeating, you have them all!',
        build: { kind: 'array', block: 'purple_wool', rows: 4, cols: 3 } },
      { say: 'Try a different number. Eighteen: how about three rows?',
        prompt: 'Build 3 rows with 6 blocks in each row.',
        hint: 'Eighteen shared between three rows is six each.',
        success: 'Three and six are factors of eighteen. Twelve has six factors, eighteen has six too!',
        build: { kind: 'array', block: 'purple_wool', rows: 3, cols: 6 } },
    ],
    reward: { coins: 90, items: [['purple_wool', 40], ['magenta_wool', 24]] },
  },
  {
    id: 'g4_prime', subject: 'math', standard: '4.OA.B.4', title: 'The Stubborn Numbers',
    story: 'Some numbers refuse to make a rectangle at all — the only way to lay them out '
      + 'is one long line. Those are the PRIME numbers, and they are the building blocks '
      + 'of every other number there is.',
    steps: [
      { say: 'Try to make seven into a rectangle. There is only one way.',
        prompt: 'Build 1 row with 7 blocks in it.',
        hint: 'Seven in a single line. Try two rows — it will not come out even.',
        success: 'Seven is PRIME. One row of seven, and nothing else works.',
        build: { kind: 'array', block: 'red_wool', rows: 1, cols: 7 } },
      { say: 'Now eight. That one bends.',
        prompt: 'Build 2 rows with 4 blocks in each row.',
        hint: 'Eight shared between two rows is four each.',
        success: 'Eight is COMPOSITE — it can be made from smaller pieces.',
        build: { kind: 'array', block: 'green_wool', rows: 2, cols: 4 } },
      { say: 'Eleven. Try it.',
        prompt: 'Build 1 row with 11 blocks in it.',
        hint: 'Eleven in a line. Two rows? Not even. Three? Not even.',
        success: 'Eleven is prime. Stubborn as they come!',
        build: { kind: 'array', block: 'red_wool', rows: 1, cols: 11 } },
      { say: 'Nine bends, but only one way.',
        prompt: 'Build 3 rows with 3 blocks in each row.',
        hint: 'Three rows of three — a perfect square.',
        success: 'Nine is composite AND square. Three times three.',
        build: { kind: 'array', block: 'green_wool', rows: 3, cols: 3 } },
      { say: 'Last one: thirteen. Prime or composite?',
        prompt: 'Build 1 row with 13 blocks in it.',
        hint: 'Thirteen fills the whole mat in one line. Nothing else divides it.',
        success: 'Thirteen is prime. Two, three, five, seven, eleven, thirteen — you have met six of them now!',
        build: { kind: 'array', block: 'red_wool', rows: 1, cols: 13 } },
    ],
    reward: { coins: 90, items: [['red_wool', 30], ['green_wool', 30]] },
  },
  {
    id: 'g4_areamodel', subject: 'math', standard: '4.NBT.B.5', title: 'Breaking Up the Big Sum',
    story: 'Four times thirteen sounds hard. But thirteen is just ten and three — '
      + 'and four times ten is easy, and four times three is easy. '
      + 'Break the hard sum into two easy ones and add them. That is the whole trick.',
    steps: [
      { say: 'The easy half first. Four rows of ten.',
        prompt: 'Build 4 rows with 10 blocks in each row.',
        hint: 'Ten in a row, four rows of them.',
        success: 'Four tens is forty. Half the sum, done in your head.',
        build: { kind: 'array', block: 'blue_wool', rows: 4, cols: 10 } },
      { say: 'Now the little half. Four rows of three.',
        prompt: 'Build 4 rows with 3 blocks in each row.',
        hint: 'Three in a row, four times.',
        success: 'Four threes is twelve. Forty and twelve is FIFTY-TWO — that is four times thirteen!',
        build: { kind: 'array', block: 'blue_wool', rows: 4, cols: 3 } },
      { say: 'Try another. Three times twelve. Start with three tens.',
        prompt: 'Build 3 rows with 10 blocks in each row.',
        hint: 'Ten in a row, three rows.',
        success: 'Thirty. Now the leftover twos.',
        build: { kind: 'array', block: 'orange_wool', rows: 3, cols: 10 } },
      { say: 'And three rows of two.',
        prompt: 'Build 3 rows with 2 blocks in each row.',
        hint: 'Two in a row, three rows of them.',
        success: 'Six. Thirty and six is THIRTY-SIX — three times twelve!',
        build: { kind: 'array', block: 'orange_wool', rows: 3, cols: 2 } },
      { say: 'One more, all in one go. Five times eleven — five tens and five ones.',
        prompt: 'Build 5 rows with 11 blocks in each row.',
        hint: 'Eleven in a row, five rows. Fifty from the tens, five from the ones.',
        success: 'Fifty-five. You can multiply two-digit numbers now — just break them up!',
        build: { kind: 'array', block: 'orange_wool', rows: 5, cols: 11 } },
    ],
    reward: { coins: 95, items: [['blue_wool', 40], ['orange_wool', 40]] },
  },
  {
    id: 'g4_fracadd', subject: 'math', standard: '4.NF.B.3', title: 'Adding Up the Slices',
    story: 'The pie is cut into eight and everybody takes a few slices. '
      + 'Adding fractions with the same bottom number is easy: count the slices, '
      + 'and leave the bottom number alone. It is still a pie cut into eight.',
    steps: [
      { say: 'You take one slice out of eight.',
        prompt: 'Make a row of 8 blocks with exactly 1 of them pink.',
        hint: 'Eight in a row, one pink.',
        success: 'One eighth.',
        build: { kind: 'fraction', whole: 'white_wool', part: 'pink_wool', den: 8, num: 1 } },
      { say: 'Pip takes two more. One slice and two slices.',
        prompt: 'Make a row of 8 blocks with exactly 3 of them pink.',
        hint: 'One plus two is three. Three pink out of eight.',
        success: 'One eighth and two eighths is THREE eighths. The bottom number never moved!',
        build: { kind: 'fraction', whole: 'white_wool', part: 'pink_wool', den: 8, num: 3 } },
      { say: 'Rowan takes three more.',
        prompt: 'Make a row of 8 blocks with exactly 6 of them pink.',
        hint: 'Three and three is six.',
        success: 'Six eighths gone. Only two slices left!',
        build: { kind: 'fraction', whole: 'white_wool', part: 'pink_wool', den: 8, num: 6 } },
      { say: 'And the last two slices go too.',
        prompt: 'Make a row of 8 blocks with all 8 of them pink.',
        hint: 'Six and two is eight — the whole pie.',
        success: 'Eight eighths is ONE WHOLE PIE. When the numbers match, you have all of it.',
        build: { kind: 'fraction', whole: 'white_wool', part: 'pink_wool', den: 8, num: 8 } },
      { say: 'A different pie, cut into twelve. Take five, then two more.',
        prompt: 'Make a row of 12 blocks with exactly 7 of them pink.',
        hint: 'Five and two is seven. Twelve in the row, seven of them pink.',
        success: 'Five twelfths and two twelfths is seven twelfths. Same rule, bigger pie!',
        build: { kind: 'fraction', whole: 'white_wool', part: 'pink_wool', den: 12, num: 7 } },
    ],
    reward: { coins: 95, items: [['pink_wool', 30], ['white_wool', 40]] },
  },
  {
    id: 'g4_decimal', subject: 'math', standard: '4.NF.C.6', title: 'Tenths of a Rod',
    story: 'The carpenter\'s rod is marked into ten equal parts, and every measurement in the '
      + 'workshop is written with a dot: nought point three means three parts out of ten. '
      + 'A decimal is just a fraction with a tidier way of writing it down.',
    steps: [
      { say: 'Mark three tenths of the rod.',
        prompt: 'Make a row of 10 blocks with exactly 3 of them cyan.',
        hint: 'Ten in a row — the whole rod. Three of them cyan.',
        success: 'Three tenths. The carpenter writes that nought point three.',
        build: { kind: 'fraction', whole: 'white_wool', part: 'cyan_wool', den: 10, num: 3 } },
      { say: 'Now seven tenths.',
        prompt: 'Make a row of 10 blocks with exactly 7 of them cyan.',
        hint: 'Ten in the row, seven cyan.',
        success: 'Seven tenths — nought point seven. More than half the rod.',
        build: { kind: 'fraction', whole: 'white_wool', part: 'cyan_wool', den: 10, num: 7 } },
      { say: 'Half the rod. How many tenths is that?',
        prompt: 'Make a row of 10 blocks with exactly 5 of them cyan.',
        hint: 'Half of ten is five.',
        success: 'Five tenths IS a half — nought point five. Two ways of writing the same length!',
        build: { kind: 'fraction', whole: 'white_wool', part: 'cyan_wool', den: 10, num: 5 } },
      { say: 'The smallest mark on the rod: one tenth.',
        prompt: 'Make a row of 10 blocks with exactly 1 of them cyan.',
        hint: 'Just one of the ten.',
        success: 'One tenth — nought point one. The smallest step on the rod.',
        build: { kind: 'fraction', whole: 'white_wool', part: 'cyan_wool', den: 10, num: 1 } },
      { say: 'Last cut: nine tenths. Nearly the whole rod.',
        prompt: 'Make a row of 10 blocks with exactly 9 of them cyan.',
        hint: 'Nine cyan, one white.',
        success: 'Nine tenths — nought point nine. One more tenth and it would be a whole one!',
        build: { kind: 'fraction', whole: 'white_wool', part: 'cyan_wool', den: 10, num: 9 } },
    ],
    reward: { coins: 95, items: [['cyan_wool', 30], ['white_wool', 30]] },
  },
  {
    id: 'g4_symmetry', subject: 'math', standard: '4.G.A.3', title: 'The Butterfly\'s Wing',
    story: 'A butterfly landed on the plank line and Pip only sketched one wing before it flew off. '
      + 'You can finish the drawing without ever having seen the other side — because a butterfly '
      + 'is SYMMETRICAL. Whatever is a certain distance from the line, the other side matches.',
    steps: [
      { say: 'Start simple. Four blocks each side of the line, matching.',
        prompt: 'Put 4 blocks on one side of the line and 4 matching ones the same distance away on the other side.',
        hint: 'However far a block is from the wooden line, put one just as far on the other side.',
        success: 'Both wings match. That is a line of symmetry!',
        build: { kind: 'mirror', block: 'yellow_wool', pairs: 4 } },
      { say: 'A bigger wing. Six pairs.',
        prompt: 'Make 6 matching pairs across the line.',
        hint: 'Work outwards from the line: first block each side, then the next, and so on.',
        success: 'Six pairs, perfectly balanced.',
        build: { kind: 'mirror', block: 'yellow_wool', pairs: 6 } },
      { say: 'Now use two rows, so the wing has some depth. Eight pairs.',
        prompt: 'Make 8 matching pairs across the line.',
        hint: 'Fill one row of pairs, then start the next row — always matching both sides.',
        success: 'Eight pairs across two rows. The wing is taking shape!',
        build: { kind: 'mirror', block: 'yellow_wool', pairs: 8 } },
      { say: 'A wing tip in a different colour. Ten pairs this time.',
        prompt: 'Make 10 matching pairs across the line.',
        hint: 'Ten on each side, each one mirrored exactly.',
        success: 'Ten pairs. Twenty blocks, and not one of them out of place.',
        build: { kind: 'mirror', block: 'orange_wool', pairs: 10 } },
      { say: 'The finished butterfly: twelve pairs, both wings complete.',
        prompt: 'Make 12 matching pairs across the line.',
        hint: 'Keep the two sides identical the whole way. Check each pair as you place it.',
        success: 'A whole butterfly, drawn from one wing and a rule. Pip is amazed!',
        build: { kind: 'mirror', block: 'orange_wool', pairs: 12 } },
    ],
    reward: { coins: 100, items: [['yellow_wool', 30], ['orange_wool', 30]] },
  },
  {
    id: 'g4_perimarea', subject: 'math', standard: '4.MD.A.3', title: 'Same Fence, Different Field',
    story: 'Two farmers have exactly the same length of fence and are arguing about who has '
      + 'more grass. They both do have the same fence — but not the same field. '
      + 'Perimeter and area are different questions, and today you settle the argument.',
    steps: [
      { say: 'The first farmer makes a long thin field: nine across, two back. Fence only.',
        prompt: 'Build the OUTLINE of a rectangle 9 across and 2 back.',
        hint: 'Nine along the front, nine along the back — with two deep there is no middle.',
        success: 'Eighteen posts of fence for the thin field.',
        build: { kind: 'frame', block: 'brown_wool', w: 9, d: 2 } },
      { say: 'Now fill it in — that is the grass.',
        prompt: 'Build 2 rows with 9 blocks in each row.',
        hint: 'Two rows of nine, filled solid.',
        success: 'Eighteen squares of grass. Fence eighteen, grass eighteen.',
        build: { kind: 'array', block: 'green_wool', rows: 2, cols: 9 } },
      { say: 'The second farmer uses the same fence but makes it fatter: six across, three back.',
        prompt: 'Build the OUTLINE of a rectangle 6 across and 3 back.',
        hint: 'Six along the top and bottom, and one square each side in the middle row.',
        success: 'Fourteen posts… hold on, that is LESS fence than the other field.',
        build: { kind: 'frame', block: 'brown_wool', w: 6, d: 3 } },
      { say: 'Fill that one in too and count the grass.',
        prompt: 'Build 3 rows with 6 blocks in each row.',
        hint: 'Three rows of six, solid.',
        success: 'Eighteen squares of grass from only fourteen posts. The fat field is the better deal!',
        build: { kind: 'array', block: 'green_wool', rows: 3, cols: 6 } },
      { say: 'The fattest field of all with that much grass: a square. Look what happens.',
        prompt: 'Build the OUTLINE of a rectangle 5 across and 4 back.',
        hint: 'Five along the top and bottom, four deep.',
        success: 'Fourteen posts round twenty squares of grass. The closer to a square, the more grass per post!',
        build: { kind: 'frame', block: 'brown_wool', w: 5, d: 4 } },
    ],
    reward: { coins: 100, items: [['brown_wool', 30], ['green_wool', 30]] },
  },
  {
    id: 'g4_lineplot', subject: 'math', standard: '4.MD.B.4', title: 'The Rainfall Record',
    story: 'The meadow keeps a rain barrel and marks the level every week. '
      + 'A page of numbers tells you nothing. Stand them up as bars and the wet weeks, '
      + 'the dry weeks, the highest and the lowest all jump straight out at you.',
    steps: [
      { say: 'The first three weeks: two, five and three.',
        prompt: 'Build three towers side by side: 2, 5 and 3 tall.',
        hint: 'Two blocks, then five, then three.',
        success: 'Week two was the wettest so far.',
        build: { kind: 'stack', block: 'blue_wool', heights: [2, 5, 3] } },
      { say: 'Weeks four and five: six and one.',
        prompt: 'Build five towers side by side: 2, 5, 3, 6 and 1 tall.',
        hint: 'Add a six and a one on the end of the ones you had.',
        success: 'Week four is the new record, and week five was almost dry.',
        build: { kind: 'stack', block: 'blue_wool', heights: [2, 5, 3, 6, 1] } },
      { say: 'What is the difference between the wettest week and the driest?',
        prompt: 'Build ONE tower exactly 5 tall.',
        hint: 'Six take away one is five. That difference is called the RANGE.',
        success: 'The range is five. That is how spread out the numbers are!',
        build: { kind: 'tower', block: 'blue_wool', h: 5 } },
      { say: 'Sort the five weeks smallest to biggest, so we can find the middle one.',
        prompt: 'Build five towers side by side: 1, 2, 3, 5 and 6 tall.',
        hint: 'One, two, three, five, six — in order.',
        success: 'In order. The one in the very middle is three — that is the MEDIAN.',
        build: { kind: 'stack', block: 'blue_wool', heights: [1, 2, 3, 5, 6] } },
      { say: 'Build just the median on its own so Pip can write it in the book.',
        prompt: 'Build ONE tower exactly 3 tall.',
        hint: 'The middle value when they are in order: three.',
        success: 'Median three, range five. That is a proper record!',
        build: { kind: 'tower', block: 'blue_wool', h: 3 } },
    ],
    reward: { coins: 100, items: [['blue_wool', 30], ['light_blue_wool', 24]] },
  },
  {
    id: 'g4_roots', subject: 'reading', standard: 'L.4.4.B', title: 'The Root of the Matter',
    story: 'Long words are not new words — they are old words with pieces bolted on the front '
      + 'and back. Find the ROOT in the middle and you can work out a word you have never seen. '
      + 'PORT means to carry. Everything else is decoration.',
    steps: [
      { say: 'Here is the root, on its own. P, O, R, T. It means "carry".',
        prompt: 'Spell PORT.',
        hint: 'Four letters: P, O, R, T.',
        success: 'PORT — to carry. A port is where things get carried on and off ships!',
        build: { kind: 'word', text: 'PORT' } },
      { say: 'Bolt RE on the front. RE means "back" or "again". Carry it back…',
        prompt: 'Spell REPORT.',
        hint: 'R-E and then P-O-R-T.',
        success: 'REPORT — to carry information BACK to somebody. The pieces tell you the meaning!',
        build: { kind: 'word', text: 'REPORT' } },
      { say: 'Now EX on the front. EX means "out".',
        prompt: 'Spell EXPORT.',
        hint: 'E-X and then P-O-R-T.',
        success: 'EXPORT — to carry OUT of the country. You just worked out a word from its pieces.',
        build: { kind: 'word', text: 'EXPORT' } },
      { say: 'And IM means "in".',
        prompt: 'Spell IMPORT.',
        hint: 'I-M and then P-O-R-T.',
        success: 'IMPORT — to carry IN. Out and in, from two little letters!',
        build: { kind: 'word', text: 'IMPORT' } },
      { say: 'One more root: TRACT means "pull". Try three words built from pieces.',
        prompt: 'Spell PORT, TRACT and TRACTOR — one on each row.',
        hint: 'P-O-R-T. T-R-A-C-T. Then TRACT with O-R on the end.',
        success: 'A tractor is a thing that PULLS. Roots turn hard words into easy ones!',
        build: { kind: 'words', list: ['PORT', 'TRACT', 'TRACTOR'] } },
    ],
    reward: { coins: 100, items: [['letter_p', 4], ['letter_o', 4], ['letter_r', 6], ['letter_t', 6]] },
  },
  {
    id: 'g4_homophone', subject: 'reading', standard: 'L.4.1.G', title: 'Sound the Same, Mean Different',
    story: 'Two words can sound exactly alike and mean completely different things. '
      + 'Your ears cannot tell them apart — only the spelling can. '
      + 'Get them the wrong way round and a sentence turns into nonsense.',
    steps: [
      { say: 'The first one belongs to somebody. It is THEIR hat. T-H-E-I-R.',
        prompt: 'Spell THEIR.',
        hint: 'T, H, E, I, R. The one with the I in it means "belonging to them".',
        success: 'THEIR — belonging to them. Remember the I: "their" has heir in it, and an heir owns things.',
        build: { kind: 'word', text: 'THEIR' } },
      { say: 'This one is a place. Over THERE. T-H-E-R-E.',
        prompt: 'Spell THERE.',
        hint: 'T, H, E, R, E. It has HERE hiding inside it — and here is a place!',
        success: 'THERE — a place. HERE is inside it. That is how you will always remember.',
        build: { kind: 'word', text: 'THERE' } },
      { say: 'Now a pair about writing. What you do with a pen: W, R, I, T, E.',
        prompt: 'Spell WRITE.',
        hint: 'The W at the start is silent.',
        success: 'WRITE — with a silent W.',
        build: { kind: 'word', text: 'WRITE' } },
      { say: 'And the one that means correct — or the opposite of left.',
        prompt: 'Spell RIGHT.',
        hint: 'R, I, G, H, T. The G and H are both silent.',
        success: 'RIGHT. Sounds identical, spelled completely differently!',
        build: { kind: 'word', text: 'RIGHT' } },
      { say: 'Three more pairs to finish: HEAR and HERE, and the number EIGHT.',
        prompt: 'Spell HEAR, HERE and EIGHT — one on each row.',
        hint: 'HEAR has EAR in it, and you hear with your ear. HERE is a place. EIGHT sounds like ATE.',
        success: 'You can hear the difference nowhere and see it everywhere. That is spelling for you!',
        build: { kind: 'words', list: ['HEAR', 'HERE', 'EIGHT'] } },
    ],
    reward: { coins: 110, items: [['hearth_loaf', 4], ['travel_biscuit', 4]] },
  },
];
