// Grade 1 — addition and subtraction within twenty, the teen numbers as a ten
// and some ones, measuring by counting units, halves, and blending sounds into
// real words. Still entirely read aloud.
export const GRADE_1 = [
  {
    id: 'g1_teens', subject: 'math', standard: '1.NBT.B.2', title: 'The Ferryman\'s Bundles',
    story: 'Old Rowan ferries firewood across the stream, and his boat only takes bundles of TEN. '
      + 'Anything left over rides on his lap. That is the secret of the teen numbers: '
      + 'thirteen is one bundle of ten, and three more on his lap.',
    steps: [
      { say: 'First load. Make one bundle of ten, and put three on their own beside it.',
        prompt: 'Make a row of exactly 10, a gap, then a row of 3.',
        hint: 'Ten in a line, all touching. Leave one empty square. Then three more.',
        success: 'One ten and three ones — that is THIRTEEN.',
        build: { kind: 'groups', block: 'brown_wool', sizes: [10, 3] } },
      { say: 'Next load is bigger. A bundle of ten, and six loose.',
        prompt: 'Make a row of 10, a gap, then a row of 6.',
        hint: 'Always the ten first. Then count the loose ones: one, two, three, four, five, six.',
        success: 'Ten and six is SIXTEEN. You can hear the six in the word!',
        build: { kind: 'groups', block: 'brown_wool', sizes: [10, 6] } },
      { say: 'This one is nearly two boats. Ten, and nine more.',
        prompt: 'Make a row of 10, a gap, then a row of 9.',
        hint: 'Ten, gap, then nine. One short of two whole bundles.',
        success: 'Ten and nine is NINETEEN — the biggest teen number there is.',
        build: { kind: 'groups', block: 'brown_wool', sizes: [10, 9] } },
      { say: 'And what if there is nothing left over? Just the one bundle.',
        prompt: 'Make one unbroken row of exactly 10.',
        hint: 'Ten in a straight line, every one touching the next. No gaps at all.',
        success: 'A whole ten with nothing left over. That is just called TEN!',
        build: { kind: 'count', block: 'brown_wool', n: 10 } },
      { say: 'Last load. Two full bundles of ten — that is a big word coming.',
        prompt: 'Make two rows of 10, with a gap between them.',
        hint: 'Ten on one row. Then ten more on the next row.',
        success: 'Two tens is TWENTY. The boat is full and Rowan is going home!',
        build: { kind: 'groups', block: 'brown_wool', sizes: [10, 10] } },
    ],
    reward: { coins: 45, items: [['brown_wool', 16], ['white_wool', 12]] },
  },
  {
    id: 'g1_add', subject: 'math', standard: '1.OA.C.6', title: 'The Market Stall',
    story: 'Maren is running a stall at the meadow market and she is terrible at sums. '
      + 'Every customer buys twice — some of this, then some of that — and you have to '
      + 'tell her the total before they wander off.',
    steps: [
      { say: 'First customer takes seven plums, then five more.',
        prompt: 'Put 12 purple blocks on the mat.',
        hint: 'Seven first. Then count on: eight, nine, ten, eleven, twelve.',
        success: 'Seven and five make twelve. Counting on is much quicker than starting again!',
        build: { kind: 'count', block: 'purple_wool', n: 12 } },
      { say: 'Show her WHY. Seven in one heap, five in the other, so she can see them join.',
        prompt: 'Make a group of 7 and a group of 5, with a gap between.',
        hint: 'Seven in a row, an empty square, then five in a row.',
        success: 'Seven and five, side by side. Together they are still twelve.',
        build: { kind: 'groups', block: 'purple_wool', sizes: [7, 5] } },
      { say: 'Next customer: nine apples and six pears.',
        prompt: 'Put 15 red blocks on the mat.',
        hint: 'Nine, then count on six more: ten, eleven, twelve, thirteen, fourteen, fifteen.',
        success: 'Nine and six make fifteen!',
        build: { kind: 'count', block: 'red_wool', n: 15 } },
      { say: 'Here is a trick. Nine and six is hard — but ten and five is easy. Move one across.',
        prompt: 'Make a group of 10 and a group of 5, with a gap between.',
        hint: 'Ten in a row. Gap. Five in a row. Same fifteen, easier to see.',
        success: 'Ten and five is fifteen too! Making a ten first makes every sum easier.',
        build: { kind: 'groups', block: 'red_wool', sizes: [10, 5] } },
      { say: 'Last customer of the day. Eight loaves and eight more.',
        prompt: 'Put 16 yellow blocks on the mat.',
        hint: 'Eight and eight. It is a double — say it with me: sixteen.',
        success: 'Double eight is sixteen. Maren says you can have the stall tomorrow!',
        build: { kind: 'count', block: 'yellow_wool', n: 16 } },
    ],
    reward: { coins: 45, items: [['purple_wool', 16], ['red_wool', 16]] },
  },
  {
    id: 'g1_sub', subject: 'math', standard: '1.OA.A.1', title: 'The Leaky Boat',
    story: 'Rowan\'s boat has sprung a leak and things keep falling out of it on the way across. '
      + 'You are on the far bank, counting what arrives. Load the boat, let the leak take some, '
      + 'and see what is left. That is subtraction — the story of what is missing.',
    steps: [
      { say: 'Twelve barrels go in. Three fall out through the hole.',
        prompt: 'Place 12 blue blocks, then break 3 of them.',
        hint: 'All twelve first, so we can see the full load. Then break three away.',
        success: 'Twelve take away three leaves nine.',
        build: { kind: 'subtract', block: 'blue_wool', from: 12, take: 3 } },
      { say: 'The leak gets worse. Fifteen loaded, five lost.',
        prompt: 'Place 15 blue blocks, then break 5 of them.',
        hint: 'Build fifteen. Then break five. Count what is still there.',
        success: 'Fifteen take away five leaves ten. A nice round number!',
        build: { kind: 'subtract', block: 'blue_wool', from: 15, take: 5 } },
      { say: 'Rowan patches the hole with his hat. Eleven in, only two lost.',
        prompt: 'Place 11 blue blocks, then break 2 of them.',
        hint: 'Eleven first. Then two away.',
        success: 'Eleven take away two leaves nine. The hat is working!',
        build: { kind: 'subtract', block: 'blue_wool', from: 11, take: 2 } },
      { say: 'Now work backwards. Nine arrived and four were lost — how many set off?',
        prompt: 'Place 13 blue blocks, then break 4 of them.',
        hint: 'Nine arrived, four went missing, so thirteen must have started. Build thirteen, then break four.',
        success: 'Thirteen set off, four were lost, nine arrived. You worked backwards!',
        build: { kind: 'subtract', block: 'blue_wool', from: 13, take: 4 } },
      { say: 'The very last crossing. Twenty barrels — and a wave takes half.',
        prompt: 'Place 20 blue blocks, then break 10 of them.',
        hint: 'Twenty is two whole rows of ten. Then break ten away.',
        success: 'Twenty take away ten leaves ten. Half the boat, saved!',
        build: { kind: 'subtract', block: 'blue_wool', from: 20, take: 10 } },
    ],
    reward: { coins: 50, items: [['blue_wool', 24], ['hearth_loaf', 2]] },
  },
  {
    id: 'g1_bonds', subject: 'math', standard: '1.OA.B.4', title: 'The Lantern Keeper',
    story: 'You have been made keeper of the meadow lanterns. There must always be ten lit, '
      + 'and Pip lights a few before she goes to bed. Knowing your pairs to ten by heart '
      + 'means you will never be out on the path in the dark.',
    steps: [
      { say: 'Pip lit four. Finish the row.',
        prompt: 'Add BLUE blocks until there are 10 altogether.',
        hint: 'Four are there. Count on: five, six, seven, eight, nine, ten.',
        success: 'Four and six make ten!',
        build: { kind: 'bond', have: { block: 'yellow_wool', n: 4 }, add: { block: 'blue_wool', n: 6 } } },
      { say: 'Tonight she only managed three.',
        prompt: 'Add BLUE blocks until there are 10 altogether.',
        hint: 'Three and how many more? Count on to ten.',
        success: 'Three and seven make ten!',
        build: { kind: 'bond', have: { block: 'yellow_wool', n: 3 }, add: { block: 'blue_wool', n: 7 } } },
      { say: 'A windy night — only one stayed alight.',
        prompt: 'Add BLUE blocks until there are 10 altogether.',
        hint: 'One and nine. Nearly the whole row is yours tonight.',
        success: 'One and nine make ten!',
        build: { kind: 'bond', have: { block: 'yellow_wool', n: 1 }, add: { block: 'blue_wool', n: 9 } } },
      { say: 'The path to the fair needs TWENTY. Pip lit fourteen of them.',
        prompt: 'Add BLUE blocks until there are 20 altogether.',
        hint: 'Fourteen and how many? Count on: fifteen… all the way to twenty. That is six.',
        success: 'Fourteen and six make twenty. Bonds work for bigger numbers too!',
        build: { kind: 'bond', have: { block: 'yellow_wool', n: 14 }, add: { block: 'blue_wool', n: 6 } } },
      { say: 'Finish by building the whole set yourself, so you know what twenty looks like.',
        prompt: 'Make two rows of 10, with a gap between them.',
        hint: 'Ten on one row, ten on the next.',
        success: 'Twenty lanterns. Nobody will get lost tonight!',
        build: { kind: 'groups', block: 'yellow_wool', sizes: [10, 10] } },
    ],
    reward: { coins: 50, items: [['yellow_wool', 20], ['blue_wool', 20]] },
  },
  {
    id: 'g1_measure', subject: 'math', standard: '1.MD.A.2', title: 'Measuring the Bridge',
    story: 'The stream needs a new footbridge and nobody in the meadow owns a ruler. '
      + 'But you can measure anything by counting how many blocks long it is — '
      + 'as long as every block is the same size and there are no gaps.',
    steps: [
      { say: 'Measure the plank first. Lay a row of blocks the same length as it: six.',
        prompt: 'Make one unbroken row of exactly 6.',
        hint: 'Six blocks in a straight line, all touching. No gaps — a gap would spoil the measurement.',
        success: 'The plank is six blocks long!',
        build: { kind: 'groups', block: 'gray_wool', sizes: [6] } },
      { say: 'The stream is wider than the plank. Nine blocks across.',
        prompt: 'Make one unbroken row of exactly 9.',
        hint: 'Nine in a line. Count them out loud as you go.',
        success: 'Nine across. The plank is too short — we knew that by measuring, not guessing!',
        build: { kind: 'groups', block: 'gray_wool', sizes: [9] } },
      { say: 'Compare them side by side: the six-plank and the nine-gap.',
        prompt: 'Make a row of 6 and a row of 9, with a gap between them.',
        hint: 'Six in one row, nine in another. Now you can see how much is missing.',
        success: 'Nine is three longer than six. That is the piece we still need!',
        build: { kind: 'groups', block: 'gray_wool', sizes: [9, 6] } },
      { say: 'Rowan has three posts of different heights. Stand them up: two, five and three.',
        prompt: 'Build three towers side by side: 2, 5 and 3 tall.',
        hint: 'Three separate stacks next to each other — two blocks, then five, then three.',
        success: 'The five is the tallest, the two is the shortest. Measured, not guessed!',
        build: { kind: 'stack', block: 'gray_wool', heights: [2, 5, 3] } },
      { say: 'Now put them in order, shortest to tallest, so he can choose.',
        prompt: 'Build four towers side by side: 1, 2, 3 and 4 tall.',
        hint: 'Start with one block. Each tower next to it is one taller.',
        success: 'In order, smallest to biggest. That is how you sort by size!',
        build: { kind: 'stack', block: 'gray_wool', heights: [1, 2, 3, 4] } },
    ],
    reward: { coins: 50, items: [['gray_wool', 20], ['light_gray_wool', 16]] },
  },
  {
    id: 'g1_half', subject: 'math', standard: '1.G.A.3', title: 'Sharing the Honey Cake',
    story: 'Thistle the hedgehog has baked an enormous honey cake and everyone wants a piece. '
      + 'Sharing FAIRLY means every piece is the same size. Half means two fair pieces. '
      + 'A quarter means four.',
    steps: [
      { say: 'Two hedgehogs, one cake. Make a cake of four slices and colour half of it.',
        prompt: 'Make a row of 4 blocks with exactly 2 of them pink.',
        hint: 'Four in a row. Two pink at one end, two white at the other.',
        success: 'Two out of four — that is one HALF. Both halves are the same size!',
        build: { kind: 'fraction', whole: 'white_wool', part: 'pink_wool', den: 4, num: 2 } },
      { say: 'Four guests turn up. Cut the same cake into four and take one piece.',
        prompt: 'Make a row of 4 blocks with exactly 1 of them pink.',
        hint: 'Four in a row, and only one of them pink.',
        success: 'One out of four — a QUARTER. Smaller piece, more friends fed.',
        build: { kind: 'fraction', whole: 'white_wool', part: 'pink_wool', den: 4, num: 1 } },
      { say: 'A bigger cake, six slices. Half of six is…?',
        prompt: 'Make a row of 6 blocks with exactly 3 of them pink.',
        hint: 'Six in a row, three pink. Count them — is each side the same?',
        success: 'Three out of six is a half as well! Halves can be different sizes and still be halves.',
        build: { kind: 'fraction', whole: 'white_wool', part: 'pink_wool', den: 6, num: 3 } },
      { say: 'Now the giant cake: eight slices, and half for the hedgehogs.',
        prompt: 'Make a row of 8 blocks with exactly 4 of them pink.',
        hint: 'Eight in a row. Four pink, four white.',
        success: 'Four out of eight — still a half. You are seeing the pattern!',
        build: { kind: 'fraction', whole: 'white_wool', part: 'pink_wool', den: 8, num: 4 } },
      { say: 'Last one, and the hardest. Eight slices, but only a QUARTER of it.',
        prompt: 'Make a row of 8 blocks with exactly 2 of them pink.',
        hint: 'Split eight into four fair groups — that is two each. So a quarter of eight is two.',
        success: 'Two out of eight is a quarter. Everyone got a fair piece!',
        build: { kind: 'fraction', whole: 'white_wool', part: 'pink_wool', den: 8, num: 2 } },
    ],
    reward: { coins: 55, items: [['pink_wool', 16], ['white_wool', 16]] },
  },
  {
    id: 'g1_grow', subject: 'math', standard: '1.OA.C.5', title: 'The Beanstalk Race',
    story: 'Pip and Nib the crow have planted beans and are racing them. '
      + 'Every morning each beanstalk grows the SAME amount as the day before. '
      + 'If you can spot the rule, you can say how tall it will be tomorrow without waiting.',
    steps: [
      { say: 'Day one, day two, day three: one block, two blocks, three blocks.',
        prompt: 'Build three towers side by side: 1, 2 and 3 tall.',
        hint: 'One block, then a stack of two beside it, then three.',
        success: 'Up by one every day. Tomorrow it will be four!',
        build: { kind: 'stack', block: 'lime_wool', heights: [1, 2, 3] } },
      { say: 'You were right. Show four days in a row.',
        prompt: 'Build four towers side by side: 1, 2, 3 and 4 tall.',
        hint: 'Add a tower of four on the end of the ones you had.',
        success: 'Four days, growing by one each time. That is a rule you can trust!',
        build: { kind: 'stack', block: 'lime_wool', heights: [1, 2, 3, 4] } },
      { say: 'Nib\'s bean is a fast one. It goes up TWO every day: two, four, six.',
        prompt: 'Build three towers side by side: 2, 4 and 6 tall.',
        hint: 'Two, then four, then six. Each one is two taller than the last.',
        success: 'Two, four, six — counting in twos. Nib is winning!',
        build: { kind: 'stack', block: 'lime_wool', heights: [2, 4, 6] } },
      { say: 'Some beans go the other way when the frost comes. Six, four, two.',
        prompt: 'Build three towers side by side: 6, 4 and 2 tall.',
        hint: 'Start tall this time: six, then four, then two. Down by two each day.',
        success: 'Down by two each time. A pattern can shrink as well as grow!',
        build: { kind: 'stack', block: 'lime_wool', heights: [6, 4, 2] } },
      { say: 'Last one. Odd numbers: one, three, five, seven.',
        prompt: 'Build four towers side by side: 1, 3, 5 and 7 tall.',
        hint: 'One, three, five, seven. Two taller each time, starting at one.',
        success: 'One, three, five, seven — the odd numbers. Now you can carry on forever!',
        build: { kind: 'stack', block: 'lime_wool', heights: [1, 3, 5, 7] } },
    ],
    reward: { coins: 55, items: [['lime_wool', 20], ['green_wool', 16]] },
  },
  {
    id: 'g1_blend', subject: 'reading', standard: 'RF.1.2.B', title: 'The Word Wood',
    story: 'The Word Wood grows words instead of leaves, but the wind has blown the letters loose. '
      + 'Say each word slowly and listen — every sound you hear needs a letter, in the order you hear it. '
      + 'Sounding out is a skill, and it gets faster every time you use it.',
    steps: [
      { say: 'A little red bird on the branch. R… e… d.',
        prompt: 'Spell RED.',
        hint: 'Three sounds: R, E, D. Put the letters in a row, all touching.',
        success: 'R-E-D spells RED!',
        build: { kind: 'word', text: 'RED' } },
      { say: 'Something big and green with a trunk. T… r… e… e. Two letter E\'s at the end.',
        prompt: 'Spell TREE.',
        hint: 'T, R, then two E\'s. Some words use two letters for one sound.',
        success: 'T-R-E-E spells TREE. Well spotted — two E\'s, one sound.',
        build: { kind: 'word', text: 'TREE' } },
      { say: 'The little house you sleep in at the camp. T… e… n… t.',
        prompt: 'Spell TENT.',
        hint: 'Four sounds this time: T, E, N, T. Say it slowly and you will hear them all.',
        success: 'T-E-N-T spells TENT. Four sounds, four letters!',
        build: { kind: 'word', text: 'TENT' } },
      { say: 'What Rowan sails across the stream. B… o… a… t.',
        prompt: 'Spell BOAT.',
        hint: 'B, O, A, T. The O and A sit together in the middle.',
        success: 'B-O-A-T spells BOAT!',
        build: { kind: 'word', text: 'BOAT' } },
      { say: 'Three words that all end the same way. Listen: PIG, BIG, DIG.',
        prompt: 'Spell PIG, BIG and DIG — one on each row.',
        hint: 'They all end I-G. Only the first letter changes.',
        success: 'PIG, BIG, DIG. When words end the same, they rhyme — and they are easier to read!',
        build: { kind: 'words', list: ['PIG', 'BIG', 'DIG'] } },
    ],
    reward: { coins: 55, items: [['letter_s', 4], ['letter_t', 4], ['letter_o', 4], ['letter_p', 4]] },
  },
  {
    id: 'g1_sight', subject: 'reading', standard: 'RF.1.3.G', title: 'Words You Just Know',
    story: 'Some words turn up in EVERY story, so often that it is quicker to know them by sight '
      + 'than to sound them out each time. Pip calls them the "just know them" words. '
      + 'Build each one and say it — by the fifth you will not be sounding them out at all.',
    steps: [
      { say: 'The commonest word in the whole language. T, H, E.',
        prompt: 'Spell THE.',
        hint: 'T, H, E. Do not try to sound it out — this one you just learn.',
        success: 'THE. You will see that word a thousand times this year!',
        build: { kind: 'word', text: 'THE' } },
      { say: 'The word that joins things together. A, N, D.',
        prompt: 'Spell AND.',
        hint: 'A, N, D — this one you CAN sound out.',
        success: 'AND. Cats AND dogs. Bread AND jam.',
        build: { kind: 'word', text: 'AND' } },
      { say: 'What you do with your eyes. S, A, I, D — but it does not sound like it looks.',
        prompt: 'Spell SAID.',
        hint: 'S, A, I, D. It sounds like "sed", but it is spelled with an A and an I.',
        success: 'SAID. A tricky one — good thing you just know it now!',
        build: { kind: 'word', text: 'SAID' } },
      { say: 'Where things are. H, E, R, E.',
        prompt: 'Spell HERE.',
        hint: 'H, E, R, E. The E on the end is silent.',
        success: 'HERE. Silent E on the end, doing its quiet job.',
        build: { kind: 'word', text: 'HERE' } },
      { say: 'Three more for the collection: YOU, ARE and WAS.',
        prompt: 'Spell YOU, ARE and WAS — one on each row.',
        hint: 'Y-O-U. A-R-E. W-A-S. Say each one as you finish it.',
        success: 'YOU ARE WAS — three more words you just know. You can read a whole sentence now!',
        build: { kind: 'words', list: ['YOU', 'ARE', 'WAS'] } },
    ],
    reward: { coins: 60, items: [['letter_e', 4], ['letter_h', 4], ['letter_r', 4]] },
  },
  {
    id: 'g1_story', subject: 'reading', standard: 'RL.1.2', title: 'Beginning, Middle, End',
    story: 'Pip wants to write down the story of the leaky boat, but she cannot remember the order. '
      + 'Every story has a BEGINNING, a MIDDLE and an END, and they only make sense that way round. '
      + 'You will build the shape of a story, then label it.',
    steps: [
      { say: 'Three parts to a story. Build three towers to stand for them.',
        prompt: 'Build three towers side by side: 1, 2 and 3 tall.',
        hint: 'One block for the beginning, two for the middle, three for the end.',
        success: 'Three parts, in order — a story never starts in the middle!',
        build: { kind: 'stack', block: 'orange_wool', heights: [1, 2, 3] } },
      { say: 'Label the first part. The story BEGAN when the boat set off.',
        prompt: 'Spell ONE.',
        hint: 'O, N, E — the first part.',
        success: 'ONE: the boat set off. That is the beginning.',
        build: { kind: 'word', text: 'ONE' } },
      { say: 'The middle is where the trouble happens. The boat sprang a leak.',
        prompt: 'Spell TWO.',
        hint: 'T, W, O. The W is silent!',
        success: 'TWO: the leak. Every good story has a problem in the middle.',
        build: { kind: 'word', text: 'TWO' } },
      { say: 'And at the END, the problem is solved. Rowan patched it with his hat.',
        prompt: 'Spell END.',
        hint: 'E, N, D. Three letters.',
        success: 'END: the hat saved the day. Now the story is whole!',
        build: { kind: 'word', text: 'END' } },
      { say: 'Write the three labels together so Pip can pin them up.',
        prompt: 'Spell ONE, TWO and END — one on each row.',
        hint: 'O-N-E, then T-W-O, then E-N-D, each on its own row.',
        success: 'Beginning, middle, end. That is how every story you ever read is built!',
        build: { kind: 'words', list: ['ONE', 'TWO', 'END'] } },
    ],
    reward: { coins: 65, items: [['hearth_loaf', 3], ['travel_biscuit', 3]] },
  },
];
