// Grade 8 — exponents as repeated multiplication you can pick up, scientific
// notation, slope and linear functions, where two lines cross, the theorem that
// squares on the sides of a right triangle add up, transformations, and tone.
export const GRADE_8 = [
  {
    id: 'g8_exp', subject: 'math', standard: '8.EE.A.1', title: 'Squares and Cubes',
    story: 'A power is not "times itself a lot" — it is a SHAPE. Two squared is a square. '
      + 'Two cubed is a cube. Once you have held one, exponents stop being decoration '
      + 'on top of a number and start being the number\'s shape.',
    steps: [
      { say: 'Two squared: two rows of two.',
        prompt: 'Build 2 rows with 2 blocks in each row.',
        hint: 'A little square, two by two.',
        success: 'Four. Two squared IS a square — that is where the word comes from.',
        build: { kind: 'array', block: 'purple_wool', rows: 2, cols: 2 } },
      { say: 'Now two CUBED. Take the square and give it depth: two high as well.',
        prompt: 'Build a solid block 2 across, 2 back and 2 tall.',
        hint: 'The two-by-two square, and another one on top of it.',
        success: 'Eight. Two cubed is a cube — two times two times two.',
        build: { kind: 'box', block: 'purple_wool', w: 2, d: 2, h: 2 } },
      { say: 'Three squared.',
        prompt: 'Build 3 rows with 3 blocks in each row.',
        hint: 'Three by three.',
        success: 'Nine. Three squared.',
        build: { kind: 'array', block: 'purple_wool', rows: 3, cols: 3 } },
      { say: 'And three cubed. Brace yourself — powers grow fast.',
        prompt: 'Build a solid block 3 across, 3 back and 3 tall.',
        hint: 'Three layers of nine.',
        success: 'Twenty-seven! From nine to twenty-seven with one more dimension.',
        build: { kind: 'box', block: 'purple_wool', w: 3, d: 3, h: 3 } },
      { say: 'The doubling powers, as towers: two, four, eight — the mat caps at seven, so build up to seven.',
        prompt: 'Build four towers side by side: 1, 2, 4 and 7 tall.',
        hint: 'One, two, four, and the next would be eight — one taller than the ceiling.',
        success: 'One, two, four, eight, sixteen… doubling outruns any mat there is!',
        build: { kind: 'stack', block: 'purple_wool', heights: [1, 2, 4, 7] } },
    ],
    reward: { coins: 175, items: [['purple_wool', 50]] },
  },
  {
    id: 'g8_sci', subject: 'math', standard: '8.EE.A.3', title: 'Numbers Too Big to Write',
    story: 'The star-charter needs to write down distances with twenty noughts on the end, '
      + 'and he is not going to count noughts for a living. Scientific notation says '
      + 'a small number, then how many times to multiply it by ten. That is all it is.',
    steps: [
      { say: 'Ten to the power one: one row of ten.',
        prompt: 'Build 1 row with 10 blocks in it.',
        hint: 'Ten in a straight line.',
        success: 'Ten. One nought.',
        build: { kind: 'array', block: 'white_wool', rows: 1, cols: 10 } },
      { say: 'Ten to the power two is a hundred — that is ten of those rows. Build five of them and picture double.',
        prompt: 'Build 5 rows with 10 blocks in each row.',
        hint: 'Ten in a row, five rows. Half of a hundred.',
        success: 'Fifty here, and a hundred would need two of these mats. Two noughts already needs a room!',
        build: { kind: 'array', block: 'white_wool', rows: 5, cols: 10 } },
      { say: 'Now the front part. Three times ten means three lots of ten.',
        prompt: 'Build 3 rows with 10 blocks in each row.',
        hint: 'Three rows of ten.',
        success: 'Thirty. Written properly: three times ten to the power one.',
        build: { kind: 'array', block: 'cyan_wool', rows: 3, cols: 10 } },
      { say: 'Small numbers work the same way backwards. Ten to the power MINUS one is a tenth.',
        prompt: 'Make a row of 10 blocks with exactly 1 of them cyan.',
        hint: 'One out of ten — nought point one.',
        success: 'A tenth. A negative power means DIVIDE by ten, not "a negative number".',
        build: { kind: 'fraction', whole: 'white_wool', part: 'cyan_wool', den: 10, num: 1 } },
      { say: 'Last: two and a half times ten. Two full rows and a half row.',
        prompt: 'Make a group of 10, a group of 10 and a group of 5.',
        hint: 'Ten, ten, and five: twenty-five.',
        success: 'Twenty-five, or two point five times ten. Now the star-charter can go to bed!',
        build: { kind: 'groups', block: 'cyan_wool', sizes: [10, 10, 5] } },
    ],
    reward: { coins: 175, items: [['white_wool', 50], ['cyan_wool', 30]] },
  },
  {
    id: 'g8_slope', subject: 'math', standard: '8.EE.B.5', title: 'The Steepness of the Ramp',
    story: 'The carpenter builds ramps and describes every one with a single number: '
      + 'how far it RISES for every step it RUNS. A slope of one goes up one for every one along. '
      + 'A slope of two is twice as steep, and a slope of nothing is flat.',
    steps: [
      { say: 'A gentle ramp. Up one for every one along: one, two, three, four.',
        prompt: 'Build four towers side by side: 1, 2, 3 and 4 tall.',
        hint: 'Each tower one taller than the one before it.',
        success: 'Rise one, run one. A slope of ONE.',
        build: { kind: 'stack', block: 'brown_wool', heights: [1, 2, 3, 4] } },
      { say: 'Twice as steep: up two for every one along.',
        prompt: 'Build three towers side by side: 2, 4 and 6 tall.',
        hint: 'Two, four, six — going up two each time.',
        success: 'Rise two, run one. A slope of TWO — you can see it is steeper.',
        build: { kind: 'stack', block: 'brown_wool', heights: [2, 4, 6] } },
      { say: 'A shallow one: up one for every TWO along. Pairs of equal towers.',
        prompt: 'Build six towers side by side: 1, 1, 2, 2, 3 and 3 tall.',
        hint: 'Two at one, two at two, two at three — it takes two steps to climb one.',
        success: 'Rise one, run two. A slope of a HALF — the gentlest ramp yet.',
        build: { kind: 'stack', block: 'brown_wool', heights: [1, 1, 2, 2, 3, 3] } },
      { say: 'And a flat floor? No rise at all.',
        prompt: 'Build five towers side by side, all exactly 3 tall.',
        hint: 'Five towers, all the same height.',
        success: 'No rise for any run. A slope of ZERO — perfectly level.',
        build: { kind: 'stack', block: 'brown_wool', heights: [3, 3, 3, 3, 3] } },
      { say: 'Last: a ramp going DOWN as you walk along. Six, four, two.',
        prompt: 'Build three towers side by side: 6, 4 and 2 tall.',
        hint: 'Starting high and dropping by two each step.',
        success: 'Falling two for every one along — a slope of MINUS two. Direction matters!',
        build: { kind: 'stack', block: 'brown_wool', heights: [6, 4, 2] } },
    ],
    reward: { coins: 180, items: [['brown_wool', 50]] },
  },
  {
    id: 'g8_linear', subject: 'math', standard: '8.F.B.4', title: 'The Toll Road',
    story: 'The toll road charges one coin to join and two coins for every mile. '
      + 'That is a linear function: a starting amount, and a steady rate on top. '
      + 'Build the table of what it costs and the shape of the rule appears in front of you.',
    steps: [
      { say: 'Nought miles still costs one coin, just to join.',
        prompt: 'Build ONE tower exactly 1 tall.',
        hint: 'One block. That is the joining fee — the y-intercept.',
        success: 'One coin before you have moved. That is where the line starts.',
        build: { kind: 'tower', block: 'yellow_wool', h: 1 } },
      { say: 'One mile: the fee, plus two.',
        prompt: 'Build two towers side by side: 1 and 3 tall.',
        hint: 'One for nought miles, three for one mile.',
        success: 'One and three. Up two for every mile.',
        build: { kind: 'stack', block: 'yellow_wool', heights: [1, 3] } },
      { say: 'Carry the table on: nought, one, two and three miles.',
        prompt: 'Build four towers side by side: 1, 3, 5 and 7 tall.',
        hint: 'One, three, five, seven — two more each mile.',
        success: 'A perfectly straight climb. Cost equals two times miles, plus one!',
        build: { kind: 'stack', block: 'yellow_wool', heights: [1, 3, 5, 7] } },
      { say: 'A rival road charges nothing to join and two a mile. Same steepness, different start.',
        prompt: 'Build four towers side by side: 2, 4, 6 and 7 tall.',
        hint: 'Two, four, six, and eight would be next — but the ceiling is seven.',
        success: 'The same slope, starting lower. Two lines with the same steepness never meet — they are PARALLEL.',
        build: { kind: 'stack', block: 'orange_wool', heights: [2, 4, 6, 7] } },
      { say: 'A third road charges three to join and one a mile. Slower climb, higher start.',
        prompt: 'Build four towers side by side: 3, 4, 5 and 6 tall.',
        hint: 'Three, four, five, six — up one each mile.',
        success: 'A gentler line that starts higher. Somewhere ahead the steep road overtakes it!',
        build: { kind: 'stack', block: 'orange_wool', heights: [3, 4, 5, 6] } },
    ],
    reward: { coins: 180, items: [['yellow_wool', 40], ['orange_wool', 40]] },
  },
  {
    id: 'g8_system', subject: 'math', standard: '8.EE.C.8', title: 'Where the Two Roads Cross',
    story: 'Two toll roads, two different deals. One starts cheap and climbs fast; '
      + 'the other starts dear and climbs slowly. There is exactly one distance where they cost '
      + 'the same — and that crossing point is the answer to a pair of equations at once.',
    steps: [
      { say: 'Road A: one to join, two a mile. Build four miles of it.',
        prompt: 'Build four towers side by side: 1, 3, 5 and 7 tall.',
        hint: 'One, three, five, seven.',
        success: 'Road A, climbing fast.',
        build: { kind: 'stack', block: 'red_wool', heights: [1, 3, 5, 7] } },
      { say: 'Road B: four to join, one a mile.',
        prompt: 'Build four towers side by side: 4, 5, 6 and 7 tall.',
        hint: 'Four, five, six, seven — up one each mile.',
        success: 'Road B, starting dear and climbing slowly.',
        build: { kind: 'stack', block: 'blue_wool', heights: [4, 5, 6, 7] } },
      { say: 'Look at the last tower of each: both were SEVEN. That is where they cross.',
        prompt: 'Build a tower 7 tall on the LEFT and a tower 7 tall on the RIGHT.',
        hint: 'Seven each side of the wooden line — the two roads, level at last.',
        success: 'At three miles both cost seven. That is the SOLUTION to the pair!',
        build: { kind: 'compare', block: 'green_wool', left: 7, right: 7 } },
      { say: 'Before the crossing, road A is cheaper. At one mile: three against five.',
        prompt: 'Build a tower 3 tall on the LEFT and a tower 5 tall on the RIGHT.',
        hint: 'Three for road A, five for road B.',
        success: 'Road A wins early — cheaper for any short journey.',
        build: { kind: 'compare', block: 'green_wool', left: 3, right: 5 } },
      { say: 'And what if two roads never cross? Same rate, different start — build A at 2,4,6 and B at 3,5,7.',
        prompt: 'Build six towers side by side: 2, 3, 4, 5, 6 and 7 tall.',
        hint: 'The two lines interleaved: two, three, four, five, six, seven.',
        success: 'Parallel lines never meet, so that pair has NO solution. A pair of equations can have one answer, none, or infinitely many!',
        build: { kind: 'stack', block: 'green_wool', heights: [2, 3, 4, 5, 6, 7] } },
    ],
    reward: { coins: 185, items: [['red_wool', 30], ['blue_wool', 30], ['green_wool', 30]] },
  },
  {
    id: 'g8_pyth', subject: 'math', standard: '8.G.B.7', title: 'The Knotted Rope',
    story: 'Egyptian builders carried a rope knotted into twelve equal lengths. '
      + 'Pegged out as three, four and five, it makes a perfect right angle every time. '
      + 'Today you build the reason it works, and it is the prettiest thing in mathematics.',
    steps: [
      { say: 'The short side is three. Build the square on it: three by three.',
        prompt: 'Build 3 rows with 3 blocks in each row.',
        hint: 'A three-by-three square.',
        success: 'Nine. Three squared.',
        build: { kind: 'array', block: 'red_wool', rows: 3, cols: 3 } },
      { say: 'The next side is four. Build its square.',
        prompt: 'Build 4 rows with 4 blocks in each row.',
        hint: 'A four-by-four square.',
        success: 'Sixteen. Four squared.',
        build: { kind: 'array', block: 'blue_wool', rows: 4, cols: 4 } },
      { say: 'Nine and sixteen. Add them: twenty-five. Now build the square on the LONG side, which is five.',
        prompt: 'Build 5 rows with 5 blocks in each row.',
        hint: 'A five-by-five square.',
        success: 'Twenty-five — exactly nine plus sixteen. The two small squares fill the big one perfectly!',
        build: { kind: 'array', block: 'green_wool', rows: 5, cols: 5 } },
      { say: 'Draw the triangle itself: three along the front and four up the side.',
        prompt: 'Put blocks along 4 squares of the front row and 3 squares up the left edge.',
        hint: 'Four in a line going across, and three going back from the same corner.',
        success: 'The right angle sits in the corner where the two legs meet.',
        build: { kind: 'cells', block: 'white_wool',
          at: [[0, 0, 0], [1, 0, 0], [2, 0, 0], [3, 0, 0], [0, 0, 1], [0, 0, 2]] } },
      { say: 'One more triple that works the same way: six, eight, ten. Build the square on six.',
        prompt: 'Build 5 rows with 7 blocks in each row.',
        hint: 'Six squared is thirty-six — a six-by-six square will not fit five rows, so build five by seven and remember.',
        success: 'Thirty-six and sixty-four make a hundred. Three-four-five doubled is six-eight-ten, and it still works!',
        build: { kind: 'array', block: 'white_wool', rows: 5, cols: 7 } },
    ],
    reward: { coins: 185, items: [['red_wool', 30], ['blue_wool', 30], ['green_wool', 30]] },
  },
  {
    id: 'g8_transform', subject: 'math', standard: '8.G.A.1', title: 'Slide, Flip, Turn',
    story: 'There are only three things you can do to a shape without changing its size: '
      + 'slide it, flip it, or turn it. Mathematicians call them translation, reflection and rotation, '
      + 'and every pattern in every tiled floor you have ever walked on is made of those three.',
    steps: [
      { say: 'A FLIP first — reflection. Four blocks one side of the line, four mirrored on the other.',
        prompt: 'Make 4 matching pairs across the line.',
        hint: 'Whatever you put a certain distance from the line, put its twin the same distance the other side.',
        success: 'A reflection. The shape is the same size — just handed over.',
        build: { kind: 'mirror', block: 'magenta_wool', pairs: 4 } },
      { say: 'A bigger reflection: eight pairs.',
        prompt: 'Make 8 matching pairs across the line.',
        hint: 'Fill one row of pairs, then start the next — always both sides at once.',
        success: 'Eight pairs, both sides identical.',
        build: { kind: 'mirror', block: 'magenta_wool', pairs: 8 } },
      { say: 'A SLIDE — translation. The same shape, moved along. Build an L in one corner.',
        prompt: 'Put blocks at 0-across-0-back, 0-across-1-back, 0-across-2-back and 1-across-0-back.',
        hint: 'Three going back from the corner, and one to the right of the corner.',
        success: 'An L shape. Now watch what a slide does to it.',
        build: { kind: 'cells', block: 'lime_wool', at: [[0, 0, 0], [0, 0, 1], [0, 0, 2], [1, 0, 0]] } },
      { say: 'The same L, slid five squares across. Not turned, not flipped — just moved.',
        prompt: 'Put blocks at 5-across-0-back, 5-across-1-back, 5-across-2-back and 6-across-0-back.',
        hint: 'Exactly the same shape, five squares further along.',
        success: 'A translation. Same shape, same size, same way up — just somewhere else.',
        build: { kind: 'cells', block: 'lime_wool', at: [[5, 0, 0], [5, 0, 1], [5, 0, 2], [6, 0, 0]] } },
      { say: 'And a TURN — rotation. The same L, spun a quarter turn.',
        prompt: 'Put blocks at 0-across-0-back, 1-across-0-back, 2-across-0-back and 0-across-1-back.',
        hint: 'Three going ACROSS this time, and one going back from the corner.',
        success: 'Rotated a quarter turn. Slide, flip, turn — and the shape never changed size once!',
        build: { kind: 'cells', block: 'lime_wool', at: [[0, 0, 0], [1, 0, 0], [2, 0, 0], [0, 0, 1]] } },
    ],
    reward: { coins: 185, items: [['magenta_wool', 40], ['lime_wool', 30]] },
  },
  {
    id: 'g8_data', subject: 'math', standard: '8.SP.A.1', title: 'Two Things at Once',
    story: 'Pip measured every seedling twice: how much water it got, and how tall it grew. '
      + 'Two numbers for each plant. Plot them together and a shape appears — '
      + 'and that shape tells you whether the two things are connected at all.',
    steps: [
      { say: 'Five seedlings, more water each time, and each one taller: one, two, three, four, five.',
        prompt: 'Build five towers side by side: 1, 2, 3, 4 and 5 tall.',
        hint: 'Climbing steadily, one at a time.',
        success: 'As water goes up, height goes up. That is a POSITIVE association.',
        build: { kind: 'stack', block: 'lime_wool', heights: [1, 2, 3, 4, 5] } },
      { say: 'Now the ones in the shade: more water, but LESS light, and they got shorter: six, five, four, three, two.',
        prompt: 'Build five towers side by side: 6, 5, 4, 3 and 2 tall.',
        hint: 'Starting tall and dropping each time.',
        success: 'As one goes up the other goes down. A NEGATIVE association.',
        build: { kind: 'stack', block: 'lime_wool', heights: [6, 5, 4, 3, 2] } },
      { say: 'And the ones in the greenhouse, where water made no difference at all: four, four, four, four, four.',
        prompt: 'Build five towers side by side, all exactly 4 tall.',
        hint: 'All the same height.',
        success: 'No pattern at all. NO association — the two things are simply unconnected.',
        build: { kind: 'stack', block: 'lime_wool', heights: [4, 4, 4, 4, 4] } },
      { say: 'Real data is never that tidy. Here is the messy version: two, three, three, five, four.',
        prompt: 'Build five towers side by side: 2, 3, 3, 5 and 4 tall.',
        hint: 'Two, three, three, five, four — mostly climbing, but not perfectly.',
        success: 'Still climbing overall, with wobble. Real measurements always wobble.',
        build: { kind: 'stack', block: 'lime_wool', heights: [2, 3, 3, 5, 4] } },
      { say: 'The TREND LINE is the straight line that best describes the wobble. Build the tidy version of it.',
        prompt: 'Build five towers side by side: 2, 3, 3, 4 and 5 tall.',
        hint: 'The smoothest climb that still fits the messy data.',
        success: 'A trend line. It ignores the wobble and shows the story — as long as you remember it is only a summary!',
        build: { kind: 'stack', block: 'lime_wool', heights: [2, 3, 3, 4, 5] } },
    ],
    reward: { coins: 190, items: [['lime_wool', 50]] },
  },
  {
    id: 'g8_tone', subject: 'reading', standard: 'RL.8.6', title: 'How It Is Said',
    story: 'Two people can report the same event and leave you feeling completely differently about it. '
      + 'That is TONE — the writer\'s attitude, leaking through their word choices. '
      + 'Learn to hear it and nobody can steer you without you noticing.',
    steps: [
      { say: 'The writer\'s attitude to what they are describing has a name.',
        prompt: 'Spell TONE.',
        hint: 'T, O, N, E.',
        success: 'TONE. Angry, fond, mocking, sad — all carried in the choice of words.',
        build: { kind: 'word', text: 'TONE' } },
      { say: 'What the reader is left feeling is a different thing again.',
        prompt: 'Spell MOOD.',
        hint: 'M, O, O, D.',
        success: 'MOOD — the feeling in the reader. Tone is the writer; mood is you.',
        build: { kind: 'word', text: 'MOOD' } },
      { say: 'When somebody says the opposite of what they mean, and everyone knows it.',
        prompt: 'Spell IRONY.',
        hint: 'I-R-O-N-Y. "Lovely weather," in a downpour.',
        success: 'IRONY. The words say one thing; the tone says the reverse.',
        build: { kind: 'word', text: 'IRONY' } },
      { say: 'And the slant a writer puts on a story, on purpose or without knowing.',
        prompt: 'Spell BIAS.',
        hint: 'B, I, A, S.',
        success: 'BIAS. Everyone has some. Spotting it is how you read the news.',
        build: { kind: 'word', text: 'BIAS' } },
      { say: 'The four to carry with you.',
        prompt: 'Spell TONE, MOOD and BIAS — one on each row.',
        hint: 'T-O-N-E. M-O-O-D. B-I-A-S.',
        success: 'Tone, mood, irony, bias. You can now read what a writer is DOING, not just what they said!',
        build: { kind: 'words', list: ['TONE', 'MOOD', 'BIAS'] } },
    ],
    reward: { coins: 190, items: [['letter_o', 6], ['letter_n', 6], ['letter_b', 4]] },
  },
  {
    id: 'g8_academic', subject: 'reading', standard: 'L.8.6', title: 'The Words That Open Doors',
    story: 'Every subject you meet from here on has its own handful of words that do the heavy lifting. '
      + 'They turn up in exam questions, in science papers, in essays, everywhere — '
      + 'and knowing exactly what each one is ASKING is half of every answer.',
    steps: [
      { say: 'The first one asks you to break something into its parts and look at each.',
        prompt: 'Spell ANALYSE.',
        hint: 'A-N-A-L-Y-S-E. Seven letters.',
        success: 'ANALYSE — take it apart and examine the pieces. Not "describe"!',
        build: { kind: 'word', text: 'ANALYSE' } },
      { say: 'This one asks for what is the same and what is different.',
        prompt: 'Spell COMPARE.',
        hint: 'C-O-M-P-A-R-E.',
        success: 'COMPARE — both the likenesses AND the differences. People forget the differences.',
        build: { kind: 'word', text: 'COMPARE' } },
      { say: 'This one asks you to judge how good, useful or true something is.',
        prompt: 'Spell EVALUATE.',
        hint: 'E-V-A-L-U-A-T-E. Eight letters.',
        success: 'EVALUATE — weigh it up and come down on a side. An opinion, with reasons.',
        build: { kind: 'word', text: 'EVALUATE' } },
      { say: 'And this one asks WHY, not what.',
        prompt: 'Spell EXPLAIN.',
        hint: 'E-X-P-L-A-I-N.',
        success: 'EXPLAIN — give the reasons and the causes, not just the facts.',
        build: { kind: 'word', text: 'EXPLAIN' } },
      { say: 'The four command words, together. Get these right and you have answered the question that was asked.',
        prompt: 'Spell EXPLAIN, COMPARE and EVALUATE — one on each row.',
        hint: 'E-X-P-L-A-I-N. C-O-M-P-A-R-E. E-V-A-L-U-A-T-E.',
        success: 'Analyse, compare, evaluate, explain. That is the whole of school in four words — and the whole of this curriculum finished. Well done!',
        build: { kind: 'words', list: ['EXPLAIN', 'COMPARE', 'EVALUATE'] } },
    ],
    reward: { coins: 250, items: [['hearth_loaf', 6], ['travel_biscuit', 6]] },
  },
];
