// Grade 2 — place value to a hundred, skip counting, even and odd, the array
// model that becomes multiplication next year, measuring and comparing, reading
// a graph, and words made of other words.
export const GRADE_2 = [
  {
    id: 'g2_tens', subject: 'math', standard: '2.NBT.A.1', title: 'The Tally Keeper',
    story: 'Every barn in the meadow keeps its count in bundles of ten, because nobody can look at '
      + 'a heap of forty-three things and know it is forty-three. Bundle them by ten and you can. '
      + 'The bundles are the TENS and the loose ones are the ONES.',
    steps: [
      { say: 'The hay barn has twenty-four bales. Two bundles of ten, and four loose.',
        prompt: 'Make two rows of 10 and one row of 4, each with a gap between.',
        hint: 'A row of ten. Then another row of ten. Then four on their own.',
        success: 'Two tens and four ones is TWENTY-FOUR. You can read it straight off the mat!',
        build: { kind: 'groups', block: 'yellow_wool', sizes: [10, 10, 4] } },
      { say: 'The apple store has thirty-one. How many bundles?',
        prompt: 'Make three rows of 10 and one row of 1.',
        hint: 'Three tens — that is thirty — and one single left over.',
        success: 'Three tens and one one is THIRTY-ONE!',
        build: { kind: 'groups', block: 'red_wool', sizes: [10, 10, 10, 1] } },
      { say: 'Trickier. The seed shed has forty-three.',
        prompt: 'Make four rows of 10 and one row of 3.',
        hint: 'Four bundles of ten is forty. Then three loose ones.',
        success: 'Four tens and three ones is FORTY-THREE. The four is worth forty, not four!',
        build: { kind: 'groups', block: 'brown_wool', sizes: [10, 10, 10, 10, 3] } },
      { say: 'A tricky one. Twenty exactly — no loose ones at all.',
        prompt: 'Make two rows of 10, with a gap between them.',
        hint: 'Just the two bundles. Nothing left over.',
        success: 'Two tens and NO ones is twenty. That is what the zero in twenty is for!',
        build: { kind: 'groups', block: 'green_wool', sizes: [10, 10] } },
      { say: 'Last count of the day: the egg store, with thirty-six.',
        prompt: 'Make three rows of 10 and one row of 6.',
        hint: 'Three tens, then six ones.',
        success: 'Thirty-six. Three tens and six ones. You are a proper tally keeper now!',
        build: { kind: 'groups', block: 'white_wool', sizes: [10, 10, 10, 6] } },
    ],
    reward: { coins: 60, items: [['yellow_wool', 20], ['white_wool', 20]] },
  },
  {
    id: 'g2_skip', subject: 'math', standard: '2.NBT.A.2', title: 'The Fence Posts',
    story: 'Maren is fencing the goat field and the posts go in every five paces. '
      + 'Counting one at a time takes all afternoon. Counting in FIVES takes a minute — '
      + 'and it is the same answer.',
    steps: [
      { say: 'Four rows of posts, five in each row. Do not count them one by one.',
        prompt: 'Build 4 rows with 5 blocks in each row.',
        hint: 'A row of five. Then another. Then another. Then one more.',
        success: 'Five, ten, fifteen, TWENTY. Counting in fives got you there four times faster!',
        build: { kind: 'array', block: 'brown_wool', rows: 4, cols: 5 } },
      { say: 'The long side takes three rows of ten.',
        prompt: 'Build 3 rows with 10 blocks in each row.',
        hint: 'Ten in a row, three times over.',
        success: 'Ten, twenty, THIRTY. Counting in tens is the fastest of all.',
        build: { kind: 'array', block: 'brown_wool', rows: 3, cols: 10 } },
      { say: 'Now count in twos. Five pairs of posts, one pair per group.',
        prompt: 'Make 5 groups of 2, with gaps between them.',
        hint: 'Two together, a gap, two more, a gap — five little pairs.',
        success: 'Two, four, six, eight, TEN. Counting in twos!',
        build: { kind: 'groups', block: 'gray_wool', sizes: [2, 2, 2, 2, 2] } },
      { say: 'The gate needs a row of five posts on each side of the line — count them in fives.',
        prompt: 'Build 5 rows with 5 blocks in each row.',
        hint: 'Five rows, five in each. Five, ten, fifteen, twenty, twenty-five.',
        success: 'Twenty-five. Five fives — and it makes a perfect square!',
        build: { kind: 'array', block: 'brown_wool', rows: 5, cols: 5 } },
      { say: 'Last stretch: two rows of eleven.',
        prompt: 'Build 2 rows with 11 blocks in each row.',
        hint: 'Eleven in a row, then eleven more behind it.',
        success: 'Eleven and eleven is twenty-two. The field is fenced!',
        build: { kind: 'array', block: 'brown_wool', rows: 2, cols: 11 } },
    ],
    reward: { coins: 60, items: [['brown_wool', 30], ['gray_wool', 16]] },
  },
  {
    id: 'g2_evenodd', subject: 'math', standard: '2.OA.C.3', title: 'Everybody Gets a Partner',
    story: 'The meadow dance needs everyone in pairs. If every single dancer finds a partner, '
      + 'the number is EVEN. If one is left standing on their own, it is ODD. '
      + 'That is the whole secret — nothing else to remember.',
    steps: [
      { say: 'Eight dancers arrive. Pair them up: four pairs.',
        prompt: 'Make 4 groups of 2, with gaps between them.',
        hint: 'Two together, gap, two together, gap — four little pairs.',
        success: 'Everyone has a partner. Eight is EVEN!',
        build: { kind: 'groups', block: 'pink_wool', sizes: [2, 2, 2, 2] } },
      { say: 'Now seven turn up. Pair them and see what happens.',
        prompt: 'Make 3 groups of 2 and 1 group of 1.',
        hint: 'Three pairs, and then one on their own with nobody to dance with.',
        success: 'One dancer left over. Seven is ODD!',
        build: { kind: 'groups', block: 'pink_wool', sizes: [2, 2, 2, 1] } },
      { say: 'Ten arrive after supper.',
        prompt: 'Make 5 groups of 2, with gaps between them.',
        hint: 'Five pairs. Count them: two, four, six, eight, ten.',
        success: 'All paired up. Ten is EVEN — and every number ending in zero is!',
        build: { kind: 'groups', block: 'pink_wool', sizes: [2, 2, 2, 2, 2] } },
      { say: 'Eleven. That is ten and one more.',
        prompt: 'Make 5 groups of 2 and 1 group of 1.',
        hint: 'Five pairs, and one poor dancer left over.',
        success: 'Eleven is ODD. Odd numbers always leave somebody out!',
        build: { kind: 'groups', block: 'pink_wool', sizes: [2, 2, 2, 2, 2, 1] } },
      { say: 'Here is what even really means. Six dancers, split into two equal lines.',
        prompt: 'Build 2 rows with 3 blocks in each row.',
        hint: 'Three in one row, three in the row behind it — exactly the same.',
        success: 'Two equal lines with nothing left over. That is what makes six even!',
        build: { kind: 'array', block: 'pink_wool', rows: 2, cols: 3 } },
    ],
    reward: { coins: 60, items: [['pink_wool', 24], ['magenta_wool', 16]] },
  },
  {
    id: 'g2_array', subject: 'math', standard: '2.OA.C.4', title: 'The Orchard Rows',
    story: 'Old Rowan plants his apple trees in neat rows, and he can always tell you how many '
      + 'without counting a single tree. Rows and columns — the ARRAY — is the trick, '
      + 'and next year you will call it multiplication.',
    steps: [
      { say: 'The little orchard: three rows, four trees in each.',
        prompt: 'Build 3 rows with 4 blocks in each row.',
        hint: 'Four in a row. Then four more behind. Then four more.',
        success: 'Four and four and four is TWELVE. Three rows of four!',
        build: { kind: 'array', block: 'green_wool', rows: 3, cols: 4 } },
      { say: 'Now turn it. Four rows, three in each. Same trees, different way round.',
        prompt: 'Build 4 rows with 3 blocks in each row.',
        hint: 'Three in a row, four times over.',
        success: 'Still twelve! Turning an array does not change how many there are.',
        build: { kind: 'array', block: 'green_wool', rows: 4, cols: 3 } },
      { say: 'The big orchard: four rows of six.',
        prompt: 'Build 4 rows with 6 blocks in each row.',
        hint: 'Six in a row, and four rows of them.',
        success: 'Six, twelve, eighteen, TWENTY-FOUR!',
        build: { kind: 'array', block: 'green_wool', rows: 4, cols: 6 } },
      { say: 'Rowan\'s favourite: a square orchard, four by four.',
        prompt: 'Build 4 rows with 4 blocks in each row.',
        hint: 'Four rows, four in each. Every side the same.',
        success: 'Sixteen — and a perfect square, because the rows and the columns match.',
        build: { kind: 'array', block: 'green_wool', rows: 4, cols: 4 } },
      { say: 'Last one, and it is a big square: five rows of five.',
        prompt: 'Build 5 rows with 5 blocks in each row.',
        hint: 'Five, ten, fifteen, twenty, twenty-five.',
        success: 'Twenty-five trees. Rowan will never count one by one again!',
        build: { kind: 'array', block: 'green_wool', rows: 5, cols: 5 } },
    ],
    reward: { coins: 65, items: [['green_wool', 30], ['lime_wool', 16]] },
  },
  {
    id: 'g2_add2', subject: 'math', standard: '2.NBT.B.5', title: 'Two Barns, One Total',
    story: 'The harvest is in two barns and the meadow needs one number, not two. '
      + 'Add the tens to the tens and the ones to the ones — and if the ones ever make '
      + 'ten of their own, bundle them up. That is the whole of adding big numbers.',
    steps: [
      { say: 'Twenty in one barn, thirteen in the other. Start with the tens: two and one.',
        prompt: 'Make three rows of 10, with gaps between them.',
        hint: 'Two tens from one barn, one ten from the other. Three tens altogether.',
        success: 'Three tens is thirty. Now for the ones.',
        build: { kind: 'groups', block: 'yellow_wool', sizes: [10, 10, 10] } },
      { say: 'The loose ones: none from the first barn, three from the second.',
        prompt: 'Make three rows of 10 and one row of 3.',
        hint: 'The three tens you had, plus a little group of three.',
        success: 'Thirty and three is THIRTY-THREE. Twenty add thirteen!',
        build: { kind: 'groups', block: 'yellow_wool', sizes: [10, 10, 10, 3] } },
      { say: 'Next pair of barns: fourteen and twelve. Tens first — one and one.',
        prompt: 'Make two rows of 10 and two rows of 4 and 2.',
        hint: 'Two bundles of ten. Then a group of four, and a group of two.',
        success: 'Two tens, and four and two loose. Now — can the loose ones make a new bundle?',
        build: { kind: 'groups', block: 'orange_wool', sizes: [10, 10, 4, 2] } },
      { say: 'Four and two is six. Not enough for a new bundle. So the answer is two tens and six.',
        prompt: 'Make two rows of 10 and one row of 6.',
        hint: 'Push the four and the two together into one group of six.',
        success: 'Twenty-six! Fourteen add twelve is twenty-six.',
        build: { kind: 'groups', block: 'orange_wool', sizes: [10, 10, 6] } },
      { say: 'Last pair, and this time the ones DO make a ten. Eighteen and seven — eight and seven is fifteen.',
        prompt: 'Make two rows of 10 and one row of 5.',
        hint: 'One ten from the eighteen, and a new bundle made from the loose ones. Five left over.',
        success: 'Two tens and five: TWENTY-FIVE. You bundled a new ten — that is carrying!',
        build: { kind: 'groups', block: 'orange_wool', sizes: [10, 10, 5] } },
    ],
    reward: { coins: 65, items: [['orange_wool', 24], ['yellow_wool', 24]] },
  },
  {
    id: 'g2_measure', subject: 'math', standard: '2.MD.A.4', title: 'The Longest Ribbon',
    story: 'Three ribbons have come back from the fair and nobody agrees which is longest. '
      + 'Measure them in blocks, line them up, and the argument is over. '
      + 'Then you can say not just WHICH is longer, but by HOW MUCH.',
    steps: [
      { say: 'The blue ribbon first: eight blocks long.',
        prompt: 'Make one unbroken row of exactly 8.',
        hint: 'Eight in a straight line, no gaps.',
        success: 'The blue ribbon is eight blocks.',
        build: { kind: 'groups', block: 'blue_wool', sizes: [8] } },
      { say: 'The red one is longer: twelve.',
        prompt: 'Make one unbroken row of exactly 12.',
        hint: 'Twelve in a line — nearly the whole width of the mat.',
        success: 'Twelve blocks. The red one is the longer of the two.',
        build: { kind: 'groups', block: 'red_wool', sizes: [12] } },
      { say: 'Put them side by side so we can see the difference.',
        prompt: 'Make a row of 12 and a row of 8, with a gap between them.',
        hint: 'Twelve on one row, eight on another.',
        success: 'The red one sticks out by four. Twelve take away eight is FOUR.',
        build: { kind: 'groups', block: 'gray_wool', sizes: [12, 8] } },
      { say: 'Build just the difference — the bit that sticks out.',
        prompt: 'Make one unbroken row of exactly 4.',
        hint: 'Four blocks: the extra length of the red ribbon.',
        success: 'Four blocks of difference. That is what "how much longer" means!',
        build: { kind: 'groups', block: 'gray_wool', sizes: [4] } },
      { say: 'All three ribbons now, standing up as bars so you can compare at a glance: 8, 12 and 5.',
        prompt: 'Build three towers side by side: 5, 7 and 3 tall.',
        hint: 'The mat is only seven tall, so we use a shorter scale — five, seven, three.',
        success: 'Tallest, middle, shortest — all in one look. That is a graph!',
        build: { kind: 'stack', block: 'cyan_wool', heights: [5, 7, 3] } },
    ],
    reward: { coins: 65, items: [['cyan_wool', 20], ['gray_wool', 20]] },
  },
  {
    id: 'g2_graph', subject: 'math', standard: '2.MD.D.10', title: 'The Meadow Survey',
    story: 'Pip asked everybody in the meadow what their favourite fruit is, and now she has '
      + 'a pocketful of tally marks and no idea what they mean. Turn the counts into bars. '
      + 'A graph is a picture of numbers, and it answers questions faster than the numbers do.',
    steps: [
      { say: 'Apples got four votes, plums got two, berries got six.',
        prompt: 'Build three towers side by side: 4, 2 and 6 tall.',
        hint: 'Four blocks, then two, then six, standing next to each other.',
        success: 'Berries win! You could see it before you counted anything.',
        build: { kind: 'stack', block: 'red_wool', heights: [4, 2, 6] } },
      { say: 'Which was the smallest bar? Build just that one on its own.',
        prompt: 'Build ONE tower exactly 2 tall.',
        hint: 'Two blocks. The plums — the shortest bar.',
        success: 'Two votes for plums, the fewest of all.',
        build: { kind: 'tower', block: 'red_wool', h: 2 } },
      { say: 'How many more chose berries than plums? Six take away two.',
        prompt: 'Build ONE tower exactly 4 tall.',
        hint: 'Six take away two. Build the answer as a tower.',
        success: 'Four more people chose berries. Graphs answer "how many more" too!',
        build: { kind: 'tower', block: 'red_wool', h: 4 } },
      { say: 'A second survey: pets. Cats three, dogs five, hens one, goats seven.',
        prompt: 'Build four towers side by side: 3, 5, 1 and 7 tall.',
        hint: 'Three, five, one, seven — each its own stack, side by side.',
        success: 'Goats are the meadow favourite. Nobody is surprised.',
        build: { kind: 'stack', block: 'brown_wool', heights: [3, 5, 1, 7] } },
      { say: 'Last one. Put the same four bars in order, shortest to tallest.',
        prompt: 'Build four towers side by side: 1, 3, 5 and 7 tall.',
        hint: 'One, three, five, seven — smallest on the left.',
        success: 'Sorted! An ordered graph is even easier to read.',
        build: { kind: 'stack', block: 'brown_wool', heights: [1, 3, 5, 7] } },
    ],
    reward: { coins: 70, items: [['red_wool', 24], ['brown_wool', 24]] },
  },
  {
    id: 'g2_frac', subject: 'math', standard: '2.G.A.3', title: 'Fair Shares at the Fair',
    story: 'The fair sells one enormous gingerbread and cuts it to order. '
      + 'A HALF means two equal pieces, a THIRD means three, a QUARTER means four. '
      + 'The bigger the bottom number, the SMALLER each piece — which surprises everybody.',
    steps: [
      { say: 'Two friends. Cut the gingerbread in two and take one piece.',
        prompt: 'Make a row of 2 blocks with exactly 1 of them orange.',
        hint: 'Two blocks in a row. One orange, one white.',
        success: 'One out of two — one HALF. The biggest share you can get without taking it all!',
        build: { kind: 'fraction', whole: 'white_wool', part: 'orange_wool', den: 2, num: 1 } },
      { say: 'Three friends now. Same cake, three fair pieces.',
        prompt: 'Make a row of 3 blocks with exactly 1 of them orange.',
        hint: 'Three in a row, one of them orange.',
        success: 'One out of three — a THIRD. Smaller than a half!',
        build: { kind: 'fraction', whole: 'white_wool', part: 'orange_wool', den: 3, num: 1 } },
      { say: 'Four friends. You can guess what happens to your piece.',
        prompt: 'Make a row of 4 blocks with exactly 1 of them orange.',
        hint: 'Four in a row, one orange.',
        success: 'One out of four — a QUARTER. More friends, smaller piece!',
        build: { kind: 'fraction', whole: 'white_wool', part: 'orange_wool', den: 4, num: 1 } },
      { say: 'Now take THREE of the four quarters.',
        prompt: 'Make a row of 4 blocks with exactly 3 of them orange.',
        hint: 'Four in a row, three of them orange, one white.',
        success: 'Three quarters. Nearly the whole thing!',
        build: { kind: 'fraction', whole: 'white_wool', part: 'orange_wool', den: 4, num: 3 } },
      { say: 'Last. Two thirds of a cake cut into three.',
        prompt: 'Make a row of 3 blocks with exactly 2 of them orange.',
        hint: 'Three in a row, two orange.',
        success: 'Two thirds. The top number counts your pieces, the bottom says how many the cake was cut into!',
        build: { kind: 'fraction', whole: 'white_wool', part: 'orange_wool', den: 3, num: 2 } },
    ],
    reward: { coins: 70, items: [['orange_wool', 20], ['white_wool', 20]] },
  },
  {
    id: 'g2_vowel', subject: 'reading', standard: 'RF.2.3.B', title: 'The Silent E',
    story: 'There is a piece of magic in the Word Wood: a silent E on the end of a word '
      + 'reaches back over the middle letter and makes it say its own NAME. '
      + 'CAP becomes CAPE. Same letters, one extra, whole new word.',
    steps: [
      { say: 'Start with the plain word. C, A, P.',
        prompt: 'Spell CAP.',
        hint: 'Three sounds: c, a, p.',
        success: 'CAP — a short A sound. Now watch what the magic E does.',
        build: { kind: 'word', text: 'CAP' } },
      { say: 'Add the silent E on the end.',
        prompt: 'Spell CAPE.',
        hint: 'C, A, P and then E. The E says nothing at all — it just changes the A.',
        success: 'CAPE! The A now says its own name. That is the silent E at work.',
        build: { kind: 'word', text: 'CAPE' } },
      { say: 'Try another. Start with PIN.',
        prompt: 'Spell PIN.',
        hint: 'P, I, N.',
        success: 'PIN — a short I.',
        build: { kind: 'word', text: 'PIN' } },
      { say: 'Now let the E do its work.',
        prompt: 'Spell PINE.',
        hint: 'P, I, N, E. Like the pine tree by the stream.',
        success: 'PINE! Same three letters, one silent E, completely different word.',
        build: { kind: 'word', text: 'PINE' } },
      { say: 'Three more of the magic pairs, all at once: HOP becomes HOPE, TUB becomes TUBE.',
        prompt: 'Spell HOPE, TUBE and CUBE — one on each row.',
        hint: 'Each one ends with the silent E. H-O-P-E. T-U-B-E. C-U-B-E.',
        success: 'HOPE, TUBE, CUBE. You have the silent E rule for life now!',
        build: { kind: 'words', list: ['HOPE', 'TUBE', 'CUBE'] } },
    ],
    reward: { coins: 70, items: [['letter_e', 6], ['letter_a', 4], ['letter_i', 4]] },
  },
  {
    id: 'g2_compound', subject: 'reading', standard: 'L.2.4.D', title: 'Two Words in a Coat',
    story: 'Some words are really two words wearing one coat. SUN and SET walk out together '
      + 'as SUNSET. Once you learn to look for the join, long words stop being frightening — '
      + 'you can just read the two little ones.',
    steps: [
      { say: 'Here is the first half of the word. S, U, N.',
        prompt: 'Spell SUN.',
        hint: 'S, U, N. You know this one already!',
        success: 'SUN — one little word.',
        build: { kind: 'word', text: 'SUN' } },
      { say: 'And the second half: what the sun does in the evening. S, E, T.',
        prompt: 'Spell SET.',
        hint: 'S, E, T.',
        success: 'SET — another little word.',
        build: { kind: 'word', text: 'SET' } },
      { say: 'Now put them into one coat.',
        prompt: 'Spell SUNSET.',
        hint: 'S-U-N and then S-E-T, all in one unbroken row.',
        success: 'SUNSET! A long word made of two short ones you already knew.',
        build: { kind: 'word', text: 'SUNSET' } },
      { say: 'Try a longer one. RAIN and BOW.',
        prompt: 'Spell RAINBOW.',
        hint: 'R-A-I-N, then B-O-W. Seven letters, but only two words.',
        success: 'RAINBOW. Look for the join and long words fall apart in your hands.',
        build: { kind: 'word', text: 'RAINBOW' } },
      { say: 'Last three, all in one go: CUPCAKE, SNOWMAN and BEDTIME.',
        prompt: 'Spell CUPCAKE, SNOWMAN and BEDTIME — one on each row.',
        hint: 'CUP and CAKE. SNOW and MAN. BED and TIME. Find the join in each one.',
        success: 'Three long words, six little ones. You can read anything now!',
        build: { kind: 'words', list: ['CUPCAKE', 'SNOWMAN', 'BEDTIME'] } },
    ],
    reward: { coins: 75, items: [['hearth_loaf', 3], ['travel_biscuit', 3]] },
  },
];
