// Grade 5 — volume as a thing you can hold, decimals, multiplying by a
// fraction, the order of operations, plotting points on a grid, powers of ten,
// and the difference between what a sentence says and what it means.
export const GRADE_5 = [
  {
    id: 'g5_volume', subject: 'math', standard: '5.MD.C.3', title: 'Stacking the Woodshed',
    story: 'The woodshed is full and Rowan wants to know how many blocks of wood are in it '
      + 'without unstacking the lot. Volume is length times width times HEIGHT — '
      + 'the first measurement that needs all three, and the first you have to build upwards.',
    steps: [
      { say: 'Start with the floor of the stack: three long, two deep, one high.',
        prompt: 'Build a solid block 3 across, 2 back and 1 tall.',
        hint: 'Three in a row, two rows — one layer only.',
        success: 'Six blocks in one layer. That is the area of the floor.',
        build: { kind: 'box', block: 'brown_wool', w: 3, d: 2, h: 1 } },
      { say: 'Now stack a second layer on top of the whole thing.',
        prompt: 'Build a solid block 3 across, 2 back and 2 tall.',
        hint: 'Same floor, and then another complete layer sitting on it.',
        success: 'Twelve. Six in a layer, two layers — volume is area times height!',
        build: { kind: 'box', block: 'brown_wool', w: 3, d: 2, h: 2 } },
      { say: 'A third layer.',
        prompt: 'Build a solid block 3 across, 2 back and 3 tall.',
        hint: 'Three complete layers, each one six blocks.',
        success: 'Eighteen. Three times two times three.',
        build: { kind: 'box', block: 'brown_wool', w: 3, d: 2, h: 3 } },
      { say: 'The proper woodshed: four long, three deep, two high.',
        prompt: 'Build a solid block 4 across, 3 back and 2 tall.',
        hint: 'A floor of four by three — twelve — and then a second layer on top.',
        success: 'Twenty-four blocks of wood. Rowan is very pleased.',
        build: { kind: 'box', block: 'brown_wool', w: 4, d: 3, h: 2 } },
      { say: 'And the big shed at the mill: five long, three deep, three high.',
        prompt: 'Build a solid block 5 across, 3 back and 3 tall.',
        hint: 'Fifteen in a layer, three layers.',
        success: 'Forty-five! You measured a whole shed without unstacking a single log.',
        build: { kind: 'box', block: 'brown_wool', w: 5, d: 3, h: 3 } },
    ],
    reward: { coins: 110, items: [['brown_wool', 50]] },
  },
  {
    id: 'g5_volume2', subject: 'math', standard: '5.MD.C.5', title: 'Two Crates, One Answer',
    story: 'The carter has two crates of completely different shapes and swears they hold the same. '
      + 'The only way to settle it is to fill them. Same volume, different shape — '
      + 'it happens more often than you would think.',
    steps: [
      { say: 'The tall crate: two long, two deep, three high.',
        prompt: 'Build a solid block 2 across, 2 back and 3 tall.',
        hint: 'A little square floor of four, stacked three high.',
        success: 'Twelve. Two times two times three.',
        build: { kind: 'box', block: 'gray_wool', w: 2, d: 2, h: 3 } },
      { say: 'The flat crate: six long, two deep, one high.',
        prompt: 'Build a solid block 6 across, 2 back and 1 tall.',
        hint: 'Six in a row, two rows, one layer.',
        success: 'Twelve again! Completely different shape, exactly the same volume.',
        build: { kind: 'box', block: 'gray_wool', w: 6, d: 2, h: 1 } },
      { say: 'A third crate that also holds twelve: three long, two deep, two high.',
        prompt: 'Build a solid block 3 across, 2 back and 2 tall.',
        hint: 'Six in a layer, two layers.',
        success: 'Twelve for the third time. Three shapes, one volume!',
        build: { kind: 'box', block: 'gray_wool', w: 3, d: 2, h: 2 } },
      { say: 'Now a bigger one: twenty-four. Four long, three deep, two high.',
        prompt: 'Build a solid block 4 across, 3 back and 2 tall.',
        hint: 'Twelve in a layer, two layers.',
        success: 'Twenty-four.',
        build: { kind: 'box', block: 'cyan_wool', w: 4, d: 3, h: 2 } },
      { say: 'And the same twenty-four, laid out flat instead.',
        prompt: 'Build a solid block 6 across, 4 back and 1 tall.',
        hint: 'Six by four, one layer deep.',
        success: 'Twenty-four again. The crate that fits through the door is the one to use!',
        build: { kind: 'box', block: 'cyan_wool', w: 6, d: 4, h: 1 } },
    ],
    reward: { coins: 110, items: [['gray_wool', 40], ['cyan_wool', 40]] },
  },
  {
    id: 'g5_decimal', subject: 'math', standard: '5.NBT.A.3', title: 'The Assayer\'s Scale',
    story: 'The assayer weighs ore to a tenth of a bar, and the whole trade depends on knowing '
      + 'which of two decimals is bigger. Nought point seven and nought point three-five — '
      + 'the longer number is not always the larger one, and that catches everybody out.',
    steps: [
      { say: 'Weigh out four tenths of a bar.',
        prompt: 'Make a row of 10 blocks with exactly 4 of them yellow.',
        hint: 'Ten in a row — one whole bar. Four of them yellow.',
        success: 'Four tenths. Nought point four.',
        build: { kind: 'fraction', whole: 'white_wool', part: 'yellow_wool', den: 10, num: 4 } },
      { say: 'Now six tenths, so we can compare.',
        prompt: 'Make a row of 10 blocks with exactly 6 of them yellow.',
        hint: 'Six yellow this time.',
        success: 'Six tenths is bigger than four tenths — nought point six beats nought point four.',
        build: { kind: 'fraction', whole: 'white_wool', part: 'yellow_wool', den: 10, num: 6 } },
      { say: 'Compare them standing up, so the difference is obvious: four against six.',
        prompt: 'Build a tower 4 tall on the LEFT and a tower 6 tall on the RIGHT.',
        hint: 'Four blocks on one side of the wooden line, six on the other.',
        success: 'Six is taller. Comparing decimals is just comparing tenths!',
        build: { kind: 'compare', block: 'yellow_wool', left: 4, right: 6 } },
      { say: 'A tenth is ten times bigger than a hundredth. Show ten tenths — one whole.',
        prompt: 'Make a row of 10 blocks with all 10 of them yellow.',
        hint: 'Every one of the ten, yellow.',
        success: 'Ten tenths is ONE. That is why nought point nine is nearly a whole bar.',
        build: { kind: 'fraction', whole: 'white_wool', part: 'yellow_wool', den: 10, num: 10 } },
      { say: 'Last weigh-in: two tenths against seven tenths.',
        prompt: 'Build a tower 2 tall on the LEFT and a tower 7 tall on the RIGHT.',
        hint: 'Two on one side of the line, seven on the other.',
        success: 'Nought point seven is far heavier. The assayer trusts you now!',
        build: { kind: 'compare', block: 'yellow_wool', left: 2, right: 7 } },
    ],
    reward: { coins: 115, items: [['yellow_wool', 40], ['white_wool', 40]] },
  },
  {
    id: 'g5_fracmult', subject: 'math', standard: '5.NF.B.4', title: 'Three Lots of Two Thirds',
    story: 'Multiplying by a fraction sounds frightening until you say it out loud: '
      + '"three lots of two thirds". Lots OF something — that is all times means. '
      + 'Build the lots and count what you have.',
    steps: [
      { say: 'One lot of two thirds first. A row of three, two of them coloured.',
        prompt: 'Make a row of 3 blocks with exactly 2 of them lime.',
        hint: 'Three in a row, two lime.',
        success: 'Two thirds. Now we need three lots of that.',
        build: { kind: 'fraction', whole: 'white_wool', part: 'lime_wool', den: 3, num: 2 } },
      { say: 'Three lots of two blocks each.',
        prompt: 'Make 3 groups of 2, with gaps between them.',
        hint: 'Two together, a gap, two more, a gap, two more.',
        success: 'Six thirds altogether. Three lots of two thirds is six thirds!',
        build: { kind: 'groups', block: 'lime_wool', sizes: [2, 2, 2] } },
      { say: 'Six thirds is more than one whole. How many whole rows of three does it make?',
        prompt: 'Build 2 rows with 3 blocks in each row.',
        hint: 'Six blocks, arranged as two complete rows of three.',
        success: 'Six thirds is exactly TWO WHOLES. Three times two thirds equals two!',
        build: { kind: 'array', block: 'lime_wool', rows: 2, cols: 3 } },
      { say: 'Try another. Four lots of three quarters. First, three quarters.',
        prompt: 'Make a row of 4 blocks with exactly 3 of them lime.',
        hint: 'Four in a row, three of them lime.',
        success: 'Three quarters. Now four lots of that — that is twelve quarters.',
        build: { kind: 'fraction', whole: 'white_wool', part: 'lime_wool', den: 4, num: 3 } },
      { say: 'Twelve quarters, arranged as whole rows of four.',
        prompt: 'Build 3 rows with 4 blocks in each row.',
        hint: 'Twelve blocks in rows of four. How many complete rows?',
        success: 'Three whole ones. Four times three quarters is THREE. Nothing frightening about it!',
        build: { kind: 'array', block: 'lime_wool', rows: 3, cols: 4 } },
    ],
    reward: { coins: 115, items: [['lime_wool', 40], ['white_wool', 30]] },
  },
  {
    id: 'g5_pemdas', subject: 'math', standard: '5.OA.A.1', title: 'The Order of Operations',
    story: 'Two apprentices read the same order — "two and three lots of four" — and made '
      + 'completely different things. One made twenty. One made fourteen. '
      + 'Only one of them was right, because sums have an ORDER and you cannot just work left to right.',
    steps: [
      { say: 'The wrong way first, so you can see the trap. Add two and three, then take four lots of it.',
        prompt: 'Build 5 rows with 4 blocks in each row.',
        hint: 'Two plus three is five. Five rows of four.',
        success: 'Twenty. That is what the first apprentice built — and it is WRONG.',
        build: { kind: 'array', block: 'red_wool', rows: 5, cols: 4 } },
      { say: 'Now the right way. The times comes FIRST: three lots of four.',
        prompt: 'Build 3 rows with 4 blocks in each row.',
        hint: 'Three rows of four. Do the multiplying before the adding.',
        success: 'Twelve. Multiplying always goes before adding.',
        build: { kind: 'array', block: 'green_wool', rows: 3, cols: 4 } },
      { say: 'And THEN add the two.',
        prompt: 'Make a group of 12 and a group of 2, with a gap between them.',
        hint: 'The twelve you worked out, and then the two on its own.',
        success: 'Fourteen! Two plus three times four is fourteen, not twenty.',
        build: { kind: 'groups', block: 'green_wool', sizes: [12, 2] } },
      { say: 'Brackets beat everything. If it says brackets round the two and three, you DO add first.',
        prompt: 'Build 5 rows with 4 blocks in each row.',
        hint: 'Brackets first: two plus three is five. Then five rows of four.',
        success: 'Twenty — and this time it is right, because the brackets said so.',
        build: { kind: 'array', block: 'red_wool', rows: 5, cols: 4 } },
      { say: 'Last one. Ten take away two lots of three.',
        prompt: 'Place 10 purple blocks, then break 6 of them.',
        hint: 'Two lots of three is six. Build ten first, then take six away.',
        success: 'Four. Times before take-away, every time. The apprentices are taking notes!',
        build: { kind: 'subtract', block: 'purple_wool', from: 10, take: 6 } },
    ],
    reward: { coins: 115, items: [['red_wool', 30], ['green_wool', 30], ['purple_wool', 20]] },
  },
  {
    id: 'g5_coord', subject: 'math', standard: '5.G.A.1', title: 'The Treasure Map',
    story: 'A map is useless without a way of saying WHERE. So we count from one corner: '
      + 'first how far ACROSS, then how far BACK. Across before back, always — '
      + 'get them the wrong way round and you dig in the wrong field.',
    steps: [
      { say: 'The first mark: three across, nothing back. Right on the front edge.',
        prompt: 'Put a single block 3 squares across from the left corner, on the front row.',
        hint: 'Count three along the front row from the left-hand end, and place one block.',
        success: 'That is the point three, nought. Across first!',
        build: { kind: 'cells', block: 'red_wool', at: [[3, 0, 0]] } },
      { say: 'Now three across and two back.',
        prompt: 'Put a single block 3 across and 2 rows back.',
        hint: 'Three along, then two rows away from you. One block only.',
        success: 'Three, two. Same "across" as before, but two rows further back — a different place entirely.',
        build: { kind: 'cells', block: 'red_wool', at: [[3, 0, 2]] } },
      { say: 'Prove the order matters. Mark two across, three back — and three across, two back.',
        prompt: 'Put one block at 2 across 3 back, and another at 3 across 2 back.',
        hint: 'Two of them. Count carefully: across first, then back.',
        success: 'Two different spots! Three-two and two-three are not the same place.',
        build: { kind: 'cells', block: 'red_wool', at: [[2, 0, 3], [3, 0, 2]] } },
      { say: 'Plot the three corners of the treasure field: nought-nought, four-nought, and nought-three.',
        prompt: 'Put blocks at 0 across 0 back, 4 across 0 back, and 0 across 3 back.',
        hint: 'One in the very corner, one four along the front, one three rows back on the left edge.',
        success: 'Three corners plotted. The treasure is in the middle of them!',
        build: { kind: 'cells', block: 'yellow_wool', at: [[0, 0, 0], [4, 0, 0], [0, 0, 3]] } },
      { say: 'Last: a straight line of points where "back" is always one more than "across".',
        prompt: 'Put blocks at 0-across-0-back, 1-across-1-back, 2-across-2-back and 3-across-3-back.',
        hint: 'A diagonal: each one is one further along AND one further back.',
        success: 'A diagonal line — and every point on it follows the same rule. That is a graph of a rule!',
        build: { kind: 'cells', block: 'yellow_wool', at: [[0, 0, 0], [1, 0, 1], [2, 0, 2], [3, 0, 3]] } },
    ],
    reward: { coins: 120, items: [['red_wool', 20], ['yellow_wool', 20]] },
  },
  {
    id: 'g5_powers', subject: 'math', standard: '5.NBT.A.2', title: 'Powers of Ten',
    story: 'Every time you multiply by ten, the number grows a whole new column and the digits '
      + 'all shuffle one place to the left. That is why big numbers are so easy to write '
      + 'and so hard to imagine. Today you build the first few.',
    steps: [
      { say: 'One. A single block.',
        prompt: 'Build ONE tower exactly 1 tall.',
        hint: 'Just one block.',
        success: 'One. Ten to the power of nothing at all!',
        build: { kind: 'tower', block: 'white_wool', h: 1 } },
      { say: 'Ten. One row.',
        prompt: 'Build 1 row with 10 blocks in it.',
        hint: 'Ten in a straight line.',
        success: 'Ten — ten times bigger, and it took a whole row.',
        build: { kind: 'array', block: 'white_wool', rows: 1, cols: 10 } },
      { say: 'Ten tens would be a hundred. We only have five rows, so build half of it: five tens.',
        prompt: 'Build 5 rows with 10 blocks in each row.',
        hint: 'Ten in a row, five rows — the mat is nearly full.',
        success: 'Fifty. And a hundred would need TWICE this whole mat. That is how fast tens grow!',
        build: { kind: 'array', block: 'white_wool', rows: 5, cols: 10 } },
      { say: 'Now the doubling powers, which grow nearly as fast. One, two, four.',
        prompt: 'Build three towers side by side: 1, 2 and 4 tall.',
        hint: 'One, then double it, then double again.',
        success: 'One, two, four — each one twice the last.',
        build: { kind: 'stack', block: 'light_blue_wool', heights: [1, 2, 4] } },
      { say: 'Carry on doubling as far as the mat allows: one, two, four — and the next would be eight.',
        prompt: 'Build four towers side by side: 1, 2, 4 and 7 tall.',
        hint: 'The fourth would be eight, but the ceiling is seven — so build seven and remember it is short by one.',
        success: 'Doubling runs out of room in four steps. Powers grow faster than anything!',
        build: { kind: 'stack', block: 'light_blue_wool', heights: [1, 2, 4, 7] } },
    ],
    reward: { coins: 120, items: [['white_wool', 50], ['light_blue_wool', 20]] },
  },
  {
    id: 'g5_lineplot', subject: 'math', standard: '5.MD.B.2', title: 'The Fisher\'s Tally',
    story: 'Five fishers, five different catches, and an argument about what a "typical" day '
      + 'looks like. There are three answers to that — the middle one, the commonest one, '
      + 'and the fair-shares one — and today you build all three.',
    steps: [
      { say: 'The five catches: three, seven, one, five and four.',
        prompt: 'Build five towers side by side: 3, 7, 1, 5 and 4 tall.',
        hint: 'Five stacks in a row: three, seven, one, five, four.',
        success: 'Five days of fishing, side by side.',
        build: { kind: 'stack', block: 'blue_wool', heights: [3, 7, 1, 5, 4] } },
      { say: 'Put them in order. The MEDIAN is whichever one ends up in the middle.',
        prompt: 'Build five towers side by side: 1, 3, 4, 5 and 7 tall.',
        hint: 'Smallest to biggest: one, three, four, five, seven.',
        success: 'The middle tower is four. The median catch is FOUR.',
        build: { kind: 'stack', block: 'blue_wool', heights: [1, 3, 4, 5, 7] } },
      { say: 'The MEAN is what everyone would get if they shared equally. Three, seven, one, five and four is twenty — shared five ways.',
        prompt: 'Build five towers side by side, all exactly 4 tall.',
        hint: 'Twenty fish shared between five fishers is four each. Five equal towers of four.',
        success: 'All level at four. That is the MEAN — everybody the same.',
        build: { kind: 'stack', block: 'blue_wool', heights: [4, 4, 4, 4, 4] } },
      { say: 'The RANGE is the biggest take away the smallest: seven take away one.',
        prompt: 'Build ONE tower exactly 6 tall.',
        hint: 'Seven minus one is six.',
        success: 'A range of six. That is a very uneven week of fishing!',
        build: { kind: 'tower', block: 'blue_wool', h: 6 } },
      { say: 'A new week, and this one has a MODE — a number that turns up more than once.',
        prompt: 'Build five towers side by side: 3, 3, 5, 3 and 6 tall.',
        hint: 'Three appears three times. Build them in that order.',
        success: 'Three is the MODE — the commonest catch. Median, mean, mode and range: you have the lot!',
        build: { kind: 'stack', block: 'blue_wool', heights: [3, 3, 5, 3, 6] } },
    ],
    reward: { coins: 120, items: [['blue_wool', 40], ['cyan_wool', 24]] },
  },
  {
    id: 'g5_prefix', subject: 'reading', standard: 'L.5.4.B', title: 'The Front of the Word',
    story: 'A prefix is a little word bolted onto the front, and it can turn a word '
      + 'completely inside out. UN means not. RE means again. PRE means before. '
      + 'Three syllables of knowledge that unlock a thousand words.',
    steps: [
      { say: 'Start with the plain word. What Rowan did to the boat.',
        prompt: 'Spell PACK.',
        hint: 'P, A, C, K.',
        success: 'PACK.',
        build: { kind: 'word', text: 'PACK' } },
      { say: 'Now bolt UN on the front. UN means "not" — or "the opposite of".',
        prompt: 'Spell UNPACK.',
        hint: 'U-N and then P-A-C-K.',
        success: 'UNPACK — the opposite of packing. Two letters flipped the whole meaning!',
        build: { kind: 'word', text: 'UNPACK' } },
      { say: 'RE means "again". Try it on the same word.',
        prompt: 'Spell REPACK.',
        hint: 'R-E and then P-A-C-K.',
        success: 'REPACK — pack it again. You have never seen that word before and you knew it instantly.',
        build: { kind: 'word', text: 'REPACK' } },
      { say: 'PRE means "before". What do you do to a field before you plant it?',
        prompt: 'Spell PREHEAT.',
        hint: 'P-R-E and then H-E-A-T. Heat it beforehand.',
        success: 'PREHEAT — heat it before. Prefixes are little machines for making words.',
        build: { kind: 'word', text: 'PREHEAT' } },
      { say: 'Three at once: UNDO, REDO and UNFAIR.',
        prompt: 'Spell UNDO, REDO and UNFAIR — one on each row.',
        hint: 'UN plus DO. RE plus DO. UN plus FAIR.',
        success: 'Not-do, do-again, not-fair. Three prefixes, three brand new words!',
        build: { kind: 'words', list: ['UNDO', 'REDO', 'UNFAIR'] } },
    ],
    reward: { coins: 120, items: [['letter_u', 4], ['letter_n', 4], ['letter_r', 4], ['letter_e', 4]] },
  },
  {
    id: 'g5_figure', subject: 'reading', standard: 'L.5.5.A', title: 'It Does Not Mean What It Says',
    story: 'When Maren says it is "raining cats and dogs", no animals are falling. '
      + 'When Pip says the stream "sings", it has no voice. Writers say one thing and mean another '
      + 'on purpose — and once you can spot it, stories get twice as good.',
    steps: [
      { say: 'A SIMILE says one thing is LIKE another. "As quiet as a mouse." Spell the little word that does the work.',
        prompt: 'Spell LIKE.',
        hint: 'L, I, K, E.',
        success: 'LIKE — the word that marks a simile. "As" does the same job.',
        build: { kind: 'word', text: 'LIKE' } },
      { say: 'A METAPHOR is braver: it says one thing IS another. "The stream is a ribbon."',
        prompt: 'Spell METAPHOR.',
        hint: 'M-E-T-A-P-H-O-R. Eight letters. Say it in pieces: MET-A-PHOR.',
        success: 'METAPHOR. No "like" at all — it just says it IS.',
        build: { kind: 'word', text: 'METAPHOR' } },
      { say: 'When something that is not alive is given a life of its own, that is PERSONIFICATION. The stream SINGS.',
        prompt: 'Spell SINGS.',
        hint: 'S-I-N-G-S. Streams cannot really sing.',
        success: 'SINGS. The stream is doing something only a person can do — that is the trick.',
        build: { kind: 'word', text: 'SINGS' } },
      { say: 'An IDIOM means something completely different from its words. "Break a leg" means good luck.',
        prompt: 'Spell IDIOM.',
        hint: 'I-D-I-O-M. Five letters.',
        success: 'IDIOM. If you translated it word by word into another language, nobody would understand it!',
        build: { kind: 'word', text: 'IDIOM' } },
      { say: 'The three you have met, all together.',
        prompt: 'Spell SIMILE, IDIOM and METAPHOR — one on each row.',
        hint: 'S-I-M-I-L-E. I-D-I-O-M. M-E-T-A-P-H-O-R.',
        success: 'Simile, idiom, metaphor. You will spot them in every book you open now!',
        build: { kind: 'words', list: ['SIMILE', 'IDIOM', 'METAPHOR'] } },
    ],
    reward: { coins: 130, items: [['hearth_loaf', 4], ['travel_biscuit', 4]] },
  },
];
