// GENERATED by tools/gen-mobpack.mjs — do not edit by hand.
// Blockbench models from assets/mobs/, converted to mob defs (parts + UV
// islands into each model's own embedded texture). Empty until models are dropped in.
export const MOB_MODELS = {};
