// Runtime mob-override store for the in-game Admin / Debug panel.
//
// Player-authored tweaks (which mobs spawn, how densely, in which biomes, and
// what they drop) live here, layered on top of the immutable ENEMY_TYPES
// registry in enemies.js. Persisted to localStorage under 'emberveil.mobconfig'
// and read LIVE by worldgen spawning (js/world/world.js) and combat drops
// (combat.js / combatrs.js). Node-safe: with no localStorage it starts empty.
//
// Override shape (all keys optional), per mob type:
//   { active: bool, rate: 0..4, biomes: string[]|null, drops: [{item,qty:[min,max],chance}] }
import { ENEMY_TYPES } from './enemies.js';
import { MOB_DEFAULTS } from './mobconfig-defaults.js';

export const MOBCONFIG_KEY = 'emberveil.mobconfig';

function loadOverrides() {
  try {
    if (typeof localStorage === 'undefined') return {};
    const raw = localStorage.getItem(MOBCONFIG_KEY);
    const parsed = raw ? JSON.parse(raw) : {};
    return parsed && typeof parsed === 'object' ? parsed : {};
  } catch {
    return {};
  }
}

// Loaded once at import; mutated in place by setMobConfig/resetMobConfig so the
// exported binding is always the live store every consumer reads through.
export const MOB_OVERRIDES = loadOverrides();

// Read precedence for every setting: a player's own localStorage override wins,
// then the baked game defaults (mobconfig-defaults.js, shipped for everyone),
// then the hard-coded fallback. So "Save as game defaults" changes what every
// player sees while a local tweak still overrides it, and "Reset to default"
// falls back to whatever is baked.
// Native mobs default ON; imported mobs (imported:true) default OFF.
export function mobActive(type) {
  const a = MOB_OVERRIDES[type]?.active ?? MOB_DEFAULTS[type]?.active;
  return a ?? (ENEMY_TYPES[type]?.imported ? false : true);
}

// Density multiplier applied to the mob's per-block spawn chance. 1 = default.
export function mobRate(type) {
  return MOB_OVERRIDES[type]?.rate ?? MOB_DEFAULTS[type]?.rate ?? 1;
}

// null = spawn wherever it already spawns / everywhere it's declared.
// A non-null array of biome KEYS restricts (or, for added mobs, steers) spawns.
export function mobBiomes(type) {
  return MOB_OVERRIDES[type]?.biomes ?? MOB_DEFAULTS[type]?.biomes ?? null;
}

// The effective drop table for a defeated mob: an override if present, else the
// baked default, else the registry default. Same shape as ENEMY_TYPES.drops.
export function mobDropsFor(type) {
  return MOB_OVERRIDES[type]?.drops ?? MOB_DEFAULTS[type]?.drops ?? (ENEMY_TYPES[type]?.drops ?? []);
}

// Merge a partial patch into a mob's override, creating the entry if needed.
export function setMobConfig(type, patch) {
  const cur = MOB_OVERRIDES[type] || (MOB_OVERRIDES[type] = {});
  Object.assign(cur, patch);
  return cur;
}

// Drop all overrides for a mob (back to registry defaults).
export function resetMobConfig(type) {
  delete MOB_OVERRIDES[type];
}

// Persist the whole override store. No-op when localStorage is unavailable.
export function saveMobConfig() {
  try {
    if (typeof localStorage === 'undefined') return;
    localStorage.setItem(MOBCONFIG_KEY, JSON.stringify(MOB_OVERRIDES));
  } catch {
    /* private mode / quota — keep running with in-memory config */
  }
}

// Sorted list of every registered mob type (so mobs added by other modules at
// runtime appear in the panel automatically).
export function allMobTypes() {
  return Object.keys(ENEMY_TYPES).sort();
}

// Bake the current effective config (baked defaults overlaid by the player's own
// overrides) into the exact source text of js/game/mobconfig-defaults.js, ready
// to commit so every player gets it. Returns the file contents as a string.
export function exportMobDefaults() {
  const merged = {};
  for (const type of [...new Set([...Object.keys(MOB_DEFAULTS), ...Object.keys(MOB_OVERRIDES)])].sort()) {
    const entry = { ...MOB_DEFAULTS[type], ...MOB_OVERRIDES[type] };
    if (Object.keys(entry).length) merged[type] = entry;
  }
  const body = JSON.stringify(merged, null, 2);
  return '// Baked mob-config defaults, shipped with the build so every player gets them.\n'
    + '// Generated by the Admin/Debug panel\'s "Save as game defaults" export, then\n'
    + '// committed by hand. A player\'s own localStorage overrides still win over these,\n'
    + '// and "Reset to default" on a mob falls back to whatever is baked here.\n'
    + '// Same override shape as js/game/mobconfig.js:\n'
    + '//   { active, rate, biomes: string[]|null, drops: [{item,qty:[min,max],chance}] }\n'
    + `export const MOB_DEFAULTS = ${body};\n`;
}
