#!/usr/bin/env node
// Bake a converted schematic JSON (tools/import-schematic.mjs output) into a
// source module the game bundles as a starter structure. Normalizes the build so
// its minimum corner is (0,0,0), palette-compresses the block names, and writes
// js/world/starter-manor.js.
//
//   node tools/bake-manor.mjs assets/schematics/z7_recolored.json js/world/starter-manor.js
import fs from 'node:fs';

const [inPath, outPath] = process.argv.slice(2);
if (!inPath || !outPath) { console.error('usage: node tools/bake-manor.mjs <in.json> <out.js>'); process.exit(1); }

const data = JSON.parse(fs.readFileSync(inPath, 'utf8'));
const cells = data.cells;
let minx = Infinity, miny = Infinity, minz = Infinity, maxx = -Infinity, maxy = -Infinity, maxz = -Infinity;
for (const c of cells) {
  minx = Math.min(minx, c.x); maxx = Math.max(maxx, c.x);
  miny = Math.min(miny, c.y); maxy = Math.max(maxy, c.y);
  minz = Math.min(minz, c.z); maxz = Math.max(maxz, c.z);
}
// palette: block name → index, ordered by frequency (smaller indices for common blocks)
const freq = new Map();
for (const c of cells) freq.set(c.block, (freq.get(c.block) || 0) + 1);
const palette = [...freq.entries()].sort((a, b) => b[1] - a[1]).map(([name]) => name);
const pIndex = new Map(palette.map((n, i) => [n, i]));

// flat [x,y,z,paletteIndex,facing] normalized to origin (facing 255 = none)
const flat = [];
for (const c of cells) flat.push(c.x - minx, c.y - miny, c.z - minz, pIndex.get(c.block), c.f ?? 255);

const w = maxx - minx + 1, h = maxy - miny + 1, l = maxz - minz + 1;
const module = `// AUTO-GENERATED by tools/bake-manor.mjs — do not edit by hand.
// Source: ${inPath.split('/').pop()} (converted from a Minecraft schematic).
// A starter structure normalized to a (0,0,0) minimum corner. Footprint ${w}×${l},
// height ${h}. cells is a flat [x,y,z,paletteIndex,facing] run (stride 5, facing
// 255 = none); resolve the block name through PALETTE. Placed by structures.js.
export const MANOR = {
  w: ${w}, h: ${h}, l: ${l}, count: ${cells.length}, stride: 5,
  palette: ${JSON.stringify(palette)},
  cells: ${JSON.stringify(flat)},
};
`;
fs.writeFileSync(outPath, module);
console.log(`baked ${cells.length} cells → ${outPath}  (${w}×${h}×${l}, palette ${palette.length}, ${(module.length / 1024).toFixed(0)} KB)`);
