// Embed the 32x32 art pack (assets/textures/*.png) into a single-file module
// js/gfx/texpack.js as base64 data URIs, keyed by the engine's tile / item names.
// The atlas paints procedurally first, then overlays these real textures.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { tileNames } from '../js/gfx/textures.js';
import { ITEMS } from '../js/game/items.js';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SRC = path.join(ROOT, 'assets/textures');
const OUT = path.join(ROOT, 'js/gfx/texpack.js');

const tileSet = new Set(tileNames());
const itemSet = new Set(Object.keys(ITEMS));

// Per-face station tiles the pack ships that don't yet exist as engine tiles —
// Phase B wires blocks to them. Kept under their own names so the art is ready.
const NEW_FACE_TILES = new Set([
  'furnace_side', 'furnace_top', 'grindstone', 'grindstone_side', 'grindstone_top',
  'loom_side', 'loom_top', 'tanning_rack', 'tanning_rack_side', 'tanning_rack_top',
  'workbench', 'chest_side', 'anvil_side', 'campfire_side',
]);

// Map a pack block basename → engine tile name (or null if we don't use it).
function aliasBlock(name) {
  // Every block_<tile>.png that matches an engine tile is honored — including
  // leaves. Until hand-authored leaf art is dropped in, leaves have no PNG and
  // fall back to the detailed see-through procedural tile.
  if (tileSet.has(name)) return name;              // exact match
  if (name === 'cobblestone') return 'cobble';
  if (name === 'coal_lump') return 'coal_seam';       // manifest name → engine tile
  if (name === 'mossy_cobblestone') return 'mossy_cobble';
  if (name === 'mossy_stone_bricks') return 'mossy_stone_brick';
  if (name === 'clay') return 'clay_block';
  if (name === 'furnace') return 'furnace_front';  // the front face art
  const log = name.match(/^(.+)_log(_top)?$/);      // <wood>_log → <wood>_bark / _ring
  if (log) return log[2] ? `${log[1]}_ring` : `${log[1]}_bark`;
  if (NEW_FACE_TILES.has(name)) return name;
  return null;
}

const dataURI = (file) => `data:image/png;base64,${fs.readFileSync(path.join(SRC, file)).toString('base64')}`;

const files = fs.readdirSync(SRC).filter((f) => f.endsWith('.png'));
const tiles = {};      // engineTile → dataURI
const items = {};      // itemId → dataURI
const skins = {};      // 64×64 player UV skin → dataURI (skin_player_base / skin_armor_*)
const unmappedBlocks = [];
const unmappedItems = [];

for (const f of files) {
  const base = f.replace(/\.png$/, '');
  if (base.startsWith('skin_')) {
    // 32×32 body-material tiles for the player + mobs (skin_fur, skin_hide, …)
    // go on the atlas; the 64×64 full-body player wraps (skin_player_base and
    // skin_armor_<material>) are standalone UV skins, not atlas tiles.
    if (tileSet.has(base)) tiles[base] = dataURI(f);
    else if (/^skin_(player_|armor_)/.test(base)) skins[base] = dataURI(f);
    else unmappedBlocks.push(base);
  } else if (base.startsWith('block_')) {
    const target = aliasBlock(base.slice(6));
    if (target) tiles[target] = dataURI(f);
    else unmappedBlocks.push(base.slice(6));
  } else if (base.startsWith('item_')) {
    const id = base.slice(5);
    if (itemSet.has(id)) items[id] = dataURI(f);
    else unmappedItems.push(id);
  }
}

const header = `// GENERATED by tools/gen-texpack.mjs — do not edit by hand.
// Real 32x32 art from assets/textures/, embedded as base64 for the single-file build.
// TEXPACK_TILES: engine atlas tile name → data URI.  TEXPACK_ITEMS: item id → data URI.
`;
const body = header
  + `export const TEXPACK_TILES = ${JSON.stringify(tiles, null, 0)};\n`
  + `export const TEXPACK_ITEMS = ${JSON.stringify(items, null, 0)};\n`
  + `export const TEXPACK_SKINS = ${JSON.stringify(skins, null, 0)};\n`;
fs.writeFileSync(OUT, body);

const kb = Math.round(fs.statSync(OUT).size / 1024);
console.log(`wrote ${OUT} (${kb} KB)`);
console.log(`tiles embedded: ${Object.keys(tiles).length} / engine ${tileSet.size}`);
console.log(`items embedded: ${Object.keys(items).length} / catalog ${itemSet.size}`);
console.log(`player skins embedded: ${Object.keys(skins).length}`);
if (unmappedBlocks.length) console.log(`UNMAPPED block pngs (skipped): ${unmappedBlocks.sort().join(' ')}`);
if (unmappedItems.length) console.log(`UNMAPPED item pngs (skipped): ${unmappedItems.sort().join(' ')}`);
// tiles the world uses that still fall back to procedural art:
const missing = [...tileSet].filter((t) => !tiles[t] && !t.startsWith('skin_')).sort();
console.log(`\nengine tiles WITHOUT pack art (procedural fallback, ${missing.length}):\n${missing.join(' ')}`);
