// Convert the Nature Props Pack .bbmodels into static 3D prop models the game
// scatters as harvestable forage. Reuses the (fixed) Blockbench converter, so
// hidden reference/hitbox cubes are already dropped. Each prop becomes a single
// static model with its own embedded texture.
//
//   node tools/import-props.mjs [pack-dir] [out.js]
//
// Output: js/gfx/proppack.js — export const PROP_MODELS = { <id>: { texW, texH,
//   texture, parts }, ... }.  Registered by js/game/proppack.js; the forage
//   node defs live in js/game/nodes.js and worldgen scatter in js/world/world.js.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { convertBBModel } from './gen-mobpack.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const PACK = process.argv[2]
  || '/tmp/claude-0/-home-user-test1/5581956a-db33-537d-943c-5bb1e466c794/scratchpad/nature/Nature Props Pack 2 1.21.11+/bbmodels';
const OUT = process.argv[3] || path.join(ROOT, 'js/gfx/proppack.js');

const files = fs.readdirSync(PACK).filter((f) => f.endsWith('.bbmodel')).sort();
const models = {};
const skipped = [];
for (const f of files) {
  const id = f.replace(/\.bbmodel$/, '').toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_+|_+$/g, '');
  try {
    const json = JSON.parse(fs.readFileSync(path.join(PACK, f), 'utf8'));
    const def = convertBBModel(json, { rig: 'lumberer' });
    models[id] = { texW: def.texW, texH: def.texH, texture: def.texture, parts: def.parts };
  } catch (e) {
    skipped.push(`${f} — ${e.message}`);
  }
}

const header = '// GENERATED by tools/import-props.mjs — do not edit by hand.\n'
  + '// Nature Props Pack converted to static 3D forage models (parts + per-box UV\n'
  + '// islands into each prop\'s own embedded texture). See assets/props/CREDITS.md\n'
  + '// for attribution. Registered via js/game/proppack.js; scattered + harvested\n'
  + '// through the resource-node system (js/game/nodes.js, js/world/world.js).\n';
fs.writeFileSync(OUT, header + `export const PROP_MODELS = ${JSON.stringify(models, null, 0)};\n`);

const kb = (p) => Math.round(fs.statSync(p).size / 1024);
console.log(`Imported ${Object.keys(models).length} of ${files.length} nature props.`);
console.log(`  ${path.relative(ROOT, OUT)} — ${kb(OUT)} KB`);
for (const [id, m] of Object.entries(models)) {
  const boxes = m.parts.reduce((a, p) => a + p.boxes.length, 0);
  console.log(`  ${id.padEnd(18)} ${boxes} boxes, tex ${m.texW}x${m.texH}`);
}
if (skipped.length) { console.log('SKIPPED:'); for (const s of skipped) console.log(`  ${s}`); }
