// Guards the imported licensed mob pack (generated by tools/import-mobpack.mjs).
// Every IMPORTED_TYPES entry must be a well-formed ENEMY_TYPES def whose drops
// are real items, must be flagged imported (so it is never worldgen-spawned),
// must have a rig, and must merge into ENEMY_TYPES without clobbering a native.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { IMPORTED_TYPES, IMPORTED_RIGS } from '../../js/game/mobs-imported.js';
import { ENEMY_TYPES } from '../../js/game/enemies.js';
import { ITEMS } from '../../js/game/items.js';

const RIG_STYLES = new Set(['quadruped', 'biped', 'pecker', 'floater', 'hopper', 'scamper', 'slither', 'lumberer', 'sway']);

test('the pack imported a full roster', () => {
  const n = Object.keys(IMPORTED_TYPES).length;
  assert.ok(n >= 90, `expected ~99 imported types, got ${n}`);
  assert.equal(Object.keys(IMPORTED_RIGS).length, n, 'a rig for every imported type');
});

test('every imported type is a well-formed enemy def with real-item drops', () => {
  for (const [id, def] of Object.entries(IMPORTED_TYPES)) {
    assert.ok(def.label, `${id} needs a label`);
    assert.ok(def.hp > 0, `${id} hp must be > 0`);
    assert.ok(Array.isArray(def.model) && def.model.length >= 2, `${id} needs a >=2-box fallback model`);
    assert.ok(def.desc && def.recommend, `${id} needs desc + recommend`);
    assert.ok(['passive', 'aggressive'].includes(def.behavior), `${id} behavior invalid: ${def.behavior}`);
    assert.equal(def.imported, true, `${id} must be flagged imported`);
    assert.ok(def.credit, `${id} needs an attribution credit`);
    assert.ok(Array.isArray(def.abilities) && def.abilities.length === 0, `${id} should carry no abilities`);
    assert.ok(def.drops && def.drops.length, `${id} needs drops`);
    for (const d of def.drops) {
      assert.ok(ITEMS[d.item], `${id} drops unknown item ${d.item}`);
      assert.ok(Array.isArray(d.qty) && d.qty.length === 2 && d.qty[0] >= 1, `${id} drop ${d.item} bad qty`);
      assert.ok(d.chance > 0 && d.chance <= 1, `${id} drop ${d.item} bad chance`);
    }
    assert.ok(RIG_STYLES.has(IMPORTED_RIGS[id]), `${id} has a valid rig style (${IMPORTED_RIGS[id]})`);
  }
});

// Ids the licensed pack ships that a hand-authored native also claims. The
// native wins — the pack spreads first in enemies.js precisely so it cannot
// shadow a curated creature. Add an id here when a native takes over a pack id.
const NATIVE_OVERRIDES = new Set(['zombie']);

test('imported types merge into ENEMY_TYPES without clobbering natives', () => {
  // every imported id is reachable through ENEMY_TYPES
  for (const id of Object.keys(IMPORTED_TYPES)) {
    assert.ok(ENEMY_TYPES[id], `imported ${id} missing from ENEMY_TYPES`);
    if (NATIVE_OVERRIDES.has(id)) {
      assert.ok(!ENEMY_TYPES[id].imported, `${id} is claimed by a native — the native must win`);
      continue;
    }
    assert.equal(ENEMY_TYPES[id].imported, true, `ENEMY_TYPES[${id}] should be the imported def`);
  }
  // natives keep their own (non-imported) defs — collisions were deduped
  for (const nativeId of ['cow', 'pig', 'sheep', 'horse', 'chicken', 'duck', 'pixie']) {
    assert.ok(ENEMY_TYPES[nativeId], `native ${nativeId} vanished`);
    assert.ok(!ENEMY_TYPES[nativeId].imported, `native ${nativeId} was clobbered by an import`);
  }
});
